import express from 'express';
import db from '../db.js';
import {
  COURSE, MODULES, TEMPO_LADDER, TEMPO_LADDER_NOTE,
  ERROR_CODES, REPAIR_PROTOCOL, CHECKPOINTS
} from '../data/course/modules.js';
import { EXERCISES, RECOGNITION_DRILLS, WEEKLY_ROTATION } from '../data/course/exercises.js';
import {
  generateSweep, generateTraversal, startingRows, spellMajorScale,
  renderTab, MILLPAD, SHAPES, KEYS, STRINGS
} from '../utils/millpad.js';
import { buildPaper, publicPaper, gradePaper } from '../utils/test-engine.js';

const router = express.Router();

// ── Syllabus ───────────────────────────────────────────────────────────────

router.get('/', async (req, res) => {
  try {
    const progress = await moduleProgress();

    res.json({
      course: COURSE,
      modules: MODULES.map((m) => {
        const record = progress.get(m.quiz) ?? null;
        return {
          number: m.number,
          code: m.code,
          title: m.title,
          unit: m.unit,
          days: m.days,
          summary: m.summary,
          prerequisites: m.prerequisites,
          objectiveCount: m.objectives.length,
          drills: m.drills,
          quiz: m.quiz,
          // A module unlocks when every prerequisite's quiz has been passed.
          unlocked: m.prerequisites.every((p) => {
            const prereq = MODULES.find((x) => x.number === p);
            return prereq ? progress.get(prereq.quiz)?.passed : true;
          }),
          bestScore: record ? Number(record.best_score) : null,
          passed: Boolean(record?.passed),
          attempts: record ? Number(record.attempts) : 0
        };
      })
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/reference', (req, res) => {
  res.json({
    millpad: MILLPAD.map((m) => ({
      ...m,
      shape: shapeFor(m.label).name,
      steps: shapeFor(m.label).steps,
      offsets: shapeFor(m.label).offsets
    })),
    shapes: Object.values(SHAPES),
    startingRows: startingRows(),
    tempoLadder: TEMPO_LADDER,
    tempoLadderNote: TEMPO_LADDER_NOTE,
    errorCodes: ERROR_CODES,
    repairProtocol: REPAIR_PROTOCOL,
    checkpoints: CHECKPOINTS,
    recognitionDrills: RECOGNITION_DRILLS,
    weeklyRotation: WEEKLY_ROTATION,
    keys: KEYS,
    strings: STRINGS.map((s) => s.name)
  });
});

router.get('/exercises', (req, res) => {
  res.json(EXERCISES);
});

router.get('/modules/:number', async (req, res) => {
  try {
    const number = parseInt(req.params.number, 10);
    const module = MODULES.find((m) => m.number === number);
    if (!module) return res.status(404).json({ error: 'Module not found' });

    // Worked examples are generated by the engine so they can never drift from
    // the theory the module is teaching.
    let worked = null;
    if (module.workedExample) {
      const { key, startString = 0, startFret = 0, traversal } = module.workedExample;
      try {
        if (traversal) {
          const t = generateTraversal({ key, startString, startFret, maxFret: 17 });
          worked = {
            ...module.workedExample,
            traversal: t.passes.map((p) => ({
              direction: p.direction,
              labels: p.groups.map((g) => g.label),
              startFret: p.groups[0].frets[0],
              startNote: p.groups[0].notes[0].name,
              turnaround: { note: p.turnaround.name, fret: p.turnaround.fret }
            })),
            warnings: t.warnings
          };
        } else {
          const sweep = generateSweep({ key, startString, startFret });
          worked = {
            ...module.workedExample,
            scale: sweep.scale.map((n) => n.name),
            groups: sweep.groups,
            line: sweep.line,
            unbroken: sweep.unbroken,
            tab: renderTab(sweep.groups),
            warnings: sweep.warnings
          };
        }
      } catch (err) {
        worked = { ...module.workedExample, error: err.message };
      }
    }

    const drills = module.drills
      .map((id) => EXERCISES.find((e) => e.id === id) ?? RECOGNITION_DRILLS.find((d) => d.id === id))
      .filter(Boolean);

    res.json({ ...module, workedExample: worked, drills });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── The Beast generator ────────────────────────────────────────────────────

router.get('/beast/sweep', (req, res) => {
  try {
    const key = req.query.key ?? 'C';
    const startString = clampInt(req.query.string, 0, 3, 0);
    const startFret = clampInt(req.query.fret, 0, 24, 0);

    const sweep = generateSweep({ key, startString, startFret });
    res.json({
      ...sweep,
      scale: sweep.scale.map((n) => n.name),
      tab: renderTab(sweep.groups)
    });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.get('/beast/traversal', (req, res) => {
  try {
    const key = req.query.key ?? 'C';
    const startFret = clampInt(req.query.fret, 0, 24, 0);
    const maxFret = clampInt(req.query.maxFret, 5, 24, 17);

    const t = generateTraversal({ key, startString: 0, startFret, maxFret });
    res.json({
      key: t.key,
      scale: t.scale.map((n) => n.name),
      warnings: t.warnings,
      passes: t.passes.map((p) => ({
        direction: p.direction,
        groups: p.groups,
        tab: renderTab(p.groups),
        turnaround: p.turnaround
      }))
    });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// Which frets on a given string are valid starting points in a key.
router.get('/beast/valid-starts', (req, res) => {
  try {
    const key = req.query.key ?? 'C';
    const stringIndex = clampInt(req.query.string, 0, 3, 0);
    const scale = spellMajorScale(key);
    const pcs = new Set(scale.map((n) => n.pc));

    const starts = [];
    for (let fret = 0; fret <= 17; fret++) {
      const midi = STRINGS[stringIndex].openMidi + fret;
      const pc = ((midi % 12) + 12) % 12;
      if (pcs.has(pc)) {
        const note = scale.find((n) => n.pc === pc);
        starts.push({ fret, note: note.name, degree: note.degree });
      }
    }

    res.json({ key, string: STRINGS[stringIndex].name, starts });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// ── Tests ──────────────────────────────────────────────────────────────────

router.get('/tests/:quizId', (req, res) => {
  try {
    const seed = Math.floor(Math.random() * 2 ** 31);
    const paper = buildPaper(req.params.quizId, seed);
    res.json(publicPaper(paper));
  } catch (err) {
    res.status(404).json({ error: err.message });
  }
});

router.post('/tests/:quizId/submit', async (req, res) => {
  try {
    const { seed, responses } = req.body;
    if (!Number.isFinite(seed)) {
      return res.status(400).json({ error: 'seed is required to mark the paper' });
    }

    // Rebuilding from the seed reproduces the exact paper the student answered,
    // so the answer key never has to travel to the client or be stored per-attempt.
    const paper = buildPaper(req.params.quizId, seed);
    const graded = gradePaper(paper, responses ?? {});

    await recordAttempt(req.params.quizId, graded);
    res.json(graded);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.get('/progress', async (req, res) => {
  try {
    const progress = await moduleProgress();
    const rows = MODULES.map((m) => {
      const r = progress.get(m.quiz);
      return {
        module: m.number,
        title: m.title,
        quiz: m.quiz,
        attempts: r ? Number(r.attempts) : 0,
        bestScore: r ? Number(r.best_score) : null,
        passed: Boolean(r?.passed),
        lastAttempt: r?.last_attempt ?? null,
        weakTopics: r?.weak_topics ?? []
      };
    });

    const passed = rows.filter((r) => r.passed).length;
    res.json({
      modulesPassed: passed,
      modulesTotal: MODULES.length,
      percentComplete: Math.round((passed / MODULES.length) * 100),
      modules: rows
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── helpers ────────────────────────────────────────────────────────────────

function shapeFor(label) {
  const map = { M: 'WS-WS', I: 'WS-WS', Ly: 'WS-WS', Lo: '1-2-4', P: '1-2-4', A: '1-3-4', D: '1-3-4' };
  return SHAPES[map[label]];
}

function clampInt(value, min, max, fallback) {
  const n = parseInt(value, 10);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}

async function moduleProgress() {
  try {
    const result = await db.query(
      `SELECT quiz_id, attempts, best_score, passed, last_attempt, weak_topics
       FROM course_progress`
    );
    return new Map(result.rows.map((r) => [r.quiz_id, r]));
  } catch (err) {
    console.error('Could not read course progress:', err);
    return new Map();
  }
}

async function recordAttempt(quizId, graded) {
  await db.query(
    `INSERT INTO course_progress
       (quiz_id, attempts, best_score, passed, last_attempt, weak_topics)
     VALUES ($1, 1, $2, $3, NOW(), $4)
     ON CONFLICT (quiz_id) DO UPDATE SET
       attempts = course_progress.attempts + 1,
       best_score = GREATEST(course_progress.best_score, EXCLUDED.best_score),
       passed = course_progress.passed OR EXCLUDED.passed,
       last_attempt = NOW(),
       weak_topics = EXCLUDED.weak_topics`,
    [quizId, graded.score, graded.passed, graded.weakTopics]
  );
}

export default router;
