export type LocalText={en:string;ar:string};
const t=(en:string,ar:string):LocalText=>({en,ar});

export type TheoryConcept={name:LocalText;formula:string;explain:LocalText};
export type TheoryDomain={
 id:string;n:string;level:LocalText;title:LocalText;aim:LocalText;core:LocalText;
 concepts:TheoryConcept[];bass:LocalText;trap:LocalText;proof:LocalText;
};
export type TheoryRow={name:LocalText;formula:string;meaning:LocalText;semitones?:number};
export type TheoryDictionary={id:string;title:LocalText;intro:LocalText;columns:[LocalText,LocalText,LocalText];rows:TheoryRow[]};

export const THEORY_DOMAINS:TheoryDomain[]=[
 {id:"notation",n:"01",level:t("FOUNDATION","أساس"),title:t("Notation, symbols & musical language","النوتة والرموز ولغة المزيكا"),aim:t("Read what another musician means without guessing.","تقرا قصد أي موسيقي من غير تخمين."),core:t("Notation separates pitch, duration, articulation, dynamics and navigation. A bassist must read bass clef and chord symbols, understand rhythmic notation before pitch, and know when two written names describe the same sounding fret but a different harmonic job.","النوتة بتفصل بين النغمة ومدتها وطريقة نطقها والديناميكس ومسار القطعة. عازف الباص لازم يقرا مفتاح فا ورموز الكوردات، يفهم الإيقاع قبل النغمات، ويعرف إمتى اسمين مكتوبين يطلعوا نفس الفريت لكن بوظيفتين هارمونيتين مختلفتين."),concepts:[
  {name:t("Staff, bass clef & register","المدرج ومفتاح فا والمنطقة الصوتية"),formula:"LINES G–B–D–F–A · SPACES A–C–E–G",explain:t("Clef assigns pitch to staff positions; ledger lines extend the range. Octave placement matters because the same pitch class can support, crowd or dominate the ensemble in different registers.","المفتاح بيدي كل مكان على المدرج نغمة؛ والخطوط الإضافية بتوسّع المدى. مكان الأوكتاف مهم لأن نفس النغمة ممكن تسند الفرقة أو تزحمها أو تسيطر عليها حسب المنطقة." )},
  {name:t("Accidentals, key signatures & spelling","علامات التحويل ودليل المفتاح وكتابة النغمة"),formula:"♯ RAISES · ♭ LOWERS · ♮ CANCELS",explain:t("C♯ and D♭ can share a fret, but spelling shows direction and chord function. Write one letter per scale degree and preserve the chord’s thirds so the harmony remains readable.","دو دييز وري بيمول ممكن يبقوا نفس الفريت، لكن الاسم بيشرح الاتجاه ووظيفة الكورد. استخدم حرف مختلف لكل درجة وحافظ على تتابع التالتات عشان الهارموني يفضل مفهوم." )},
  {name:t("Note values, rests, ties & dots","قيم النغمات والسكتات والرباط والنقطة"),formula:"WHOLE 4 · HALF 2 · QUARTER 1 · EIGHTH ½ · 16TH ¼",explain:t("A tie adds durations across beats; a dot adds half the written value; a rest is measured time, not absence of responsibility. Count the full grid even when no note sounds.","الرباط بيجمع مدد عبر النبضات؛ النقطة بتضيف نص القيمة؛ والسكتة وقت محسوب مش إعفاء. عُدّ الشبكة كلها حتى لما مفيش نغمة بتطلع." )},
  {name:t("Articulation, dynamics & road signs","النطق والديناميكس وعلامات الطريق"),formula:"LEGATO · STACCATO · ACCENT · p–f · D.S. · D.C. · CODA",explain:t("Length, accent and volume can change a bass line more than pitch. Repeats, endings, segno and coda define the route; missing one can destroy the form while every note remains correct.","طول النغمة والنبرة والصوت ممكن يغيّروا خط الباص أكتر من النغمات نفسها. الإعادات والنهايات والسيجنو والكودا بيحددوا الطريق؛ علامة واحدة ضايعة ممكن تبوّظ الفورمة رغم إن كل النغمات صح." )},
 ],bass:t("Read rhythm first, mark section boundaries, circle accidentals and decide the octave before playing. TAB can show location, but only notation and chord symbols explain duration, function and ensemble intent.","اقرا الإيقاع الأول، علّم حدود السكاشن، حوّط علامات التحويل، وحدد الأوكتاف قبل العزف. التاب يوريك المكان، لكن النوتة ورمز الكورد هم اللي يشرحوا المدة والوظيفة وقصد الفرقة."),trap:t("Decoding one note at a time and stopping at mistakes. Reading is continuous prediction: eyes ahead, pulse alive, recovery at the next musical checkpoint.","تفك نغمة نغمة وتقف عند كل غلطة. القراية توقّع مستمر: عينك قدّام، النبض شغّال، والرجوع عند أقرب نقطة موسيقية."),proof:t("Sight-read 16 unfamiliar bars in bass clef, count every rest, follow all repeats and explain each accidental and chord symbol afterward.","اقرا ١٦ مازورة جديدة بمفتاح فا، عُدّ كل سكتة، اتبع كل الإعادات، وبعدها اشرح كل علامة تحويل ورمز كورد.")},

 {id:"rhythm",n:"02",level:t("FOUNDATION","أساس"),title:t("Pulse, subdivision, feel & syncopation","النبض والتقسيم والإحساس والسنكوب"),aim:t("Know exactly where a note lives in time—and why it feels good there.","تعرف النغمة مكانها في الوقت بالظبط وليه إحساسها حلو هناك."),core:t("Bass joins rhythm to harmony. Tempo is the speed of the reference pulse; subdivision is the internal grid; feel is how attacks and lengths sit around that grid. Strong time continues through rests, fills, accents and disappearing clicks.","الباص بيوصل الإيقاع بالهارموني. التيمبو سرعة النبض المرجعي؛ التقسيم هو الشبكة الداخلية؛ والإحساس هو الضربات وأطوال النغمات قاعدين إزاي حوالين الشبكة. الوقت القوي يفضل شغّال خلال السكتات والفيلات والنبرات واختفاء الكليك."),concepts:[
  {name:t("Pulse, tempo & internal clock","النبض والتيمبو والساعة الداخلية"),formula:"BPM = BEATS PER MINUTE",explain:t("The pulse is the recurring reference; tempo only measures its rate. Internal time means the body predicts the next pulse without chasing an external click.","النبض هو المرجع المتكرر؛ التيمبو بيقيس سرعته بس. الوقت الداخلي يعني جسمك يتوقع النبضة اللي بعدها من غير ما يجري ورا الكليك." )},
  {name:t("Subdivision hierarchy","هرم التقسيم"),formula:"¼ → ⅛ → 16TH · TRIPLET → ⅛-TRIPLET → 12/8",explain:t("Every attack and rest belongs to a smaller grid. Count or vocalize the smallest active subdivision so syncopation remains deliberate rather than approximate.","كل ضربة وسكتة ليهم مكان على شبكة أصغر. عُدّ أو انطق أصغر تقسيمة شغالة عشان السنكوب يبقى مقصود مش تقريبي." )},
  {name:t("Syncopation & anticipation","السنكوب والتقديم"),formula:"ACCENT OFFBEAT · TIE ACROSS STRONG BEAT · ATTACK BEFORE CHANGE",explain:t("Syncopation shifts expected weight; anticipation states the next harmony early. The effect works only if the listener still feels the unplayed strong beat underneath.","السنكوب بينقل الوزن المتوقع؛ والتقديم بيقول الهارموني اللي جاي بدري. التأثير يشتغل بس لو المستمع لسه حاسس بالنبضة القوية حتى لو ما اتعزفتش." )},
  {name:t("Feel, placement & note length","الإحساس ومكان الضربة وطول النغمة"),formula:"AHEAD · CENTRED · BEHIND · SHORT · CONNECTED",explain:t("Micro-placement and duration shape pocket. Playing behind is not being late, and short is not rushed: both require a stable shared grid and repeatable control.","المكان الدقيق وطول النغمة بيشكّلوا الجروف. العزف ورا النبضة مش تأخير، والنغمة القصيرة مش استعجال: الاتنين محتاجين شبكة مشتركة ثابتة وتحكّم قابل للتكرار." )},
 ],bass:t("Lock the bass attack to the drummer’s chosen reference—often kick, hi-hat subdivision or snare backbeat—then control note endings so the groove breathes. Rests and releases are part of the line.","اربط ضربة الباص بمرجع الدرامز المختار—غالباً الكيك أو تقسيم الهاي هات أو سنير ٢ و٤—وبعدها تحكّم في نهايات النغمات عشان الجروف يتنفس. السكتات وإنهاء النغمة جزء من الخط."),trap:t("Practising only attacks. A line can land on time and still feel bad because releases, accents and subdivision are inconsistent.","تدرّب الضربات بس. الخط ممكن ينزل في الوقت وبرضه إحساسه وحش لأن النهايات والنبرات والتقسيم مش ثابتين."),proof:t("Play one groove through four bars of click and four silent bars, return with the click three times, then reproduce centred, ahead and behind feels without changing tempo.","اعزف جروف ٤ موازير بالكليك و٤ ساكتين، وارجع راكب مع الكليك ٣ مرات، وبعدها كرّر إحساس في النص وقدّام وورا من غير تغيير التيمبو.")},

 {id:"meter",n:"03",level:t("INTERMEDIATE → ADVANCED","متوسط ← متقدم"),title:t("Meter, tuplets, polyrhythm & metric control","الميزان والتقسيمات الغريبة والبوليرذم والتحكّم المتري"),aim:t("Feel complex rhythm as organized cycles, not mathematical panic.","تحس الإيقاع المركب كدورات منظمة مش رعب حسابي."),core:t("Meter groups pulses; beat division decides whether it is simple or compound. Additive meters combine short groups, tuplets divide space unusually, polyrhythms overlay different equal cycles and polymeters align different bar lengths. Metric modulation makes one subdivision become the new pulse.","الميزان بيجمع النبضات؛ تقسيم النبضة بيحدد بسيط ولا مركب. الموازين التجميعية بتجمع وحدات قصيرة، والتوبلت بيقسم الوقت بشكل مختلف، والبوليرذم بيركب دورات متساوية مختلفة، والبوليميتر بيركب أطوال موازير مختلفة. المودوليشن المتري بيحوّل تقسيمة لنبض جديد."),concepts:[
  {name:t("Simple, compound & swing","البسيط والمركب والسوينج"),formula:"4/4 = 4×2 · 6/8 = 2×3 · SWING = UNEQUAL 8TH FEEL",explain:t("Top number counts written units, but felt beats may differ. Compound meter groups eighths in threes; swing shades paired eighths without requiring a rigid triplet ratio.","الرقم اللي فوق بيعد الوحدات المكتوبة، لكن النبضات المحسوسة ممكن تختلف. المركب بيجمع الأثمان تلاتات؛ والسوينج بيلوّن زوج الأثمان من غير نسبة تريبلت ثابتة." )},
  {name:t("Odd and additive meters","الموازين الفردية والتجميعية"),formula:"5 = 3+2 / 2+3 · 7 = 2+2+3 / 3+2+2",explain:t("Group the bar by recurring accents instead of counting a long number string. A bass ostinato should make the grouping obvious to the band and audience.","قسّم المازورة حسب النبرات المتكررة بدل عد سلسلة أرقام طويلة. أوستيناتو الباص لازم يوضح التجميع للفرقة والجمهور." )},
  {name:t("Tuplets, hemiola & displacement","التوبلت والهيميولا والإزاحة"),formula:"3:2 · 5:4 · 3 GROUPS ACROSS 2 BARS",explain:t("Tuplets fit a chosen number of equal events into another value. Hemiola changes perceived grouping; displacement moves a motif while preserving its internal rhythm.","التوبلت بيحط عدد مختار من الأحداث المتساوية جوّه قيمة تانية. الهيميولا بتغيّر التجميع المحسوس؛ والإزاحة بتحرك الموتيف مع الحفاظ على إيقاعه الداخلي." )},
  {name:t("Polyrhythm, polymeter & metric modulation","البوليرذم والبوليميتر والمودوليشن المتري"),formula:"3:2 · 4/4 OVER 3/4 · OLD ⅛-TRIPLET = NEW ⅛",explain:t("Polyrhythm shares a span with different subdivisions; polymeter shares tempo with different bar cycles. Metric modulation preserves a mathematical subdivision relationship while redefining the beat.","البوليرذم بيشارك نفس المدة بتقسيمات مختلفة؛ البوليميتر بيشارك نفس التيمبو بدورات موازير مختلفة. المودوليشن المتري يحافظ على علاقة تقسيم حسابية ويعرّف نبضة جديدة." )},
 ],bass:t("Reduce every complex meter to a vocal pattern, accent map and repeating low-register cell. Make the form audible before adding fills or harmonic movement.","حوّل أي ميزان مركب لنطق وإشارات نبرات وخلية واطية متكررة. خلّي الفورمة مسموعة قبل الفيلات أو الحركة الهارمونية."),trap:t("Counting successfully while the groove has no hierarchy. Mathematics is only useful when accents, phrase length and return points can be heard.","تعد صح لكن الجروف مفيهوش ترتيب وزن. الحساب مفيد بس لما النبرات وطول الجملة ونقط الرجوع يتسمعوا."),proof:t("Clap and play 5/4 in two groupings, 7/8 in three groupings, a 3:2 polyrhythm and one metric modulation, then re-enter beat 1 without a visual counter.","سقّف واعزف ٥/٤ بتجميعين و٧/٨ بتلات تجميعات وبوليرذم ٣:٢ ومودوليشن متري واحد، وبعدها ارجع للنبضة ١ من غير عداد بصري.")},

 {id:"form",n:"04",level:t("ALL LEVELS","كل المستويات"),title:t("Form, phrases, charts & navigation","الفورمة والجمل والشارت ومسار الأغنية"),aim:t("Always know where the music is, what changed and what returns next.","تبقى عارف المزيكا فين وإيه اتغيّر وإيه هيرجع بعده."),core:t("Form organizes time above the bar: motives become phrases, phrases become sections and sections create a complete arc. Harmonic rhythm is the rate of chord change. A professional bassist tracks section length, cues, repeats, endings, pickups, tags, vamps and dynamics while preserving the groove.","الفورمة بتنظم الوقت فوق مستوى المازورة: الموتيف يبقى جملة، والجمل تبقى سكاشن، والسكاشن تعمل قوس كامل. الإيقاع الهارموني هو سرعة تغيير الكوردات. عازف الباص المحترف يتابع طول السكشن والإشارات والإعادات والنهايات والبيك أب والتاج والفامب والديناميكس مع الحفاظ على الجروف."),concepts:[
  {name:t("Motif, phrase, period & cadence","الموتيف والجملة والفترة والقفلة"),formula:"IDEA → QUESTION → ANSWER → ARRIVAL",explain:t("A motif is a reusable identity; a phrase carries it toward punctuation; a period pairs question and answer. Cadence closes or suspends the thought.","الموتيف هوية قابلة للتكرار؛ الجملة بتاخده ناحية علامة وقف؛ والفترة بتجمع سؤال وجواب. القفلة بتنهي الفكرة أو تعلقها." )},
  {name:t("Common song forms","فورمات الأغاني الشائعة"),formula:"VERSE–CHORUS · AABA · 12-BAR BLUES · THROUGH-COMPOSED",explain:t("Form labels describe relationships, not fixed instrumentation. Count actual bars and note altered repeats, pre-choruses, post-choruses, interludes, tags and codas.","أسماء الفورمة بتشرح العلاقات مش آلات ثابتة. عُدّ الموازير الحقيقية وسجّل الإعادات المتغيرة والبري كورس والبوست كورس والفواصل والتاج والكودا." )},
  {name:t("Harmonic rhythm & phrase rhythm","الإيقاع الهارموني وإيقاع الجملة"),formula:"CHANGES PER BAR · PHRASE LENGTH 2/4/8/16",explain:t("Chord-change rate creates momentum independently of tempo. Phrase rhythm tells when ideas begin, repeat, extend or overlap section boundaries.","سرعة تغيير الكوردات بتعمل حركة مستقلة عن التيمبو. إيقاع الجملة بيقول الأفكار تبدأ وتتكرر وتتمدد أو تركب فوق حدود السكاشن إمتى." )},
  {name:t("Lead sheets, road maps & cues","الليد شيت وخريطة الطريق والإشارات"),formula:"INTRO · A · B · SOLO · SHOUT · OUTRO",explain:t("A useful chart states key, meter, tempo, bars, chords, hits, rests and navigation. Cues are musical events—lyric, fill, melody or gesture—not only page numbers.","الشارت المفيد يكتب المفتاح والميزان والتيمبو والموازير والكوردات والضربات والسكتات والطريق. الإشارة حدث موسيقي—كلمة أو فيل أو لحن أو حركة—مش رقم صفحة بس." )},
 ],bass:t("Memorize each section’s first root, length, last-bar cue and dynamic job. If lost, keep pulse, simplify to the tonal centre and recover at the next unmistakable section boundary.","احفظ أول قرار في كل سكشن وطوله وإشارة آخر مازورة ومهمته الديناميكية. لو تهت، حافظ على النبض، بسّط للقرار، وارجع عند أقرب حد سكشن واضح."),trap:t("Knowing the chord loop but not the song. A bassist can repeat correct harmony and still miss the bridge, stop, breakdown or final ending.","تعرف لوب الكوردات ومش عارف الأغنية. ممكن تكرر هارموني صح وتفوّت البريج أو الوقفة أو البريك داون أو النهاية."),proof:t("Hear an unfamiliar song twice, write a bar-accurate road map with cues, then perform the form without looking away from the band.","اسمع أغنية جديدة مرتين، اكتب خريطة دقيقة بالموازير والإشارات، وبعدها اعزف الفورمة من غير ما تبعد عينك عن الفرقة.")},

 {id:"fretboard",n:"05",level:t("FOUNDATION → AUTOMATIC","أساس ← تلقائي"),title:t("Fretboard, tuning, intervals & transposition","الفريت بورد والتونينج والمسافات والنقل"),aim:t("See function everywhere instead of memorizing isolated boxes.","تشوف الوظيفة في كل مكان بدل حفظ بوكسات منفصلة."),core:t("The fretboard is a repeating pitch grid shaped by tuning. Intervals describe distance and function independent of key; transposition preserves relationships while changing absolute pitch. Register, string choice and position change tone and physical phrasing even when the notes are identical.","الفريت بورد شبكة نغمات متكررة شكلها التونينج. المسافات بتشرح البعد والوظيفة بعيد عن المفتاح؛ والنقل بيحافظ على العلاقات ويغيّر النغمة المطلقة. المنطقة والوتر والموضع بيغيّروا الصوت وطريقة الجملة حتى لو النغمات نفسها."),concepts:[
  {name:t("Pitch class, octave & register","فصيلة النغمة والأوكتاف والمنطقة"),formula:"12 PITCH CLASSES · FRET 12 = OCTAVE",explain:t("All Cs share pitch class but not frequency or ensemble role. Register controls weight, clarity, masking and perceived tension.","كل نغمات C من نفس الفصيلة لكن مش نفس التردد أو دور الفرقة. المنطقة بتتحكم في الوزن والوضوح والتغطية والتوتّر المحسوس." )},
  {name:t("Interval number and quality","رقم المسافة ونوعها"),formula:"COUNT LETTERS + COUNT SEMITONES",explain:t("Number comes from letter distance; quality comes from semitones. Perfect families use perfect/augmented/diminished; major families use major/minor plus altered forms.","الرقم جاي من عدد الحروف؛ والنوع من أنصاف التون. عيلة الـperfect فيها تامة وزائدة وناقصة؛ وعيلة الـmajor فيها كبيرة وصغيرة وتحويلاتها." )},
  {name:t("Inversions and compound intervals","قلب المسافات والمسافات المركبة"),formula:"NUMBERS SUM TO 9 · QUALITIES INVERT",explain:t("2↔7, 3↔6 and 4↔5. A tenth is a third plus an octave; compound intervals spread harmony while retaining its function.","٢↔٧ و٣↔٦ و٤↔٥. العاشرة هي تالتة زائد أوكتاف؛ المسافات المركبة بتفتح الهارموني وتحافظ على وظيفته." )},
  {name:t("Tuning geometry and transposition","هندسة التونينج والنقل"),formula:"E–A–D–G = PERFECT 4THS · SAME INTERVALS, NEW ROOT",explain:t("Standard tuning repeats shapes predictably except across range limits. Drop, five- and six-string tunings change available register, not interval theory; recalculate from each open string.","التونينج العادي بيكرر الأشكال بشكل متوقع لحد حدود المدى. الدروب والخمس والست أوتار بيغيّروا المنطقة المتاحة مش نظرية المسافات؛ احسب من كل وتر مفتوح." )},
 ],bass:t("Name every note, degree and interval from the current root; find it on all strings in two registers; then move the whole relationship to a random key without changing fingering logic or rhythmic identity.","سمّي كل نغمة ودرجة ومسافة من القرار الحالي؛ لاقيها على كل الأوتار في منطقتين؛ وبعدها انقل العلاقة كلها لمفتاح عشوائي من غير تغيير منطق الصوابع أو هوية الإيقاع."),trap:t("Knowing one shape and calling it fretboard knowledge. Real command survives a new string, octave, key, direction, tuning and starting finger.","تعرف شكل واحد وتسميه معرفة الفريت بورد. التحكّم الحقيقي يفضل شغال مع وتر وأوكتاف ومفتاح واتجاه وتونينج وصباع بداية جديد."),proof:t("From five random roots, name and play every interval within two seconds below fret 7 and above fret 12, then transpose one bass line through all 12 keys.","من ٥ قرارات عشوائية، سمّي واعزف كل مسافة خلال ثانيتين تحت فريت ٧ وفوق فريت ١٢، وبعدها انقل خط باص واحد للـ١٢ مفتاح.")},

 {id:"scales",n:"06",level:t("FOUNDATION → ADVANCED","أساس ← متقدم"),title:t("Keys, scales, modes & tonal collections","المفاتيح والسلالم والمودات والمجموعات النغمية"),aim:t("Understand what a collection sounds like, how it is spelled and when it applies.","تفهم المجموعة صوتها إيه وبتتكتب إزاي وإمتى تنفع."),core:t("A scale orders pitches around a centre; a key also implies hierarchy and harmonic behavior. Scale formulas are interval maps, not fingering commands. Major and minor systems, pentatonics, blues, modes, chromatic and symmetric collections each offer different degrees of stability and colour.","السلم بيرتب نغمات حوالين مركز؛ المفتاح كمان بيفرض ترتيب وزن وسلوك هارموني. تركيبة السلم خريطة مسافات مش أمر صوابع. الكبير والصغير والبنتاتونيك والبلوز والمودات والكروماتيك والمجموعات المتماثلة كلهم بيدوا درجات مختلفة من الثبات واللون."),concepts:[
  {name:t("Major and the three minor forms","الكبير والتلات أشكال للماينور"),formula:"MAJOR 1 2 3 4 5 6 7 · NAT MIN ♭3 ♭6 ♭7 · HARM MIN 7 · MEL MIN 6 7",explain:t("Natural minor supplies the key collection; harmonic minor strengthens dominant pull; melodic minor smooths the raised 6–7 ascent and becomes a modern chord-scale source.","الماينور الطبيعي بيدي مجموعة المفتاح؛ الهارمونيك ماينور يقوّي جذب الدومينانت؛ والميلوديك ماينور ينعّم طلوع ٦–٧ المرفوعين ويبقى مصدر مودات حديثة." )},
  {name:t("Pentatonic and blues language","لغة البنتاتونيك والبلوز"),formula:"MAJ PENT 1 2 3 5 6 · MIN PENT 1 ♭3 4 5 ♭7 · BLUES + ♭5",explain:t("Removing semitone friction creates portable, open vocabulary. The blues note is expressive motion, not a pitch that must be held or tempered identically in every style.","شيل احتكاك نص التون يعمل مفردات مفتوحة وسهلة النقل. نغمة البلوز حركة تعبيرية مش نغمة لازم تتثبت بنفس الضبط في كل ستايل." )},
  {name:t("Modes and characteristic degrees","المودات ودرجات الهوية"),formula:"PARALLEL COMPARISON AROUND ONE ROOT",explain:t("Hear each mode against the same tonic and compare the one or two degrees that change its gravity. Parent-scale derivation explains spelling; parallel sound explains music.","اسمع كل مود على نفس القرار وقارن الدرجة أو الدرجتين اللي بيغيّروا الجاذبية. السلم الأم يشرح الكتابة؛ والصوت الموازي يشرح المزيكا." )},
  {name:t("Chromatic, whole-tone, diminished & synthetic scales","الكروماتيك والـwhole-tone والديمينشد والسلالم المصنعة"),formula:"12-TONE · 6 EQUAL WHOLE STEPS · H–W / W–H",explain:t("Symmetric scales reduce a unique tonic and serve specific dominant or diminished colors. Synthetic collections are valid only when their interval identity and harmonic context are audible.","السلالم المتماثلة بتقلل وضوح قرار واحد وبتخدم ألوان دومينانت أو ديمينشد محددة. أي مجموعة مصنّعة تنفع بس لما هوية مسافاتها وسياقها الهارموني يتسمعوا." )},
 ],bass:t("For every scale, sing 1 and the defining degrees, spell it correctly, map it in two regions, build its chords and create a groove with no more than five pitches before running the full shape.","لكل سلم، غنّي ١ ودرجات الهوية، اكتبه صح، ارسمه في منطقتين، ابنِ كورداته، واعمل جروف بخمس نغمات أو أقل قبل ما تجري الشكل كامل."),trap:t("Treating a scale as a list of allowed notes. Rhythm, chord function, target, register and duration decide whether a theoretically available note works now.","تعامل السلم كقائمة نغمات مسموحة. الإيقاع ووظيفة الكورد والهدف والمنطقة والمدة هم اللي يحددوا النغمة النظرية تنفع دلوقتي ولا لأ."),proof:t("Given any root and chord context, spell the relevant collection, sing its identity, locate it across the neck and make it recognizable in an original four-bar bass line.","مع أي قرار وسياق كورد، اكتب المجموعة المناسبة، غنّي هويتها، لاقيها على الرقبة كلها، وخلّيها معروفة في خط باص أصلي ٤ موازير.")},

 {id:"chords",n:"07",level:t("FOUNDATION → ADVANCED","أساس ← متقدم"),title:t("Chord construction, extensions & slash harmony","بناء الكوردات والإضافات والسلاش هارموني"),aim:t("Know what every chord symbol contains, omits and asks the bass to clarify.","تعرف كل رمز كورد فيه إيه وشايل إيه وعايز الباص يوضح إيه."),core:t("Chords are interval structures heard simultaneously or arpeggiated. Stacking diatonic thirds creates triads, sevenths and extensions; alterations change specific degrees. Inversions and slash chords assign the bass note explicitly, so the bassist can redefine stability and motion without changing the upper voices.","الكوردات هياكل مسافات بتتسمع مع بعض أو كأربيج. رص التالتات الدياتونيك بيبني تراياد وسابعة وإضافات؛ علامات التحويل بتغيّر درجات محددة. القلب والسلاش كورد بيحددوا نغمة الباص، فالباص يقدر يعيد تعريف الثبات والحركة من غير تغيير الأصوات العالية."),concepts:[
  {name:t("Triads and suspended chords","التراياد والكوردات المعلقة"),formula:"MAJ 1 3 5 · MIN 1 ♭3 5 · DIM 1 ♭3 ♭5 · AUG 1 3 ♯5 · SUS 1 4/2 5",explain:t("The third defines major/minor; the fifth defines stability or alteration. Sus replaces the third and delays quality rather than adding another ordinary extension.","التالتة بتحدد ميجور أو ماينور؛ الخامسة بتحدد الثبات أو التحويل. الـsus بيشيل التالتة ويعلّق النوع مش بيضيف extension عادي." )},
  {name:t("Seventh-chord families","عائلات كوردات السابعة"),formula:"MAJ7 · 7 · m7 · m7♭5 · dim7 · mMaj7",explain:t("Third and seventh are the main guide tones. Their qualities distinguish tonic major, dominant, minor, half-diminished, fully diminished and minor-major colors.","التالتة والسابعة أهم guide tones. نوعهم بيفرّق بين تونك ميجور ودومينانت وماينور ونص ديمينشد وديمينشد كامل وماينور ميجور." )},
  {name:t("Extensions, adds and alterations","الإضافات والـadd والتحويلات"),formula:"9=2 · 11=4 · 13=6 · ♭9 ♯9 ♯11 ♭13",explain:t("Extensions assume a seventh-chord stack unless marked add. Alterations belong to chord function and voice leading; they are tensions with destinations, not decorative spelling.","الـextensions غالباً بتفترض كورد سابعة إلا لو مكتوب add. التحويلات مرتبطة بوظيفة الكورد وحركة الأصوات؛ هي توتّرات ليها أهداف مش زينة في الرمز." )},
  {name:t("Inversions, slash chords & upper structures","القلب والسلاش كورد والهياكل العليا"),formula:"C/E · Dm/C · G/A · TRIAD OVER BASS",explain:t("A slash note is the required bass pitch, which may be an inversion, pedal or independent harmony. Upper structures describe colors above a stable bass and can imply extended or altered sonorities.","النغمة بعد السلاش هي نغمة الباص المطلوبة، وممكن تكون قلب أو بيدال أو هارموني مستقل. الهياكل العليا بتشرح ألوان فوق باص ثابت وممكن تدي كوردات ممتدة أو متحوّلة." )},
 ],bass:t("On each symbol, identify required root or slash note, third, seventh and destination. Omit low extensions that muddy the arrangement; state enough information for the harmony without competing with the keyboard or guitar.","مع كل رمز، حدد القرار أو نغمة السلاش والتالتة والسابعة والهدف. شيل الإضافات الواطية اللي بتعجّن التوزيع؛ قول معلومات كفاية للهارموني من غير منافسة الكيبورد أو الجيتار."),trap:t("Playing the full scale because the chord symbol looks complicated. First reduce the symbol to bass note, quality, seventh and altered destination.","تجري سلم كامل لأن رمز الكورد شكله معقد. الأول اختصر الرمز لنغمة الباص والنوع والسابعة والهدف المتحوّل."),proof:t("Spell and arpeggiate 20 common chord symbols from random roots, name their guide tones, then choose a clean bass note and next destination in a real progression.","اكتب واعزف أربيج لـ٢٠ رمز كورد شائع من قرارات عشوائية، سمّي guide tones، وبعدها اختار نغمة باص نضيفة والهدف اللي بعدها في بروجرشن حقيقي.")},

 {id:"diatonic",n:"08",level:t("INTERMEDIATE","متوسط"),title:t("Diatonic harmony, numbers & key relationships","الهارموني الدياتونيك والأرقام وعلاقات المفاتيح"),aim:t("Generate the chords of any key and understand their local jobs.","تولّد كوردات أي مفتاح وتفهم شغلهم المحلي."),core:t("Diatonic harmony builds chords only from a key’s notes. Roman numerals describe scale-degree root and quality; Nashville numbers prioritize transposable roots and practical charts. Relative keys share notes, parallel keys share tonic, and borrowed chords temporarily import color from a parallel system.","الهارموني الدياتونيك بيبني كوردات من نغمات المفتاح بس. الأرقام الرومانية بتشرح درجة القرار ونوع الكورد؛ أرقام ناشفيل بتركز على قرارات قابلة للنقل وشارتات عملية. المفاتيح النسبية بتشارك النغمات، والموازية بتشارك القرار، والكورد المستعار بيجيب لون مؤقت من نظام موازي."),concepts:[
  {name:t("Key signatures and circle of fifths","دليل المفتاح ودائرة الخامسات"),formula:"CLOCKWISE +1♯ · COUNTERCLOCKWISE +1♭",explain:t("The circle organizes key signatures, dominant–tonic relationships and nearby modulation options. It predicts spelling; it does not dictate which chord must come next.","الدائرة بتنظم أدلة المفاتيح وعلاقة الدومينانت بالقرار وتحويلات قريبة. هي بتتوقع الكتابة؛ مش بتفرض الكورد اللي لازم ييجي بعده." )},
  {name:t("Harmonizing the major scale","هارمنة السلم الكبير"),formula:"I maj7 · ii m7 · iii m7 · IV maj7 · V7 · vi m7 · viiø",explain:t("Stack alternate scale degrees. The pattern transposes intact and supplies chord tones, functions and available voice-leading routes in every major key.","رص درجة وسيب درجة. الباترن بيتنقل زي ما هو وبيدي نغمات الكورد والوظائف ومسارات حركة الأصوات في كل مفتاح ميجور." )},
  {name:t("Roman numerals and Nashville numbers","الأرقام الرومانية وأرقام ناشفيل"),formula:"QUALITY + SCALE DEGREE · 1–7 WITH ALTERATIONS",explain:t("Roman case and symbols preserve analytical quality; Nashville notation communicates roots, bars, pushes and inversions quickly in sessions.","شكل الرقم الروماني ورموزه بيحافظوا على النوع التحليلي؛ ناشفيل بيوصل القرارات والموازير والتقديم والقلب بسرعة في السيشن." )},
  {name:t("Relative, parallel and borrowed harmony","النسبي والموازي والهارموني المستعار"),formula:"C MAJOR ↔ A MINOR · C MAJOR ↔ C MINOR",explain:t("Relative systems share collection but not gravity. Parallel borrowing changes one or more degrees around the same tonic, creating color such as iv, ♭VI or ♭VII in major.","الأنظمة النسبية بتشارك المجموعة مش الجاذبية. الاستعارة الموازية بتغيّر درجة أو أكتر حوالين نفس القرار، وتعمل ألوان زي iv أو ♭VI أو ♭VII في الميجور." )},
 ],bass:t("Reduce every progression to numbers, identify structural beats and roots, then choose when to state roots, thirds, fifths, sevenths, inversions or approaches. Numbers reveal transposition; chord tones reveal the line.","اختصر أي بروجرشن لأرقام، حدد النبضات الأساسية والقرارات، وبعدها اختار إمتى تقول القرار أو التالتة أو الخامسة أو السابعة أو القلب أو الاقتراب. الأرقام تشرح النقل؛ ونغمات الكورد تعمل الخط."),trap:t("Assuming every diatonic chord has equal weight. Position in phrase, duration, melody and bass motion can make the same chord structural, passing or prolongational.","تفترض كل كورد دياتونيك له نفس الوزن. مكانه في الجملة ومدته واللحن وحركة الباص ممكن يخلوا نفس الكورد أساسي أو عابر أو بيمد هارموني تاني."),proof:t("In all 12 keys, state the diatonic triads and sevenths, analyze a progression in Roman and Nashville numbers, then transpose it without rewriting shapes.","في الـ١٢ مفتاح، قول التراياد وكوردات السابعة الدياتونيك، حلّل بروجرشن بالروماني وناشفيل، وبعدها انقله من غير ما تعيد كتابة الأشكال.")},

 {id:"function",n:"09",level:t("INTERMEDIATE → ADVANCED","متوسط ← متقدم"),title:t("Function, cadences, tonicization & modulation","الوظيفة والقفلات والتونيك المؤقت والتحويل"),aim:t("Hear why harmony moves and where it is trying to arrive.","تسمع الهارموني بيتحرك ليه وعايز يوصل لفين."),core:t("Functional harmony groups chords by behavior: tonic stability, predominant departure and dominant demand for resolution. Cadences articulate phrases. Secondary dominants briefly tonicize a target; modulation establishes a new key strongly enough that its functions and cadences replace the old centre.","الهارموني الوظيفي بيجمع الكوردات حسب سلوكها: ثبات التونك، خروج الـpredominant، وطلب الدومينانت للقفلة. القفلات بتفصل الجمل. الدومينانت الثانوي يعمل تونك مؤقت؛ والتحويل يثبت مفتاح جديد لدرجة إن وظائفه وقفلاته ياخدوا مكان المركز القديم."),concepts:[
  {name:t("Tonic, predominant and dominant","تونك وبري دومينانت ودومينانت"),formula:"T → PD → D → T",explain:t("Function is behavior, not one chord name. Substitutes share important tones and directional tendencies; bass motion can strengthen or weaken the perceived function.","الوظيفة سلوك مش اسم كورد واحد. البدائل بتشارك نغمات مهمة واتجاهات؛ وحركة الباص ممكن تقوّي أو تضعف الوظيفة المسموعة." )},
  {name:t("Cadence families","عائلات القفلات"),formula:"AUTHENTIC V–I · HALF →V · PLAGAL IV–I · DECEPTIVE V–vi",explain:t("Cadences combine harmonic arrival, metric placement and melodic closure. A V–I off the phrase ending may not feel cadential at all.","القفلة بتجمع وصول هارموني ومكان متري ونهاية لحنية. V–I بعيد عن نهاية الجملة ممكن ما يتحسش قفلة أصلاً." )},
  {name:t("Secondary dominants and tonicization","الدومينانت الثانوي والتونيك المؤقت"),formula:"V/x → x · LEADING-TONE CHORD vii°/x",explain:t("A chromatic dominant points to a diatonic or borrowed target. Its altered notes are locally functional, so the bass should expose destination and guide-tone motion.","دومينانت كروماتيك بيشاور على هدف دياتونيك أو مستعار. نغماته المتغيرة ليها وظيفة محلية، فالباص يوضح الهدف وحركة guide tones." )},
  {name:t("Modulation and pivot logic","التحويل ومنطق الكورد المشترك"),formula:"COMMON CHORD · COMMON TONE · DIRECT · SEQUENCE",explain:t("A pivot can belong to both keys; direct modulation changes without one. A new key is confirmed by sustained hierarchy, dominant action, cadence and phrase-level emphasis—not one accidental.","الكورد المشترك ممكن ينتمي للمفتاحين؛ التحويل المباشر يغيّر من غيره. المفتاح الجديد يتثبت بترتيب وزن مستمر ودومينانت وقفلة وتركيز على مستوى الجملة—مش علامة تحويل واحدة." )},
 ],bass:t("Pre-hear the destination root and guide tones. Use stepwise, chromatic or common-tone motion to make function audible; on modulation, establish the new tonic through register, duration and arrival placement.","اسمع قرار الهدف وguide tones قبل العزف. استخدم حركة خطوة أو كروماتيك أو نغمة مشتركة عشان الوظيفة تتسمع؛ ومع التحويل ثبّت القرار الجديد بالمنطقة والمدة ومكان الوصول."),trap:t("Calling every chromatic chord a key change or every V–I a modulation. Ask whether the new centre persists, receives its own functions and controls the phrase ending.","تسمي كل كورد كروماتيك تغيير مفتاح أو كل V–I تحويل. اسأل: المركز الجديد استمر؟ خد وظائفه؟ حكم نهاية الجملة؟"),proof:t("Analyze and play tonic–predominant–dominant routes, four cadence types, three secondary dominants and two modulation methods while naming every destination before it sounds.","حلّل واعزف طرق تونك–بري دومينانت–دومينانت وأربع قفلات وتلات دومينانت ثانوي وطريقتين تحويل، وسمّي كل هدف قبل ما يتسمع.")},

 {id:"voice",n:"10",level:t("INTERMEDIATE → PROFESSIONAL","متوسط ← احترافي"),title:t("Voice leading, inversions & bass motion","حركة الأصوات والقلب وحركة الباص"),aim:t("Connect harmony with the smallest meaningful movement.","توصل الهارموني بأصغر حركة ليها معنى."),core:t("Voice leading treats each chord tone as a melodic line. Thirds and sevenths expose quality and function; common tones hold continuity; semitone and whole-step destinations create inevitability. Because the bass defines inversion, its line can smooth harmony, intensify a cadence or deliberately resist the upper voices.","حركة الأصوات بتعامل كل نغمة كورد كخط لحني. التالتة والسابعة بيكشفوا النوع والوظيفة؛ النغمة المشتركة تمسك الاستمرارية؛ وأهداف نص التون والتون تعمل إحساس حتمي. لأن الباص بيحدد القلب، خطه يقدر ينعّم الهارموني أو يقوّي القفلة أو يقاوم الأصوات العالية بقصد."),concepts:[
  {name:t("Guide tones and tendency tones","Guide tones ونغمات الاتجاه"),formula:"3RD + 7TH · 7→1 · 4→3",explain:t("Guide tones identify chord family; tendency tones have strong contextual destinations. Hearing them first prevents scale choices from obscuring progression.","Guide tones بتحدد عيلة الكورد؛ ونغمات الاتجاه ليها أهداف سياقية قوية. سماعهم الأول يمنع اختيارات السلم من تغطية البروجرشن." )},
  {name:t("Common, contrary and oblique motion","الحركة المشتركة والعكسية والثابتة"),formula:"HOLD · MOVE TOGETHER · MOVE OPPOSITE",explain:t("Different motion types control independence and smoothness. Contrary motion opens texture; oblique motion preserves a pedal; similar motion can strengthen contour but risks parallel weight.","أنواع الحركة بتتحكم في الاستقلال والنعومة. العكسية بتفتح النسيج؛ والثابتة تمسك بيدال؛ والمتشابهة تقوّي المسار لكن ممكن تعمل وزن متوازي." )},
  {name:t("Inversions and linear bass","القلب وخط الباص المتحرك"),formula:"ROOT · 1ST INV 3RD · 2ND INV 5TH · 3RD INV 7TH",explain:t("Inversions preserve chord identity while changing bass direction and stability. A linear bass can connect static upper harmony through scale, chromatic or patterned motion.","القلب بيحافظ على هوية الكورد ويغيّر اتجاه الباص وثباته. خط باص متحرك يقدر يوصل هارموني عالي ثابت بحركة سلمية أو كروماتيك أو باترن." )},
  {name:t("Pedal, ostinato and contrary harmony","البيدال والأوستيناتو والهارموني المعاكس"),formula:"FIXED BASS UNDER CHANGES · REPEATED CELL",explain:t("A pedal makes upper chords relate to one sustained bass; an ostinato adds rhythmic identity. Both can create deliberate nonfunctional tension and slash-chord colors.","البيدال بيخلي الكوردات العالية تتنسب لباص ثابت؛ والأوستيناتو يضيف هوية إيقاعية. الاتنين يعملوا توتّر غير وظيفي مقصود وألوان سلاش كورد." )},
 ],bass:t("Build the destination skeleton first: required bass note, third and seventh. Connect by nearest meaningful motion, then add approaches only if the skeleton remains singable without accompaniment.","ابنِ هيكل الهدف الأول: نغمة الباص المطلوبة والتالتة والسابعة. وصل بأقرب حركة ليها معنى، وبعدها ضيف اقترابات بس لو الهيكل لسه قابل للغنا من غير مصاحبة."),trap:t("Choosing a scale for every chord before hearing the line. Harmony is often clearer from two connected guide tones than from seven available pitches.","تختار سلم لكل كورد قبل ما تسمع الخط. الهارموني غالباً أوضح من guide tones متوصلين أكتر من سبع نغمات متاحة."),proof:t("Play a progression as roots, then inversions, guide-tone shells and one chromatic version; the chord movement must remain identifiable with no accompaniment.","اعزف بروجرشن كقرارات، وبعدها قلوب وguide-tone shells ونسخة كروماتيك واحدة؛ حركة الكوردات لازم تفضل معروفة من غير مصاحبة.")},

 {id:"modal",n:"11",level:t("INTERMEDIATE → ADVANCED","متوسط ← متقدم"),title:t("Modal, pedal & nonfunctional harmony","الهارموني المقامي والبيدال وغير الوظيفي"),aim:t("Develop one sound deeply without forcing dominant–tonic logic.","تطوّر صوت واحد بعمق من غير فرض منطق دومينانت–تونك."),core:t("Modal harmony establishes a tonic through repetition, duration, register and pedal rather than functional cadences. Characteristic degrees distinguish parallel modes. Chords may color one centre without demanding a new key, and planing or quartal structures can move by shape and voice rather than classical function.","الهارموني المقامي بيثبت القرار بالتكرار والمدة والمنطقة والبيدال بدل القفلات الوظيفية. درجات الهوية بتفرق المودات الموازية. الكوردات ممكن تلوّن مركز واحد من غير طلب مفتاح جديد، والبلانينج أو تراكيب الرابعة تتحرك بالشكل والصوت بدل الوظيفة الكلاسيكية."),concepts:[
  {name:t("Parent versus parallel modes","المود الأم والمود الموازي"),formula:"C MAJOR MODES SHARE NOTES · C MODES SHARE TONIC",explain:t("Parent thinking explains derivation; parallel comparison reveals sound. A bassist improvises more reliably by hearing degree function from the actual tonic.","تفكير السلم الأم يشرح الاشتقاق؛ المقارنة الموازية تكشف الصوت. عازف الباص يرتجل بثبات أكتر لما يسمع وظيفة الدرجة من القرار الحقيقي." )},
  {name:t("Characteristic tones and modal cadence","درجات الهوية والقفلة المقامية"),formula:"DORIAN 6 · PHRYGIAN ♭2 · LYDIAN ♯4 · MIXOLYDIAN ♭7",explain:t("Identity emerges when the defining degree is exposed against tonic and resolved in a characteristic phrase. Repetition without context can make it sound accidental.","الهوية تظهر لما درجة اللون تتكشف قدام القرار وتقفل في جملة مميزة. التكرار من غير سياق ممكن يخليها تتسمع غلطة." )},
  {name:t("Modal chord fields and pedal points","مجال الكوردات المقامية والبيدال"),formula:"TONIC PEDAL + COLOR CHORDS",explain:t("Upper structures can shift while bass preserves centre. Chord choice should emphasize the mode’s unique degrees and avoid accidentally importing stronger functional gravity.","الهياكل العالية ممكن تتغير والباص ماسك المركز. اختيار الكورد يبرز درجات المود المميزة ويتجنب إدخال جاذبية وظيفية أقوى بالغلط." )},
  {name:t("Quartal harmony, planing & constant structure","هارموني الرابعة والبلانينج والشكل الثابت"),formula:"STACK 4THS · MOVE SAME VOICING",explain:t("Quartal sonorities soften major/minor identity; planing moves a voicing in parallel. Both are controlled by centre, register, contour and voice-leading context.","تراكيب الرابعة بتخفف هوية الميجور/ماينور؛ والبلانينج بيحرك نفس الفويسنج بالتوازي. الاتنين بيتحكم فيهم القرار والمنطقة والمسار وسياق حركة الأصوات." )},
 ],bass:t("Establish tonic unmistakably, feature the characteristic degree without scale-running, keep a repeated rhythmic identity and treat upper chord changes as colors around home until the music proves otherwise.","ثبّت القرار بوضوح، ابرز درجة الهوية من غير جري سلم، حافظ على هوية إيقاعية متكررة، وتعامل مع تغييرات الكوردات العالية كألوان حوالين البيت لحد ما المزيكا تثبت غير كده."),trap:t("Equating a mode with its parent major scale or assigning a new mode to every chord. Modal music needs one audible centre and phrase behavior, not labels alone.","تساوي المود بالسلم الميجور الأم أو تدي كل كورد مود جديد. المزيكا المقامية محتاجة مركز مسموع وسلوك جملة، مش أسماء بس."),proof:t("Make all seven parallel modes recognizable with four or five pitches, then support a modal vamp for three minutes without losing tonic, time or motif identity.","خلّي السبع مودات الموازية معروفة بأربع أو خمس نغمات، وبعدها اسند فامب مقامي ٣ دقايق من غير ضياع القرار أو الوقت أو هوية الموتيف.")},

 {id:"bassline",n:"12",level:t("ALL LEVELS","كل المستويات"),title:t("Bass-line construction & ensemble function","بناء خط الباص ووظيفته في الفرقة"),aim:t("Choose the smallest line that makes time, harmony and form undeniable.","تختار أصغر خط يخلي الوقت والهارموني والفورمة واضحين."),core:t("A bass line is not a scale exercise under chords. It establishes harmonic roots and inversions, locks rhythmic hierarchy, outlines form, controls energy and connects destinations. Repetition creates identity; variation creates development; register, articulation and silence decide how much space the line occupies.","خط الباص مش تمرين سلم تحت الكوردات. هو بيثبت القرارات والقلوب، يقفل ترتيب الإيقاع، يوضح الفورمة، يتحكم في الطاقة، ويوصل الأهداف. التكرار يعمل هوية؛ التغيير يعمل تطوير؛ والمنطقة والنطق والسكتة يحددوا الخط واخد مساحة قد إيه."),concepts:[
  {name:t("Role hierarchy","ترتيب وظائف الباص"),formula:"TIME → FORM → HARMONY → FEEL → DECORATION",explain:t("If a fill damages time or form, it is too expensive. Supportive playing can be simple in pitch while sophisticated in placement, length and dynamics.","لو الفيل بوّظ الوقت أو الفورمة فتكلفته عالية. العزف الداعم ممكن يبقى بسيط نغمياً ومعقد في المكان والطول والديناميكس." )},
  {name:t("Structural beats and target hierarchy","النبضات الأساسية وترتيب الأهداف"),formula:"ROOT/SLASH ON ARRIVAL · 3RD/7TH FOR QUALITY · 5TH FOR SUPPORT",explain:t("Strong arrivals need clear harmonic evidence; weaker subdivisions carry approach, repetition or color. Context can deliberately reverse the hierarchy.","الوصولات القوية محتاجة دليل هارموني واضح؛ التقسيمات الأضعف تشيل اقتراب أو تكرار أو لون. السياق ممكن يعكس الترتيب بقصد." )},
  {name:t("Approach vocabulary","مفردات الاقتراب"),formula:"DIATONIC · CHROMATIC BELOW/ABOVE · ENCLOSURE · SCALE RUN",explain:t("Choose the destination first and fit the path to available time. An approach gains meaning from landing placement, not from being chromatic by itself.","اختار الهدف الأول وركّب الطريق على الوقت المتاح. الاقتراب بياخد معناه من مكان النزول مش من كونه كروماتيك لوحده." )},
  {name:t("Repetition, variation, fills and space","التكرار والتغيير والفيلات والسكتة"),formula:"STATE → REPEAT → VARY ONE THING → RETURN",explain:t("Change rhythm, ending, register, articulation or density one at a time. A fill should answer the song and hand the next downbeat back clearly.","غيّر الإيقاع أو النهاية أو المنطقة أو النطق أو الكثافة حاجة واحدة كل مرة. الفيل يجاوب الأغنية ويسلّم أول نبضة اللي بعدها بوضوح." )},
 ],bass:t("Start with roots and exact note lengths against drums. Add thirds or sevenths for quality, approaches into named destinations, and fills only at phrase openings; remove anything that weakens the original pocket.","ابدأ بالقرارات وأطوال نغمات دقيقة قدام الدرامز. ضيف تالتات أو سابعات للنوع، واقترابات لأهداف متسماة، وفيلات عند فتح الجمل بس؛ شيل أي حاجة تضعف الجروف الأصلي."),trap:t("Judging a line by difficulty or note count. The real test is whether the band’s time, harmony, section and emotional direction become clearer.","تحكم على الخط بالصعوبة أو عدد النغمات. الاختبار الحقيقي: وقت الفرقة والهارموني والسكشن والاتجاه العاطفي بقوا أوضح؟"),proof:t("Create three different lines over one progression: minimum support, stylistic pocket and melodic development. All three must preserve form and be recognizable without chordal accompaniment.","اعمل ٣ خطوط مختلفة على بروجرشن واحد: أقل دعم، جروف ستايل، وتطوير لحني. التلاتة يحافظوا على الفورمة ويتعرفوا من غير آلة كوردات.")},

 {id:"styles",n:"13",level:t("INTERMEDIATE → PROFESSIONAL","متوسط ← احترافي"),title:t("Style grammar, forms & historical vocabulary","قواعد الستايلات والفورمات والمفردات التاريخية"),aim:t("Sound stylistically credible before adding your personal voice.","تطلع مقنع في الستايل قبل ما تضيف صوتك الشخصي."),core:t("Style is a system of rhythmic placement, note length, harmonic vocabulary, form, tone, articulation and ensemble interaction—not a collection of licks. Learn representative recordings, historical lineage and the drummer relationship, then separate transferable principles from artist-specific imitation.","الستايل نظام من مكان الإيقاع وطول النغمة والهارموني والفورمة والصوت والنطق وتفاعل الفرقة—مش مجموعة ليكات. اتعلم تسجيلات مرجعية وتاريخ الستايل وعلاقة الدرامر، وبعدها افصل المبادئ القابلة للنقل عن تقليد عازف بعينه."),concepts:[
  {name:t("Blues, jazz and walking","البلوز والجاز والـwalking"),formula:"12-BAR · ii–V–I · CHORD TONE ON BEAT · APPROACH NEXT ROOT",explain:t("Walking balances quarter-note time, chord clarity, voice leading and melodic contour. Blues harmony mixes dominant color, call/response and flexible thirds.","الـwalking يوازن نوار ثابت ووضوح كورد وحركة أصوات ومسار لحني. البلوز بيخلط لون الدومينانت والنداء/الجواب وتالتات مرنة." )},
  {name:t("Funk, soul, Motown and R&B","الفانك والسول والموتاون والـR&B"),formula:"ONE · 16TH GRID · SYNCOPATION · MOTIF VARIATION",explain:t("Repetition, ghost placement, anticipations and controlled chromatic approaches create forward motion. Note length and kick relationship are central style markers.","التكرار ومكان المكتوم والتقديم والاقترابات الكروماتيك المتحكم فيها بيعملوا حركة. طول النغمة وعلاقتها بالكيك علامات أساسية للستايل." )},
  {name:t("Rock, grunge, metal, pop and reggae","الروك والجرنج والميتال والبوب والريجي"),formula:"RIFF/ROOT SUPPORT · SECTION ENERGY · REGGAE SPACE/DELAY",explain:t("Rock-family bass may double riffs, anchor roots or create countermelody; genre changes attack and density. Reggae often prioritizes deep placement, short harmonic vocabulary and negative space.","باص عيلة الروك ممكن يضاعف الريف أو يثبت القرارات أو يعمل لحن مقابل؛ النوع بيغيّر الضربة والكثافة. الريجي غالباً يركز على مكان عميق ومفردات هارمونية قليلة ومساحة سلبية." )},
  {name:t("Latin, Afrobeat, electronic and progressive systems","اللاتين والأفروبيت والإلكتروني والبروج"),formula:"CLAVE/TUMBAO · INTERLOCKING OSTINATI · LOOP EVOLUTION · ODD GROUPS",explain:t("These broad families contain many distinct traditions. Learn the governing timeline, percussion relationship and form from authentic sources; do not reduce them to one generic pattern.","العائلات الواسعة دي فيها تقاليد مختلفة كتير. اتعلم الخط الزمني الحاكم وعلاقة الإيقاع والفورمة من مصادر أصلية؛ ما تختصرهمش في باترن عام واحد." )},
 ],bass:t("For each style, document subdivision, primary drum lock, typical note length, harmonic density, form, common approaches and three reference players. Reproduce the grammar, then create a new line without copying a recording.","لكل ستايل، اكتب التقسيم وقفل الدرامز الأساسي وطول النغمة المعتاد وكثافة الهارموني والفورمة والاقترابات الشائعة وتلات عازفين مرجع. كرّر القواعد وبعدها اعمل خط جديد من غير نسخ تسجيل."),trap:t("Using tone or technique as the whole style: fuzz does not create grunge, slap does not create funk and roots alone do not create reggae.","تستخدم الصوت أو التكنيك كأنه الستايل كله: الفاز مش بيعمل جرنج، والسلاب مش بيعمل فانك، والقرارات لوحدها مش بتعمل ريجي."),proof:t("Perform the same progression convincingly in six contrasting styles; a listener should identify each from time feel, articulation and line design before hearing the tone preset.","اعزف نفس البروجرشن بشكل مقنع في ٦ ستايلات مختلفة؛ المستمع يعرف كل واحد من إحساس الوقت والنطق وتصميم الخط قبل ما يسمع البريست.")},

 {id:"improv",n:"14",level:t("INTERMEDIATE → ADVANCED","متوسط ← متقدم"),title:t("Improvisation, melody & motivic development","الارتجال واللحن وتطوير الموتيف"),aim:t("Create a coherent statement instead of reciting available material.","تعمل جملة مترابطة بدل تسميع نغمات متاحة."),core:t("Improvisation organizes melody, rhythm, harmony, form and color in real time. Chord tones provide structure, target notes create direction, motifs provide identity, and phrasing provides speech. Vocabulary becomes personal only when it can be heard first, transformed and placed deliberately.","الارتجال بينظم اللحن والإيقاع والهارموني والفورمة واللون في اللحظة. نغمات الكورد تدي هيكل، الأهداف تدي اتجاه، الموتيف يدي هوية، والجملة تدي كلام. المفردات تبقى بتاعتك لما تسمعها الأول وتحوّلها وتحطها بقصد."),concepts:[
  {name:t("Targets, chord tones and available tensions","الأهداف ونغمات الكورد والتوتّرات المتاحة"),formula:"DESTINATION FIRST · PATH SECOND",explain:t("Choose an arrival note, beat and duration before decoration. Tensions are judged by local chord, style and resolution—not by a universal avoid-note list.","اختار نغمة الوصول والنبضة والمدة قبل الزينة. التوتّرات تتحكم حسب الكورد المحلي والستايل والقفلة—مش قائمة نغمات ممنوعة عامة." )},
  {name:t("Motif and transformation","الموتيف والتحويل"),formula:"REPEAT · SEQUENCE · INVERT · RETROGRADE · DISPLACE · ALTER END",explain:t("Preserve enough rhythm or contour for recognition while changing one parameter. Development creates memory and direction with fewer notes.","حافظ على إيقاع أو مسار كفاية للتعرّف مع تغيير عامل واحد. التطوير يعمل ذاكرة واتجاه بنغمات أقل." )},
  {name:t("Phrase, breath and conversation","الجملة والنَفَس والحوار"),formula:"CALL · SPACE · ANSWER · EXTEND · CLOSE",explain:t("Phrase length and silence shape meaning. An answer can imitate, contrast, complete or interrupt the call; continuous sound removes punctuation.","طول الجملة والسكتة بيشكّلوا المعنى. الجواب ممكن يقلد أو يعاكس أو يكمل أو يقاطع النداء؛ الصوت المستمر بيمسح علامات الوقف." )},
  {name:t("Arc, density, register and climax","القوس والكثافة والمنطقة والقمة"),formula:"ESTABLISH → DEVELOP → DESTABILIZE → PEAK → RETURN",explain:t("Long-form improvisation distributes tension across time. A unique climax requires earlier restraint and a final return in harmony, rhythm, register and density.","الارتجال الطويل بيوزع التوتّر عبر الوقت. القمة الوحيدة محتاجة تحفّظ قبلها ورجوع أخير في الهارموني والإيقاع والمنطقة والكثافة." )},
 ],bass:t("Sing the next target, limit the pitch set, repeat one rhythmic identity and leave intentional space. Increase vocabulary only when time, form and destination stay audible.","غنّي الهدف اللي جاي، قلّل عدد النغمات، كرّر هوية إيقاعية واحدة، وسيب سكتة مقصودة. زوّد المفردات بس لما الوقت والفورمة والهدف يفضلوا مسموعين."),trap:t("Confusing spontaneity with randomness or skill with density. A scale run can be correct and still say nothing; one developed note can define the entire solo.","تلخبط العفوية بالعشوائية أو المهارة بالزحمة. جري السلم ممكن يبقى صح وما يقولش حاجة؛ نغمة واحدة متطورة ممكن تعرّف السولو كله."),proof:t("Improvise three minutes using one motif, a five-pitch limit, at least 25% silence and one climax; afterward sing the motif and explain every structural arrival.","ارتجل ٣ دقايق بموتيف واحد وحد خمس نغمات وعلى الأقل ٢٥٪ سكتة وقمة واحدة؛ وبعدها غنّي الموتيف واشرح كل وصول أساسي.")},

 {id:"outside",n:"15",level:t("ADVANCED","متقدم"),title:t("Chromaticism, outside playing & controlled resolution","الكروماتيك والعزف برّه والقفلة المتحكم فيها"),aim:t("Create friction that the listener can follow—and resolve it on command.","تعمل احتكاك المستمع يقدر يتابعه وتقفله وقت ما تحب."),core:t("Outside sound is a relationship to an established inside reference. Chromatic approaches decorate targets; enclosures surround them; side-slipping displaces a recognizable idea; superimposition temporarily creates another structure. Duration, accent, register and landing beat determine perceived distance as much as pitch.","الصوت البرّه علاقة بمرجع جوّه متثبت. الاقتراب الكروماتيك يزيّن الهدف؛ الإحاطة تحاوطه؛ السايد سليب ينقل فكرة معروفة؛ والسوبرإمبوزيشن يعمل هيكل تاني مؤقت. المدة والنبرة والمنطقة ونبضة النزول بيحددوا البعد المحسوس قد النغمة."),concepts:[
  {name:t("Passing, neighbour and approach tones","نغمات المرور والجيران والاقتراب"),formula:"STRUCTURE → PATH → STRUCTURE",explain:t("A passing tone connects two destinations; a neighbour leaves and returns; an approach points into one target. Metric placement tells the ear which note is structural.","نغمة المرور بتوصل هدفين؛ الجار يطلع ويرجع؛ والاقتراب يشاور على هدف واحد. المكان المتري بيقول للودن مين النغمة الأساسية." )},
  {name:t("Enclosures and chromatic cells","الإحاطات والخلايا الكروماتيك"),formula:"ABOVE–BELOW–TARGET · BELOW–ABOVE–TARGET",explain:t("Surround a pre-heard chord tone and land it with structural weight. Vary order, width and rhythm without losing the destination.","حاوط نغمة كورد مسموعة جواك وانزل عليها بوزن أساسي. غيّر الترتيب والعرض والإيقاع من غير ضياع الهدف." )},
  {name:t("Side-slip and superimposition","السايد سليب والسوبرإمبوزيشن"),formula:"MOTIF ±1 SEMITONE · TRIAD/PENTATONIC OVER CHORD",explain:t("Side-slip preserves idea identity while moving its centre. Superimposition overlays a chosen structure whose tensions must be named and resolved.","السايد سليب يحافظ على هوية الفكرة وينقل مركزها. السوبرإمبوزيشن يركب هيكل مختار، ولازم تسمّي توتّراته وتقفلها." )},
  {name:t("Altered dominant and symmetric tension","الدومينانت المتحوّل والتوتّر المتماثل"),formula:"ALT: 1 ♭9 ♯9 3 ♭5 ♭13 ♭7 · DIM / WHOLE-TONE",explain:t("Altered, diminished and whole-tone sounds are strongest when guide tones and destinations remain explicit. Maximum tension without directed motion becomes static noise.","ألوان الألترد والديمينشد والـwhole-tone أقوى لما guide tones والأهداف واضحين. أقصى توتّر من غير حركة موجهة يتحول لدوشة ثابتة." )},
 ],bass:t("State home first, name the outside device, duration and landing note, keep the original groove and reproduce the same departure–return effect three times before making it longer.","ثبّت البيت الأول، سمّي أداة الخروج ومدتها ونغمة النزول، حافظ على الجروف الأصلي، وكرّر نفس تأثير الخروج–الرجوع ٣ مرات قبل ما تطوّله."),trap:t("Selecting exotic notes first and searching for a rescue afterward. The destination, beat and amount of friction must exist before departure.","تختار نغمات غريبة الأول وتدور على إنقاذ بعدها. الهدف والنبضة وكمية الاحتكاك لازم يبقوا موجودين قبل الخروج."),proof:t("Record 12 named departures using four devices; every return lands on its planned beat and chord tone, time never changes and each effect is reproducible three times.","سجّل ١٢ خروجة متسماة بأربع أدوات؛ كل رجوع ينزل على النبضة ونغمة الكورد المخططين، الوقت ما يتغيرش، وكل تأثير يتكرر ٣ مرات.")},

 {id:"advanced-harmony",n:"16",level:t("ADVANCED → EXPERT","متقدم ← خبير"),title:t("Substitution, reharmonization & modern harmony","البدائل وإعادة الهارمنة والهارموني الحديث"),aim:t("Change harmony while preserving—or deliberately changing—the song’s logic.","تغيّر الهارموني مع الحفاظ على منطق الأغنية أو تغييره بقصد."),core:t("Reharmonization changes the chords beneath a melody or form. Substitutions work through shared function, guide tones, bass motion or symmetry. Advanced color includes tritone and backdoor dominants, diminished connectors, modal interchange, constant structures, upper-structure triads, intervallic harmony and polytonal layers.","إعادة الهارمنة بتغيّر الكوردات تحت لحن أو فورمة. البدائل تشتغل بوظيفة مشتركة أو guide tones أو حركة باص أو تماثل. الألوان المتقدمة فيها tritone وbackdoor dominants ووصلات diminished واستعارة مودال وأشكال ثابتة وupper structures وهارموني مسافات وطبقات بمفتاحين."),concepts:[
  {name:t("Functional substitutions","البدائل الوظيفية"),formula:"iii/vi FOR I · ii/IV FOR PD · vii°/V FOR D",explain:t("Chords can substitute when they share function and important tones. The melody and bass determine whether the replacement feels smooth, surprising or incorrect.","الكوردات تبدّل بعض لما تشارك الوظيفة ونغمات مهمة. اللحن والباص بيحددوا البديل ناعم ولا مفاجئ ولا غلط." )},
  {name:t("Tritone, backdoor and diminished routes","طرق الترايتون والباكدور والديمينشد"),formula:"♭II7→I · ♭VII7→I · vii° CONNECTORS",explain:t("Tritone dominants share the 3rd/7th pair with V7; backdoor motion approaches tonic through borrowed color; diminished chords connect targets by semitone and symmetry.","دومينانت الترايتون بيشارك زوج التالتة/السابعة مع V7؛ الباكدور يقرب للقرار بلون مستعار؛ والديمينشد يوصل الأهداف بنص تون وتماثل." )},
  {name:t("Modal interchange and constant structures","الاستعارة المقامية والأشكال الثابتة"),formula:"BORROW FROM PARALLEL · MOVE SAME QUALITY",explain:t("Borrowed chords retain one tonic while changing modal color. Constant structures move the same chord type through non-diatonic roots and rely on contour, common tones or bass logic.","الكوردات المستعارة تحافظ على قرار واحد وتغيّر اللون المقامي. الأشكال الثابتة بتحرك نفس نوع الكورد على قرارات برّه المفتاح وتعتمد على المسار أو النغمات المشتركة أو منطق الباص." )},
  {name:t("Upper structures, intervallic and polytonal color","الهياكل العليا ولون المسافات وتعدد المفاتيح"),formula:"TRIAD OVER CHORD · FIXED INTERVAL SET · TWO CENTRES",explain:t("Upper structures organize extensions; intervallic cells avoid scalar gravity; polytonality layers identifiable centres. These devices need clear register and reference to remain readable.","الهياكل العليا بتنظم الإضافات؛ خلايا المسافات بتبعد عن جاذبية السلم؛ وتعدد المفاتيح بيركب مركزين معروفين. الأدوات دي محتاجة منطقة ومرجع واضحين عشان تتقري." )},
 ],bass:t("Protect melody, form and destination first. Test the original roots, then guide tones, then the proposed bass motion; a reharmonization is valid when its new tension and release are audible, not merely nameable.","احمي اللحن والفورمة والهدف الأول. اختبر القرارات الأصلية، وبعدها guide tones، وبعدها حركة الباص المقترحة؛ إعادة الهارمنة تنفع لما توتّرها وقفلتها الجديدة يتسمعوا مش بس يتسمّوا."),trap:t("Using advanced chord names as proof of musical value. If the melody clashes unintentionally, bass motion loses direction or form becomes unclear, the theory has not served the song.","تستخدم أسماء كوردات متقدمة كدليل قيمة موسيقية. لو اللحن خبط بالغلط أو حركة الباص ضاعت أو الفورمة مبقتش واضحة، النظرية ما خدمتش الأغنية."),proof:t("Reharmonize one eight-bar melody three ways—functional, modal and chromatic—then explain every retained melody tone, bass destination and tension–release decision.","أعد هارمنة لحن ٨ موازير بتلات طرق—وظيفية ومقامية وكروماتيك—وبعدها اشرح كل نغمة لحن محفوظة وهدف باص وقرار توتّر–قفلة.")},

 {id:"ear",n:"17",level:t("ALL LEVELS · NEVER FINISHED","كل المستويات · ما بيخلصش"),title:t("Ear training, transcription, acoustics & global systems","تدريب الودن والتفريغ والصوتيات والأنظمة العالمية"),aim:t("Hear theory before naming it and respect systems that Western notation cannot fully describe.","تسمع النظرية قبل ما تسميها وتحترم أنظمة النوتة الغربية ما تقدرش توصفها بالكامل."),core:t("Ear training connects sound to label, notation and instrument: audiation, intervals, scale degrees, bass lines, chords, function, rhythm and form. Acoustics explains overtone, timbre, phase, register and intonation. Twelve-tone equal temperament is one tuning system; maqam, raga, tala, clave and African timeline traditions organize pitch and time through culture-specific behavior that cannot be reduced to a generic scale.","تدريب الودن بيوصل الصوت بالاسم والنوتة والآلة: السمع الداخلي والمسافات والدرجات وخطوط الباص والكوردات والوظيفة والإيقاع والفورمة. الصوتيات بتشرح الهارمونيكس والتيمبر والفاز والمنطقة والضبط. الضبط المتساوي ١٢ نغمة نظام واحد؛ المقام والراجا والتالا والكلافيه والخطوط الزمنية الأفريقية بينظموا النغم والوقت بسلوك ثقافي مخصوص ما ينفعش يتختصر في سلم عام."),concepts:[
  {name:t("Audiation and functional hearing","السمع الداخلي وسماع الوظيفة"),formula:"IMAGINE → SING → FIND → VERIFY",explain:t("Audiation predicts sound without the instrument. Functional hearing identifies degree relative to a centre, which transfers better than memorizing isolated interval songs.","السمع الداخلي بيتوقع الصوت من غير الآلة. سماع الوظيفة بيحدد الدرجة بالنسبة لمركز، وده بيتنقل أحسن من حفظ أغاني مسافات منفصلة." )},
  {name:t("Transcription and analysis workflow","خطوات التفريغ والتحليل"),formula:"FORM → RHYTHM → ROOTS → PITCH → ARTICULATION → THEORY",explain:t("Slow only when necessary. Loop short phrases, sing before locating, verify at full tempo and write enough detail to reproduce feel—not only fret numbers.","بطّأ وقت الضرورة بس. لف جمل قصيرة، غنّي قبل ما تدور، راجع على السرعة الأصلية، واكتب تفاصيل كفاية ترجع الإحساس مش أرقام فريتات بس." )},
  {name:t("Overtones, timbre, phase and intonation","الهارمونيكس والتيمبر والفاز وضبط النغمة"),formula:"FUNDAMENTAL + PARTIALS · FREQUENCY RATIO",explain:t("Tone changes which partials dominate; low frequencies need space and stable phase relationships. Intonation depends on context, attack, sustain, ensemble and tuning system—not a tuner light alone.","الصوت بيتغيّر حسب الهارمونيكس المسيطرة؛ الترددات الواطية محتاجة مساحة وعلاقة فاز ثابتة. الضبط يعتمد على السياق والضربة والاستمرار والفرقة ونظام التونينج—مش لمبة تيونر لوحدها." )},
  {name:t("Temperament and culture-specific pitch/time","أنظمة الضبط والنغم/الوقت حسب الثقافة"),formula:"12-TET ≠ UNIVERSAL · AJNAS/SAYR · RAGA · TALA · CLAVE/TIMELINE",explain:t("Notation is an approximation of living practice. Learn intonation, ornament, cadence, timeline and phrase grammar by listening, copying repertoire and studying qualified tradition-bearers.","النوتة تقريب لممارسة عايشة. اتعلم الضبط والزخرفة والقفلة والخط الزمني وقواعد الجملة بالسماع ونسخ الريبرتوار والدراسة مع ناس مؤهلة من التقليد نفسه." )},
 ],bass:t("Transcribe complete bass behavior: pitch, rhythm, duration, articulation, dynamics, form, drum relationship and tone. Sing every target and compare your recorded take to the source at full tempo.","فرّغ سلوك الباص كامل: النغمة والإيقاع والمدة والنطق والديناميكس والفورمة وعلاقة الدرامز والصوت. غنّي كل هدف وقارن تسجيلك بالمصدر على السرعة الأصلية."),trap:t("Naming sounds without reproducing them, or treating a tuner and Western scale formula as universal truth. Recognition must become voice, fretboard and musical behavior.","تسمي الأصوات من غير ما تكررها، أو تعامل التيونر وتركيبة السلم الغربي كحقيقة عامة. التعرف لازم يتحول لصوت وفريت بورد وسلوك موسيقي."),proof:t("Transcribe one complete verse and chorus by ear, perform it with matching feel, explain its harmony and form, then sing and play every structural target without the recording.","فرّغ فيرس وكورس كاملين بالودن، اعزفهم بنفس الإحساس، اشرح الهارموني والفورمة، وبعدها غنّي واعزف كل هدف أساسي من غير التسجيل.")},

 {id:"arranging",n:"18",level:t("PROFESSIONAL INTEGRATION","دمج احترافي"),title:t("Composition, arranging & professional application","التأليف والتوزيع والتطبيق الاحترافي"),aim:t("Use theory to make the whole piece clearer—not just the bass part busier.","تستخدم النظرية عشان القطعة كلها تبقى أوضح مش خط الباص أزحم."),core:t("Composition shapes motive, melody, harmony, rhythm, form, texture and tension. Arranging assigns those roles across instruments and registers. The bass may support, counter, pedal, double, reharmonize or lead; the correct choice depends on melody, kick, low-frequency space, section energy and production intent.","التأليف بيشكّل الموتيف واللحن والهارموني والإيقاع والفورمة والنسيج والتوتّر. التوزيع بيوزع الأدوار دي على الآلات والمناطق. الباص ممكن يسند أو يعمل خط مقابل أو بيدال أو يضاعف أو يعيد الهارمنة أو يقود؛ الاختيار الصح يعتمد على اللحن والكيك ومساحة اللو إند وطاقة السكشن وقصد الإنتاج."),concepts:[
  {name:t("Melody, counterpoint and bass relationship","علاقة اللحن والكونتربوينت والباص"),formula:"SUPPORT · DOUBLE · CONTRARY · CALL/ANSWER · PEDAL",explain:t("Independent lines need rhythmic and registral separation plus controlled consonance/dissonance. The bass can answer melody without stealing its arrival points.","الخطوط المستقلة محتاجة فصل إيقاعي ومنطقي وتحكم في التوافق والاحتكاك. الباص يقدر يجاوب اللحن من غير ما يسرق نقاط وصوله." )},
  {name:t("Register, texture, doubling and low-end space","المنطقة والنسيج والمضاعفة ومساحة اللو إند"),formula:"ONE CLEAR LOWEST FUNCTION",explain:t("Closely spaced low notes create masking and roughness. Decide who owns sub, bass motion and low chord extensions; move other information upward or thin it.","النغمات الواطية القريبة بتعمل تغطية وخشونة. حدد مين ماسك الساب وحركة الباص والإضافات الواطية؛ ارفع باقي المعلومات أو خففها." )},
  {name:t("Development, contrast and large-scale tension","التطوير والتباين والتوتّر الكبير"),formula:"REPEAT · VARY · CONTRAST · RECAPITULATE",explain:t("Sections need related identity and different function. Arrange density, register, harmony and rhythm so the climax is prepared and the return has meaning.","السكاشن محتاجة هوية مرتبطة ووظيفة مختلفة. وزع الكثافة والمنطقة والهارموني والإيقاع عشان القمة تتحضر والرجوع يبقى له معنى." )},
  {name:t("Charts, transposition, rehearsal and production decisions","الشارت والنقل والبروفة وقرارات الإنتاج"),formula:"KEY · TEMPO · METER · FORM · HITS · DYNAMICS · PATCH",explain:t("Professional theory becomes clear communication: readable charts, number systems, cue language, range awareness and versions. Record decisions so live, rehearsal and studio arrangements remain consistent.","النظرية الاحترافية تتحول لتواصل واضح: شارت مقروء ونظام أرقام ولغة إشارات ووعي بالمدى والنسخ. سجّل القرارات عشان توزيع اللايف والبروفة والاستوديو يفضل ثابت." )},
 ],bass:t("Before writing, define the song’s emotional arc and each section’s bass job. Draft roots and rhythm, test against melody and kick, then add counterpoint, fills, reharmonization or effects only where the arrangement has space.","قبل الكتابة، حدد القوس العاطفي ومهمة الباص في كل سكشن. اكتب القرارات والإيقاع، اختبرهم قدام اللحن والكيك، وبعدها ضيف كونتربوينت أو فيلات أو إعادة هارمنة أو إفكتات بس في مكان فاضي في التوزيع."),trap:t("Optimizing the bass part in isolation. A brilliant line that masks melody, fights the kick, removes contrast or confuses form is a weak arrangement choice.","تحسّن خط الباص لوحده. خط عبقري يغطي اللحن أو يحارب الكيك أو يمسح التباين أو يلخبط الفورمة هو اختيار توزيع ضعيف."),proof:t("Arrange one complete song from lead sheet to performance chart, justify every bass role and register, and produce two versions whose different line choices preserve the same song identity.","وزّع أغنية كاملة من ليد شيت لشارت أداء، برر كل دور ومنطقة للباص، واعمل نسختين اختيارات الخط فيهم مختلفة مع الحفاظ على هوية نفس الأغنية.")},
];

export const THEORY_DICTIONARIES:TheoryDictionary[]=[
 {id:"intervals",title:t("Interval dictionary","قاموس المسافات"),intro:t("Distance, sound and the fastest bass use. Compound intervals repeat the quality above the octave.","المسافة والصوت وأسرع استخدام على الباص. المسافات المركبة بتكرر النوع فوق الأوكتاف."),columns:[t("INTERVAL","المسافة"),t("FORMULA","التركيبة"),t("BASS MEANING","معناها للباص")],rows:[
  {name:t("Perfect unison","اليونيسون التام"),formula:"0 SEMITONES · 1",semitones:0,meaning:t("Home, doubling and exact pitch identity.","القرار والمضاعفة ونفس هوية النغمة.")},
  {name:t("Minor 2nd","تانية صغيرة"),formula:"1 SEMITONE · ♭2",semitones:1,meaning:t("Maximum local rub; leading motion or Phrygian color.","أقوى احتكاك محلي؛ حركة قائدة أو لون فريجيان.")},
  {name:t("Major 2nd","تانية كبيرة"),formula:"2 SEMITONES · 2",semitones:2,meaning:t("Stepwise connection, suspension or open modal color.","وصلة خطوة أو تعليق أو لون مقامي مفتوح.")},
  {name:t("Minor 3rd","تالتة صغيرة"),formula:"3 SEMITONES · ♭3",semitones:3,meaning:t("Minor quality, blues color and compact melodic leap.","نوع ماينور ولون بلوز ونطّة لحنية صغيرة.")},
  {name:t("Major 3rd","تالتة كبيرة"),formula:"4 SEMITONES · 3",semitones:4,meaning:t("Major quality and essential guide tone.","نوع ميجور وguide tone أساسية.")},
  {name:t("Perfect 4th","رابعة تامة"),formula:"5 SEMITONES · 4",semitones:5,meaning:t("Strong suspension, quartal sound and standard string tuning.","تعليق قوي وصوت رباعي وتونينج الأوتار العادي.")},
  {name:t("Tritone","ترايتون"),formula:"6 SEMITONES · ♯4/♭5",semitones:6,meaning:t("Dominant pressure, altered color and symmetrical division.","ضغط دومينانت ولون متحوّل وتقسيم متماثل.")},
  {name:t("Perfect 5th","خامسة تامة"),formula:"7 SEMITONES · 5",semitones:7,meaning:t("Stable support, power-chord clarity and strong root reinforcement.","دعم ثابت ووضوح power chord وتقوية القرار.")},
  {name:t("Minor 6th","سادسة صغيرة"),formula:"8 SEMITONES · ♭6",semitones:8,meaning:t("Dark minor color; inversion of major 3rd.","لون ماينور غامق؛ قلب التالتة الكبيرة.")},
  {name:t("Major 6th","سادسة كبيرة"),formula:"9 SEMITONES · 6",semitones:9,meaning:t("Dorian lift, major color and inversion of minor 3rd.","رفعة دورياني ولون ميجور وقلب التالتة الصغيرة.")},
  {name:t("Minor 7th","سابعة صغيرة"),formula:"10 SEMITONES · ♭7",semitones:10,meaning:t("Dominant/minor-7 family, funk and Mixolydian color.","عيلة دومينانت/ماينور٧ وفانك ولون ميكسوليديان.")},
  {name:t("Major 7th","سابعة كبيرة"),formula:"11 SEMITONES · 7",semitones:11,meaning:t("Strong leading pull and major-7 color.","جذب قوي للقرار ولون ميجور٧.")},
  {name:t("Octave","أوكتاف"),formula:"12 SEMITONES · 8",semitones:0,meaning:t("Same pitch class, new register and classic bass-line reinforcement.","نفس فصيلة النغمة ومنطقة جديدة وتقوية كلاسيكية لخط الباص.")},
 ]},
 {id:"chords",title:t("Chord-formula dictionary","قاموس تركيبات الكوردات"),intro:t("Spell from the chord root. Extensions are compound scale degrees; slash notes specify the bass.","اكتب من قرار الكورد. الإضافات درجات مركبة؛ والنغمة بعد السلاش بتحدد الباص."),columns:[t("CHORD","الكورد"),t("FORMULA","التركيبة"),t("FUNCTION / COLOR","الوظيفة / اللون")],rows:[
  {name:t("Major triad","تراياد ميجور"),formula:"1 3 5",meaning:t("Stable major quality.","نوع ميجور ثابت.")},{name:t("Minor triad","تراياد ماينور"),formula:"1 ♭3 5",meaning:t("Stable minor quality.","نوع ماينور ثابت.")},{name:t("Diminished triad","تراياد ديمينشد"),formula:"1 ♭3 ♭5",meaning:t("Unstable symmetrical tendency.","اتجاه متماثل غير ثابت.")},{name:t("Augmented triad","تراياد أوجمنتد"),formula:"1 3 ♯5",meaning:t("Open symmetrical expansion.","توسّع متماثل مفتوح.")},
  {name:t("Sus2 / Sus4","ساس٢ / ساس٤"),formula:"1 2 5 / 1 4 5",meaning:t("Third removed; quality suspended.","التالتة متشالة والنوع معلق.")},{name:t("Major 6","ميجور ٦"),formula:"1 3 5 6",meaning:t("Warm tonic major color.","لون تونك ميجور دافي.")},{name:t("Minor 6","ماينور ٦"),formula:"1 ♭3 5 6",meaning:t("Minor with bright internal tension.","ماينور بتوتّر داخلي منور.")},{name:t("Major 7","ميجور ٧"),formula:"1 3 5 7",meaning:t("Tonic major with leading-tone color.","تونك ميجور بلون النغمة القائدة.")},
  {name:t("Dominant 7","دومينانت ٧"),formula:"1 3 5 ♭7",meaning:t("Dominant, blues or Mixolydian family.","عيلة دومينانت أو بلوز أو ميكسوليديان.")},{name:t("Minor 7","ماينور ٧"),formula:"1 ♭3 5 ♭7",meaning:t("Minor, Dorian or Aeolian family.","عيلة ماينور أو دوريان أو أيوليان.")},{name:t("Minor-major 7","ماينور ميجور ٧"),formula:"1 ♭3 5 7",meaning:t("Tense tonic minor and melodic-minor color.","تونك ماينور مشدود ولون ميلوديك ماينور.")},{name:t("Half-diminished 7","نص ديمينشد ٧"),formula:"1 ♭3 ♭5 ♭7",meaning:t("Minor-key predominant and Locrian family.","بري دومينانت في الماينور وعيلة لوكريان.")},
  {name:t("Diminished 7","ديمينشد ٧"),formula:"1 ♭3 ♭5 𝄫7",meaning:t("Symmetrical connector and leading-tone function.","وصلة متماثلة ووظيفة نغمة قائدة.")},{name:t("Major 9","ميجور ٩"),formula:"1 3 5 7 9",meaning:t("Expanded tonic major.","تونك ميجور موسّع.")},{name:t("Dominant 9","دومينانت ٩"),formula:"1 3 5 ♭7 9",meaning:t("Dominant with smoother upper color.","دومينانت بلون عالي أنعم.")},{name:t("Minor 9","ماينور ٩"),formula:"1 ♭3 5 ♭7 9",meaning:t("Expanded minor/Dorian color.","لون ماينور/دوريان موسّع.")},
  {name:t("11 / Sus dominant","١١ / دومينانت ساس"),formula:"1 5 ♭7 9 11",meaning:t("Open dominant; third often omitted.","دومينانت مفتوح؛ التالتة غالباً متشالة.")},{name:t("13","١٣"),formula:"1 3 5 ♭7 9 13",meaning:t("Dominant with major-sixth color; 11 often omitted.","دومينانت بلون سادسة كبيرة؛ الـ١١ غالباً متشالة.")},{name:t("Altered dominant","دومينانت متحوّل"),formula:"1 3 ♭7 + ♭9/♯9/♭5/♯5",meaning:t("Directed maximum tension into a target.","أقصى توتّر موجه لهدف.")},{name:t("Slash chord","سلاش كورد"),formula:"CHORD / REQUIRED BASS",meaning:t("Inversion, pedal or independent bass harmony.","قلب أو بيدال أو هارموني باص مستقل.")},
 ]},
 {id:"scales",title:t("Scale and collection dictionary","قاموس السلالم والمجموعات"),intro:t("Formula is measured from one tonic. Hear the identity before memorizing a fingering.","التركيبة محسوبة من قرار واحد. اسمع الهوية قبل حفظ الصوابع."),columns:[t("COLLECTION","المجموعة"),t("FORMULA","التركيبة"),t("PRIMARY SOUND / USE","الصوت / الاستخدام الأساسي")],rows:[
  {name:t("Major / Ionian","ميجور / أيونيان"),formula:"1 2 3 4 5 6 7",meaning:t("Major key reference and tonic harmony.","مرجع المفتاح الميجور وهارموني التونك.")},{name:t("Natural minor / Aeolian","ماينور طبيعي / أيوليان"),formula:"1 2 ♭3 4 5 ♭6 ♭7",meaning:t("Natural minor key collection.","مجموعة المفتاح الماينور الطبيعي.")},{name:t("Harmonic minor","هارمونيك ماينور"),formula:"1 2 ♭3 4 5 ♭6 7",meaning:t("Minor with strong dominant–tonic pull.","ماينور بجذب دومينانت–تونك قوي.")},{name:t("Melodic minor","ميلوديك ماينور"),formula:"1 2 ♭3 4 5 6 7",meaning:t("Modern minor color and altered-mode parent.","لون ماينور حديث وأم مودات متحوّلة.")},
  {name:t("Major pentatonic","بنتاتونيك ميجور"),formula:"1 2 3 5 6",meaning:t("Open major groove and melody language.","لغة جروف ولحن ميجور مفتوحة.")},{name:t("Minor pentatonic","بنتاتونيك ماينور"),formula:"1 ♭3 4 5 ♭7",meaning:t("Portable minor, rock, funk and blues vocabulary.","مفردات ماينور وروك وفانك وبلوز قابلة للنقل.")},{name:t("Blues","بلوز"),formula:"1 ♭3 4 ♭5 5 ♭7",meaning:t("Minor pentatonic with expressive blue motion.","بنتاتونيك ماينور بحركة blue تعبيرية.")},{name:t("Dorian","دوريان"),formula:"1 2 ♭3 4 5 6 ♭7",meaning:t("Minor with natural-six lift.","ماينور برفعة السادسة الطبيعية.")},
  {name:t("Phrygian","فريجيان"),formula:"1 ♭2 ♭3 4 5 ♭6 ♭7",meaning:t("Minor with exposed flat-two root rub.","ماينور باحتكاك ♭٢ واضح مع القرار.")},{name:t("Lydian","ليديان"),formula:"1 2 3 ♯4 5 6 7",meaning:t("Major with raised-four openness.","ميجور بانفتاح الرابعة المرفوعة.")},{name:t("Mixolydian","ميكسوليديان"),formula:"1 2 3 4 5 6 ♭7",meaning:t("Major dominant, rock and funk color.","لون ميجور دومينانت وروك وفانك.")},{name:t("Locrian","لوكريان"),formula:"1 ♭2 ♭3 4 ♭5 ♭6 ♭7",meaning:t("Half-diminished environment with unstable tonic fifth.","بيئة نص ديمينشد بخامسة قرار غير ثابتة.")},
  {name:t("Chromatic","كروماتيك"),formula:"ALL 12 SEMITONES",meaning:t("Complete pitch field; requires contextual hierarchy.","كل النغمات؛ محتاج ترتيب وزن من السياق.")},{name:t("Whole tone","Whole tone"),formula:"1 2 3 ♯4 ♯5 ♭7",meaning:t("Symmetrical augmented-dominant color.","لون أوجمنتد/دومينانت متماثل.")},{name:t("Half-whole diminished","ديمينشد نص–تون"),formula:"H–W REPEATING",meaning:t("Dominant ♭9/♯9/♯11/13 tension.","توتّر دومينانت ♭9/♯9/♯11/13.")},{name:t("Whole-half diminished","ديمينشد تون–نص"),formula:"W–H REPEATING",meaning:t("Fully diminished chord environment.","بيئة كورد ديمينشد كامل.")},
 ]},
 {id:"function",title:t("Harmonic-function dictionary","قاموس الوظيفة الهارمونية"),intro:t("The bassist makes function audible through root, inversion, duration and destination.","الباص بيخلي الوظيفة مسموعة بالقرار والقلب والمدة والهدف."),columns:[t("FUNCTION / MOVE","الوظيفة / الحركة"),t("TYPICAL SYMBOL","الرمز المعتاد"),t("WHAT THE EAR EXPECTS","الودن متوقعة إيه")],rows:[
  {name:t("Tonic","تونك"),formula:"I / i · vi / iii substitutes",meaning:t("Rest, identity and return.","راحة وهوية ورجوع.")},{name:t("Predominant","بري دومينانت"),formula:"ii / IV · iiø / iv",meaning:t("Departure and preparation for dominant.","خروج وتحضير للدومينانت.")},{name:t("Dominant","دومينانت"),formula:"V7 / vii°",meaning:t("Directed instability and demand for tonic.","عدم ثبات موجه وطلب التونك.")},{name:t("Authentic cadence","قفلة أصيلة"),formula:"V–I / V–i",meaning:t("Strong tonal closure, strongest with bass 5→1.","قفلة قوية، أقواها مع باص ٥←١.")},
  {name:t("Plagal cadence","قفلة بلاجال"),formula:"IV–I / iv–i",meaning:t("Subdominant-colored closure.","قفلة بلون subdominant.")},{name:t("Deceptive cadence","قفلة خادعة"),formula:"V–vi / V–♭VI",meaning:t("Expected tonic denied but voice leading continues.","التونك المتوقع ما يجيش لكن حركة الأصوات تكمل.")},{name:t("Secondary dominant","دومينانت ثانوي"),formula:"V/x → x",meaning:t("Temporary emphasis of a non-tonic target.","تركيز مؤقت على هدف مش التونك.")},{name:t("Tritone substitution","بديل ترايتون"),formula:"♭II7 → I",meaning:t("Chromatic bass resolution with shared guide-tone tritone.","قفلة باص كروماتيك مع ترايتون guide tones مشترك.")},
  {name:t("Backdoor dominant","باكدور دومينانت"),formula:"♭VII7 → I",meaning:t("Borrowed/plagal-flavored dominant arrival.","وصول دومينانت بلون مستعار/بلاجال.")},{name:t("Modal mixture","استعارة مقامية"),formula:"BORROW FROM PARALLEL",meaning:t("Same tonic, altered modal color.","نفس القرار بلون مقامي متغير.")},{name:t("Pedal point","بيدال"),formula:"FIXED BASS UNDER CHANGES",meaning:t("One centre or tension reference beneath moving harmony.","مرجع قرار أو توتّر واحد تحت هارموني متحرك.")},{name:t("Modulation","تحويل مفتاح"),formula:"NEW FUNCTION + CADENCE",meaning:t("A new tonic takes structural control.","تونك جديد يمسك التحكم الأساسي.")},
 ]},
 {id:"rhythm",title:t("Rhythm, meter and form dictionary","قاموس الإيقاع والميزان والفورمة"),intro:t("Terms that tell the bassist how time is grouped, displaced and navigated.","مصطلحات بتقول للباص الوقت متجمع ومتحرك وماشي إزاي."),columns:[t("TERM","المصطلح"),t("SHORTHAND","الاختصار"),t("PRACTICAL MEANING","المعنى العملي")],rows:[
  {name:t("Pulse","النبض"),formula:"REFERENCE BEAT",meaning:t("Recurring time point the body predicts.","نقطة وقت متكررة الجسم بيتوقعها.")},{name:t("Subdivision","التقسيم"),formula:"BEAT → EQUAL PARTS",meaning:t("Internal grid for attacks and rests.","الشبكة الداخلية للضربات والسكتات.")},{name:t("Simple meter","ميزان بسيط"),formula:"BEAT DIVIDES BY 2",meaning:t("2/4, 3/4 and 4/4 families.","عائلات ٢/٤ و٣/٤ و٤/٤.")},{name:t("Compound meter","ميزان مركب"),formula:"BEAT DIVIDES BY 3",meaning:t("6/8, 9/8 and 12/8 families.","عائلات ٦/٨ و٩/٨ و١٢/٨.")},
  {name:t("Syncopation","سنكوب"),formula:"WEIGHT OFF EXPECTED BEAT",meaning:t("Offbeat attack, anticipation or tie across weight.","ضربة أوف بيت أو تقديم أو رباط عبر الوزن.")},{name:t("Tuplet","توبلت"),formula:"n NOTES IN ANOTHER VALUE",meaning:t("Alternative equal division of a span.","تقسيم متساوي بديل لنفس المدة.")},{name:t("Polyrhythm","بوليرذم"),formula:"DIFFERENT DIVISIONS, SAME SPAN",meaning:t("Two rhythmic grids sounding together.","شبكتين إيقاعيين بيتسمعوا مع بعض.")},{name:t("Polymeter","بوليميتر"),formula:"DIFFERENT BAR CYCLES",meaning:t("Same tempo, independently repeating meters.","نفس التيمبو وموازين بتكرر لوحدها.")},
  {name:t("Metric modulation","مودوليشن متري"),formula:"OLD SUBDIVISION = NEW BEAT",meaning:t("Related but newly defined tempo.","تيمبو جديد مرتبط حسابياً بالقديم.")},{name:t("Harmonic rhythm","إيقاع هارموني"),formula:"RATE OF CHORD CHANGE",meaning:t("How quickly harmony moves, independent of BPM.","سرعة حركة الهارموني بعيد عن BPM.")},{name:t("Pickup / anticipation","بيك أب / تقديم"),formula:"BEFORE BAR OR CHANGE",meaning:t("Phrase or harmony begins early.","الجملة أو الهارموني يبدأ بدري.")},{name:t("Tag / vamp / coda","تاج / فامب / كودا"),formula:"REPEAT / HOLD / FINAL ROUTE",meaning:t("Extend, wait or navigate the ending.","مدّ أو استنى أو امشِ في النهاية.")},
 ]},
];
