export type PracticeBlock={name:string;minutes:number;task:string;standard:string;tool:"body"|"naming"|"shape"|"millpad"|"row"|"passage"|"drone"|"assessment"|"log"};
export type BeastDay={day:number;phase:number;title:string;objective:string;context:string;standard:string;blocks:PracticeBlock[];passages:string[];checkpoint?:boolean};

export const TEMPO_RUNGS=[
 {rung:1,bpm:40,subdivision:"1 note / click"},{rung:2,bpm:48,subdivision:"1 note / click"},{rung:3,bpm:56,subdivision:"1 note / click"},{rung:4,bpm:63,subdivision:"1 note / click"},
 {rung:5,bpm:40,subdivision:"2 notes / click"},{rung:6,bpm:48,subdivision:"2 notes / click"},{rung:7,bpm:56,subdivision:"2 notes / click"},{rung:8,bpm:63,subdivision:"2 notes / click"},{rung:9,bpm:72,subdivision:"2 notes / click"},{rung:10,bpm:80,subdivision:"2 notes / click"}
];

export const PHASES=[
 {n:1,days:"1-5",title:"Foundation",purpose:"Note names and the three physical shapes, kept separate until both are reliable.",exit:"30 random coordinates: 27 correct under two seconds; 20/20 shape calls; MILLPAD both directions; every C from fret 0-12."},
 {n:2,days:"6-8",title:"Linking",purpose:"Bolt the MILLPAD label track onto scale degrees, shapes and locations.",exit:"Any label on any string becomes the correct C-major chunk in under three seconds, 27/30; next, previous and shift stated."},
 {n:3,days:"9-13",title:"Vertical sweeps",purpose:"Seven four-string rows, twelve notes each, with labels spoken and turnarounds deliberately excluded.",exit:"Any of the seven rows, called at random, correct at rung 4 with labels spoken and no chart."},
 {n:4,days:"14-17",title:"Turnarounds & full cycle",purpose:"Isolate both hinges, reverse direction and join the C-major traversal.",exit:"C major from open position to fret 12 and back, unbroken at rung 2 or higher, state recoverable when halted."},
 {n:5,days:"18-23",title:"Transposition",purpose:"Generate rather than memorize: G, F, D, B-flat, A and E-flat major.",exit:"Any learned key generated on paper in under 60 seconds, then four sweeps at rung 3 without tab."},
 {n:6,days:"24-26",title:"Free navigation",purpose:"Random key, in-key start, string and direction; construct the route live.",exit:"Correct start within six seconds, travel to fret 17 and back, and state key-direction-string-chunk on demand."},
 {n:7,days:"27-30",title:"Integration & assessment",purpose:"Convert physical chunks into modal sound, writing and proof.",exit:"Pass at least six of the eight final tests; eight passes means the month has done its job."}
];

export const MILLPAD=[
 {label:"M",mode:"Mixolydian",degree:5,steps:"W-W",shape:"WS-WS",offsets:[0,2,4],fingers:"1-3-4 high / moving hand low"},
 {label:"I",mode:"Ionian",degree:1,steps:"W-W",shape:"WS-WS",offsets:[0,2,4],fingers:"1-3-4 high / moving hand low"},
 {label:"Ly",mode:"Lydian",degree:4,steps:"W-W",shape:"WS-WS",offsets:[0,2,4],fingers:"1-3-4 high / moving hand low"},
 {label:"Lo",mode:"Locrian",degree:7,steps:"H-W",shape:"1-2-4",offsets:[0,1,3],fingers:"1-2-4"},
 {label:"P",mode:"Phrygian",degree:3,steps:"H-W",shape:"1-2-4",offsets:[0,1,3],fingers:"1-2-4"},
 {label:"A",mode:"Aeolian",degree:6,steps:"W-H",shape:"1-3-4",offsets:[0,2,3],fingers:"1-3-4"},
 {label:"D",mode:"Dorian",degree:2,steps:"W-H",shape:"1-3-4",offsets:[0,2,3],fingers:"1-3-4"}
];

export const THEORY_CHAPTERS=[
 {id:"connection",number:"1.1",title:"The connection",summary:"The Beast is the route; MILLPAD is its label track. They are not two exercises.",detail:["The Beast moves the hand through one parent scale in uninterrupted order. MILLPAD names the three-note group about to arrive under the hand.","If you can explain why the seven-label cycle exists, why only three shapes exist and why exactly one major-scale crossing shifts, the rest is retrieval and repetition."],proof:"Explain the route/label distinction aloud without the bass."},
 {id:"rule",number:"1.2",title:"The generating rule",summary:"Three consecutive scale notes per string, then cross. Nothing else is memorized.",detail:["Four strings create a twelve-note sweep. The turnaround takes the next higher in-key note, then reverses.","Every complete up-down cycle begins two scale degrees above the previous one. This two-note rule is the fastest recovery check when the route feels lost."],proof:"Write twelve consecutive notes, divide them into four groups and derive the tab rather than copying it."},
 {id:"hinge",number:"1.3",title:"Why the hand usually stays put",summary:"A string crossing supplies five semitones. Three diatonic steps usually also span five.",detail:["Because the bass is tuned in fourths, crossing E-A, A-D or D-G raises pitch by five semitones. Advancing three scale degrees usually forms a perfect fourth, so the new group begins in the same fret column.","Once per major-scale cycle the jump is a tritone: six semitones. The tuning supplies five, so the hand must add one fret."],proof:"Derive 6 - 5 = +1 at the tritone crossing."},
 {id:"cycle",number:"1.4",title:"Why MILLPAD has this order",summary:"Advance three scale degrees repeatedly: G-C-F-B-E-A-D-G in C major.",detail:["Label those starting degrees by their modes: Mixolydian-Ionian-Lydian-Locrian-Phrygian-Aeolian-Dorian.","Three scale steps, repeated seven times, returns after twenty-one degrees. The word is the circle of fourths created by the three-notes-per-string rule."],proof:"Start from every label and recite seven steps forward and backward."},
 {id:"shapes",number:"1.5",title:"Why there are only three shapes",summary:"A three-note major-scale group contains the half step first, last, or not at all.",detail:["No half step gives W-W: offsets 0-2-4, called WS-WS. Half step first gives H-W: 0-1-3, fingered 1-2-4. Half step last gives W-H: 0-2-3, fingered 1-3-4.","M, I and Ly are wide; Lo and P are half-first; A and D are half-last. Remember the 3-2-2 grouping, not seven unrelated facts."],proof:"Given an interval pair, produce shape, offsets, fingers and both/all compatible labels."},
 {id:"shift",number:"1.6",title:"The single shift",summary:"Ascending shifts +1 only at Ly to Lo; descending reverses -1 at Lo to Ly.",detail:["Rows beginning Lo, P, A or D do not cross the boundary on a four-string sweep and remain in one column.","A descending label names the low-to-high shape even when it is played backward. C-B-A is labelled Aeolian because A-B-C is W-H."],proof:"For each of the seven starting rows, state the four labels and exact crossing—if any—where the index moves."},
 {id:"state",number:"1.7",title:"Track state, not twelve frets",summary:"KEY - DIRECTION - STRING - CHUNK regenerates everything.",detail:["From C major - ascending - D string - Dorian you can recover the 1-3-4 shape, D as the group start, Mixolydian next and no immediate shift.","Tab is a check. State is the skill. Restarting from the beginning merely overtrains the opening and hides the actual failure point."],proof:"Let the session halt you at random; name all four state variables before continuing."},
 {id:"corrections",number:"1.8",title:"Correct the common source errors",summary:"1-2-4 means x-x+1-x+3. 1-3-4 means x-x+2-x+3. There is no 2-3-4 shape.",detail:["Finger names are not fret numbers. Derive the offsets from a one-finger-per-fret hand and the confusion disappears.","WS-WS spans five frets. Below about fret 7, shift the hand; do not force a five-fret static stretch."],proof:"Call all three shapes from random frets in low and high positions using safe fingering."},
 {id:"modes",number:"1.9",title:"Shape label is not tonal centre",summary:"A Phrygian-shaped chunk does not automatically sound Phrygian.",detail:["A physical chunk says where its intervals sit inside the parent collection. A musical mode requires a perceived home created through drone, chord, pedal, emphasis, rhythm and resolution.","Days 27-30 convert filenames for shapes into actual modal sound by emphasizing characteristic tones over a stable centre."],proof:"Play the same C-major notes over C, A and E drones and describe why the perceived home changes."},
 {id:"generate",number:"1.10",title:"Ten-step route generation",summary:"Spell key, number degrees, identify start, map label, read cycle, assign shapes, place columns, verify notes, turn, recover.",detail:["Never trust a visually plausible shape. The final test is an unbroken scale with no gap, duplicate or foreign pitch.","Fluency target is roughly five seconds from a valid coordinate to a correct first note."],proof:"Generate an E-major row from E-string fret 4 without using a chart."},
 {id:"selftest",number:"1.11",title:"Nine-question self-test",summary:"Do not begin Day 1 until the system can be explained, not merely copied.",detail:["State the generating rule; sweep size; cancellation; tritone; three-shape proof; 3-2-2 grid; a called state; descending-label logic; and the two-note cycle rule."],proof:"Nine written answers, then teach the system aloud in under three minutes."}
];

const b=(name:string,minutes:number,task:string,standard:string,tool:PracticeBlock["tool"]):PracticeBlock=>({name,minutes,task,standard,tool});
const hands=(minutes=3)=>b("Hands & tuning",minutes,"Tune, alternate index/middle, release the shoulders and run the fretting-hand safety checklist.","Relaxed wrist, no clamping, no pain.","body");
const log=(minutes=5)=>b("Repair & log",minutes,"Record tempo rung, clean repetitions, error codes, naming score, worst moment and tomorrow's repair.","Written evidence, not memory.","log");
const naming=(minutes:number,task:string,standard:string)=>b("Fretboard naming",minutes,task,standard,"naming");
const shape=(minutes:number,task:string,standard:string)=>b("Shape work",minutes,task,standard,"shape");

const foundation=(day:number,stringName:string,shapeName:string,passage:string):BeastDay=>({day,phase:1,title:`${stringName}-string foundation`,objective:`Name any note on the ${stringName} string in under two seconds and play ${shapeName} without looking.`,context:`Natural notes, 0/5/7/12 anchors, octave derivation and safe ${shapeName} movement are trained before any sweep.`,standard:`20 random ${stringName}-string coordinates: 18 correct, each under two seconds.`,passages:[passage],blocks:[hands(),naming(12,`20 coordinate-to-note and 10 note-to-coordinate prompts on the ${stringName} string. Say before playing.`,`18/20 under two seconds.`),shape(12,`${passage} on the ${stringName} string through tempo rungs 1-3.`,`Three clean at rung 3.`),b("Octave web",8,"From every available natural note, find the two-strings-up/two-frets-across octave.","12 pairs with no hunting.","naming"),b("MILLPAD verbal",5,"Recite M-I-Ly-Lo-P-A-D ten times forward and ten backward away from the bass.","No hesitation.","millpad"),b("Silent map",5,`Eyes closed: walk fret 0-12 on the ${stringName} string and name every note.`,`Two complete passes.`,"naming"),log()]});

const transposeDay=(day:number,key:string,checkpoint=false):BeastDay=>({day,phase:5,title:`Transposition - ${key} major`,objective:`Generate and play the full ${key}-major traversal before revealing tab.`,context:"Use the seven-step key procedure: spell the key; degree each note; choose lowest playable scale note; assign its label; read four MILLPAD labels; convert shapes; apply only the required shift.",standard:day===23?"Any learned key: written starting row under 60 seconds, first four sweeps at rung 3 without tab.":`Three clean ${key}-major traversals at rung 3, generated rather than read.`,passages:["E21"],checkpoint,blocks:[hands(),naming(4,`Accidental-weighted recall in ${key} major.`,`Clean and correctly spelled.`),b("Paper generation",8,"Complete all seven generation questions before touching the bass.","Matches the atlas when revealed.","row"),b("Row generation",14,"Generate and play the four no-shift rows from labels alone, rungs 1-3.","Three clean at rung 3.","row"),b("Full traversal",16,"Join sweeps 1-4 with both turnarounds, rungs 1-3.","Three clean at rung 3.","row"),b("Interleave",10,"Alternate one sweep in today's key with one in an earlier key.","No key contamination.","row"),log()]});

export const BEAST_DAYS:BeastDay[]=[
 foundation(1,"E","WS-WS","E1"),foundation(2,"A","1-2-4","E2"),foundation(3,"D","1-3-4","E3"),foundation(4,"G","WS-WS","E1"),
 {day:5,phase:1,title:"Whole-neck foundation",objective:"Name any note anywhere on the neck and switch between all three shapes on command.",context:"Use the natural-note skeleton, B-C/E-F semitones, fifth-fret web and 0/5/7/12 anchors rather than memorizing 52 cells.",standard:"30 coordinates: 27 correct under two seconds; 20/20 shape switches; MILLPAD both ways; all C locations 0-12.",passages:["E1","E2","E3","E4"],blocks:[hands(),naming(12,"30 random string/fret prompts, then find every location of one called note.","27/30 under two seconds."),shape(15,"Random WS-WS, 1-2-4 or 1-3-4 every four bars from a called string and fret.","20 switches with no wrong shape."),b("Fifth-fret web",8,"Match E5/open A, A5/open D, D5/open G; recall fret-7 landmarks.","Instant recall.","naming"),b("MILLPAD lookup",5,"Recite both directions, then map 20 called labels to shapes.","20/20.","millpad"),b("Silent vertical map",7,"Name every note across all strings at frets 3, 8 and 10 with eyes closed.","No hesitation.","naming"),log()]},
 {day:6,phase:2,title:"Three-way MILLPAD lookup",objective:"Query MILLPAD in both directions instead of merely reciting the word.",context:"Train label to shape, shape to compatible labels, and label to next/previous. Group the grid as three wide, two half-first, two half-last.",standard:"28/30 mixed prompts.",passages:[],blocks:[hands(),naming(6,"15 maintenance coordinates.","14/15."),b("Label to shape",12,"State shape, offsets and fingers, then play from fret 5 on a random string.","28/30.","millpad"),b("Shape to labels",10,"Name every compatible label for a called interval pattern.","18/20.","millpad"),b("Label to next",12,"Give next forward and backward; flag Ly-Lo every time.","30 with no misses.","millpad"),b("Seven-start cycle",12,"Begin from each label, forward and backward.","14 clean recitations.","millpad"),log()]},
 {day:7,phase:2,title:"C-major labels on the neck",objective:"Attach labels to notes and scale degrees in C major.",context:"For each in-key coordinate say note, degree, label and shape. The degree layer—not the letter name—is what survives transposition.",standard:"22/25 degree prompts, 18/20 chunk placements, then re-pass Phase 1 and Day 6.",passages:[],checkpoint:true,blocks:[hands(),naming(6,"15 C-major coordinates.","14/15."),b("Degree drill",12,"Coordinate to note to degree to label to shape.","22/25.","naming"),b("Shape placement",12,"Play the correct C-major chunk beginning at a called coordinate.","18/20.","shape"),b("Checkpoint",15,"Re-run the complete Phase 1 standard and Day 6 exit test.","Both passed.","assessment"),b("MILLPAD",7,"Seven-start recitation both directions.","Clean.","millpad"),log()]},
 {day:8,phase:2,title:"Random C-major chunks",objective:"Play any single C-major chunk on any string, correctly labelled, without hunting.",context:"One chunk keeps the same shape wherever it appears. Location moves; interval structure does not.",standard:"Any label and string in under three seconds, 27/30; next/previous and shift stated.",passages:["E5"],blocks:[hands(),naming(5,"12 coordinates.","Clean."),b("Random chunk",20,"Called label and string: play lowest available position, then the next position up.","27/30 inside three seconds.","shape"),b("Chunk chaining",12,"Play one chunk, name the next label, then play it on the next string.","15 chains, no wrong shape.","millpad"),b("Plain sweep",12,"Read E5 slowly while speaking P-A-D-M. Do not memorize the tab.","Labels correct.","passage"),b("Seven-start cycle",3,"One complete forward/backward round.","Clean.","millpad"),log()]},
 {day:9,phase:3,title:"No-shift rows: Lo and P",objective:"Play Lo-P-A-D and P-A-D-M in C major with labels spoken at rung 3.",context:"Both begin half-step-first and remain in one fret column. Apply the six-pass protocol before the tempo ladder.",standard:"Three clean repetitions at rung 3.",passages:["E6"],blocks:[hands(),naming(5,"12 coordinates.","11/12."),shape(5,"E1-E3 once each at rung 4.","Clean."),b("Six-pass rows",24,"Say labels; say start frets; air-finger; play naming notes; play naming chunks; play silently hearing labels.","Three clean at rung 3.","row"),b("E6 pivot chunks",13,"Apply 1-2-1-3 inside today's rows while labels continue.","Labels still correct.","passage"),b("Crossing repair",5,"Loop only the last old-string note and first new-string note eight times.","No hesitation.","row"),log()]},
 {day:10,phase:3,title:"No-shift rows: A and D",objective:"Play A-D-M-I and D-M-I-Ly in C major with labels spoken at rung 3.",context:"Both begin half-step-last and remain in one fret column.",standard:"Three clean repetitions at rung 3.",passages:["E7"],blocks:[hands(),naming(5,"12 coordinates.","11/12."),shape(5,"E1-E3 once each at rung 4.","Clean."),b("Six-pass rows",24,"Run the full six-pass protocol on A and D rows.","Three clean at rung 3.","row"),b("E7 broken chunks",13,"Use 1-3-2 order without changing the underlying label.","Labels still correct.","passage"),b("Crossing repair",5,"Loop the weakest crossing eight times.","No hesitation.","row"),log()]},
 {day:11,phase:3,title:"Late-shift row: M",objective:"Play M-I-Ly-Lo in C major, shifting +1 only into the G string.",context:"Say the memory phrase: after three wides, the index steps forward.",standard:"Three clean repetitions at rung 3.",passages:["E8"],blocks:[hands(),naming(5,"12 coordinates.","11/12."),shape(5,"E1-E3 at rung 4.","Clean."),b("Six-pass M row",24,"Speak 3-3-3-4 as start columns and isolate the Ly-Lo crossing.","Three clean at rung 3.","row"),b("E8 retrograde",13,"Play chunk order G-D-A-E while each chunk ascends.","M-D-A-P tracked.","passage"),b("Shift repair",5,"Last D-string note to first G-string note, eight exact loops.","One relaxed +1 movement.","row"),log()]},
 {day:12,phase:3,title:"Early-shift rows: I and Ly",objective:"Play I-Ly-Lo-P and Ly-Lo-P-A with the +1 shift in the correct early crossing.",context:"The boundary is identical; only its string location changes.",standard:"Three clean repetitions at rung 3.",passages:["E9"],blocks:[hands(),naming(5,"12 coordinates.","11/12."),shape(5,"E1-E3 at rung 4.","Clean."),b("Six-pass I/Ly rows",24,"Name the exact crossing before playing each row.","Three clean at rung 3.","row"),b("E9 sequence in threes",13,"Separate the scale from Beast fingering through overlapping three-note sequences.","Labels and note order retained.","passage"),b("Shift repair",5,"Loop both shift locations in isolation.","No pre-shift tension.","row"),log()]},
 {day:13,phase:3,title:"All seven rows",objective:"Play any called C-major row without chart or setup time.",context:"Random order prevents one row from cueing the next. The route must come from state, not a memorized tape.",standard:"All seven rows called randomly at rung 4 with labels spoken.",passages:["E10"],blocks:[hands(),naming(5,"12 coordinates.","11/12."),shape(5,"Three shapes, random order.","Clean."),b("Random row deck",27,"All seven rows, no consecutive predictable order, full six-pass only after a miss.","Three clean at rung 4.","row"),b("E10 sequence in fours",13,"Accent groups of four, then groups of three over the same notes.","Time remains even.","passage"),b("State halt",5,"Stop mid-row and state key, direction, string and chunk.","Instant recovery.","row"),log()]},
 {day:14,phase:4,title:"G-string turnaround",objective:"Reverse direction and label order cleanly at the upper hinge.",context:"Take the next higher in-key note; do not repeat the last note. Direction and cycle order reverse together.",standard:"E15 looped ten times clean at rung 4.",passages:["E15","E16"],checkpoint:true,blocks:[hands(),naming(5,"Turn-note coordinates in C.","Clean."),b("Bridge drill",20,"Loop E15; say TURN on the hinge for ten reps, then internalize it.","Ten clean at rung 4.","passage"),b("Descending labels",10,"Read MILLPAD backward and name the ascending shape behind each descending chunk.","No false label.","millpad"),b("Micro-Beast",10,"E16 on two strings, then add one string at a time.","Clean.","passage"),b("Checkpoint",7,"Re-pass the seven-row Phase 3 exit standard.","Passed.","assessment"),log()]},
 {day:15,phase:4,title:"Both turnarounds",objective:"Play one complete up-down-up cycle with both hinges correct.",context:"At the E-string turn, take the next higher in-key note and reverse again. The next ascending start is two scale degrees above the original.",standard:"Three complete cycles at rung 3.",passages:["E15","E14"],blocks:[hands(),naming(5,"Turn notes and two-degree start checks.","Clean."),b("G turn",10,"E15 through rungs 3-5.","Three clean at rung 5.","passage"),b("E turn",12,"Isolate final descending E-string chunk, next higher note and new ascent.","No duplicate turn note.","row"),b("Full cycle",20,"Join one ascent, descent and next ascent; speak direction and labels.","Three clean at rung 3.","row"),b("Root-pedal Beast",8,"Use E14 to hear a tonal centre inside the route.","Pedal remains even.","passage"),log()]},
 {day:16,phase:4,title:"C-major full traversal",objective:"Join the first four C-major sweeps from open position toward fret 12.",context:"Restart from the nearest checkpoint, never from the top. The route climbs because every full cycle begins two scale notes higher.",standard:"Sweeps 1-4 joined without a navigation error.",passages:["E13"],blocks:[hands(),naming(5,"C-major locations 0-12.","Clean."),b("Route card",8,"Speak each row before uncovering it; cover all other rows.","Generated, not read.","row"),b("Sweeps 1-4",28,"Join ascent, descent, ascent and descent with exact hinge notes.","Unbroken at rung 2-3.","row"),b("Checkpoint restart",8,"Plant five restarts: sweep start, D entry, G turn, A entry down, E turn.","Resume within one beat.","row"),b("E13 octave displacement",6,"Hear identical letters in two registers.","Clean.","passage"),log()]},
 {day:17,phase:4,title:"Full C-major cycle from memory",objective:"Travel up to fret 12 and back without tab, then recover state when halted.",context:"This is the halfway proof: tab disappears and the four-variable state model replaces it.",standard:"One clean full pass at rung 2 or higher; five correct random state calls.",passages:["E12"],blocks:[hands(),naming(5,"C-major maintenance.","Clean."),b("Memory route",30,"Open to fret 12 and back; no chart within reach.","One unbroken pass at rung 2+.","row"),b("State recovery",10,"Random halts: key, direction, string, chunk, then continue.","5/5.","row"),b("E12 triads",6,"Say C, Dm, Em, F, G, Am, Bdim while playing diatonic triads.","Chord names correct.","passage"),log()]},
 transposeDay(18,"G"),transposeDay(19,"F"),transposeDay(20,"D"),transposeDay(21,"B-flat",true),transposeDay(22,"A"),transposeDay(23,"E-flat"),
 {day:24,phase:6,title:"Free E-string starts",objective:"Begin a correct sweep from any in-key E-string note in any learned key within ten seconds.",context:"Run the start-anywhere worksheet: key, note, in-key check, degree, label, shape, row and shift.",standard:"18/20 spoken starts inside ten seconds and 18/20 silent starts inside six.",passages:["E21"],blocks:[hands(),naming(4,"All strings maintenance.","Clean."),b("Spoken worksheet",15,"Random key and valid E-string fret; speak every answer then play.","18/20 inside ten seconds.","row"),b("Silent worksheet",12,"Same process internally.","18/20 inside six seconds.","row"),b("Two full sweeps",16,"Continue from each random start through a turnaround at rung 3.","Three clean.","row"),b("E21 in two keys",6,"Generate before reveal.","Generated, not read.","passage"),log()]},
 {day:25,phase:6,title:"Any string, either direction",objective:"Begin from A, D or G as well as E, and let the first sweep be short when necessary.",context:"Read only as many forward labels as there are strings left; take the turn; then read backward. Downward-first runs reverse the track immediately.",standard:"13/15 short sweeps, ten downward-first starts and one continuous rung-2 run.",passages:["E11"],blocks:[hands(),naming(4,"All strings.","Clean."),b("Short sweeps",18,"Random A/D/G start; reach G, turn, descend to E, turn, continue.","13/15 clean.","row"),b("Downward first",15,"Random valid start with cycle running backward from note one.","Ten clean.","row"),b("Long run",12,"Any key/start to fret 15 and back toward open.","One unbroken rung-2 pass.","row"),b("E11 thirds",8,"Generate diatonic thirds in the drawn key.","Clean.","passage"),log()]},
 {day:26,phase:6,title:"Whole neck to fret 17",objective:"Navigate open position to fret 17 and back in any key with no chart or hesitation.",context:"Fret 12 mirrors open; 15 mirrors fret 3; 17 mirrors fret 5. The map repeats while the visual landmarks and fret widths change.",standard:"Two whole-neck passes at rung 3; start any draw within six seconds; state recoverable when halted.",passages:["E10"],blocks:[hands(),naming(6,"Frets 12-17 only.","18/20."),b("Upper-neck rows",14,"All seven rows above fret 12 in C and one drawn key.","Clean at rung 4.","row"),b("Whole-neck run",20,"Open to 17 and back, one drawn key.","Two clean at rung 3.","row"),b("Speed ceiling",7,"Best key, rungs 6-7.","Three clean at top rung.","row"),b("E10 upper neck",5,"Four-note sequence in narrow frets.","Clean.","passage"),log()]},
 {day:27,phase:7,title:"Make modes audible",objective:"Turn physical chunk labels into perceived modal centres.",context:"A drone establishes home. Emphasize the characteristic tone that separates each mode from its nearest neighbour, and land on the drone every four bars.",standard:"Name Dorian/Aeolian and Phrygian/Aeolian contrasts blind; create one usable riff idea.",passages:["E17","E18","E19","E20"],blocks:[hands(),b("Traversal maintenance",7,"One drawn key at rung 4.","Clean.","row"),b("Modal drone work",25,"E17.2-E17.7, four minutes each; root, structure and characteristic tone.","Differences are audible.","drone"),b("A/B test",12,"Two bars Dorian / two Aeolian; then Phrygian / Aeolian over same root.","Name blind.","drone"),b("Riff seeds",8,"Change E18-E20 rhythm until one stops sounding like an exercise.","One usable idea saved.","passage"),log()]},
 {day:28,phase:7,title:"Write with the map",objective:"Use the material to produce three modal bass lines rather than another scale exercise.",context:"Choose root, third, fifth and characteristic tone as structure; use Beast chunks only as connective tissue.",standard:"Three recorded eight-bar lines in three different modes; identify which sounds most modal and least scalar.",passages:["E17","E18","E19","E20"],checkpoint:true,blocks:[hands(),b("Traversal maintenance",8,"Drawn key at rung 5.","Clean.","row"),b("Checkpoint",14,"Three free starts under six seconds.","Phase 6 re-passed.","assessment"),b("Composition",25,"Write and record three eight-bar lines in three modes.","Three distinct lines recorded.","drone"),b("Review",5,"Identify tonal centre, characteristic tone and any scale-running.","Evidence named.","assessment"),log()]},
 {day:29,phase:7,title:"No-reference consolidation",objective:"Perform all rows and all learned keys at tempo with the manual out of reach.",context:"The state model must now carry the entire route. This is retrieval under pressure, not more explanation.",standard:"Seven clean key traversals; 9/10 random starts; top tempo ceiling identified.",passages:[],blocks:[hands(),b("All seven rows",12,"C major, random order, rung 5.","All clean.","row"),b("All seven keys",20,"One full up-and-back traversal per learned key at rung 4.","Seven clean traversals.","row"),b("Random draws",12,"Ten starts, six-second limit, two sweeps each.","9/10.","row"),b("Speed pass",8,"Best key, push only while relaxed.","Three clean at ceiling.","row"),log()]},
 {day:30,phase:7,title:"Final assessment",objective:"Prove the month with one recorded eight-test assessment.",context:"The score selects the repair: 8/8 moves forward; 6-7 repeats only the failed phase for five days; below 6 normally returns to honest Phase 1 work.",standard:"Six of eight minimum; eight of eight completes acquisition and begins maintenance.",passages:[],blocks:[hands(5),b("Tests 1-3",12,"Fretboard recall, shape recall and MILLPAD recall.","All three pass.","assessment"),b("Tests 4-6",20,"Row generation, C traversal and transposition.","All three pass.","assessment"),b("Tests 7-8",13,"Free start and state recovery.","Both pass.","assessment"),b("Free play",5,"Use the map to play something you genuinely like.","Enjoy it.","drone"),log()]}
];

export const ERROR_CODES=[
 {code:"N",name:"Note",example:"Foreign pitch for the parent key"},{code:"C",name:"Chunk",example:"Wrong physical shape for the label"},{code:"S",name:"String",example:"Crossed before or after three notes"},{code:"D",name:"Direction",example:"Continued upward after a turn"},{code:"T",name:"Turnaround",example:"Repeated last note instead of next in-key note"},{code:"F",name:"Fret column",example:"Missed or invented the Ly-Lo shift"},{code:"R",name:"Rhythm",example:"Hesitated or rushed at a crossing"},{code:"M",name:"Muting",example:"A departed string is still ringing"},{code:"X",name:"Tension / body",example:"Locked wrist, clamped thumb or painful reach"}
];

export const REPAIR_PROTOCOL=["Stop immediately; do not install the mistake by playing through it.","Name the error code aloud.","State the intended note and MILLPAD label.","Play the failed chunk alone five correct times.","Add the chunk before it and play both three times.","Add the chunk after it and play all three twice.","Resume at least one tempo rung slower.","If the same code survives three sessions, return to the phase that teaches it."];

export const COMMON_CONFUSIONS=[
 ["Am I playing E Phrygian when I play E-F-G?","No. That is a Phrygian-shaped chunk. A mode needs E to be perceived as home through drone, harmony, emphasis and resolution."],
 ["If I start on A, did C major become A minor?","The collection is unchanged. Perceived home changes only when the musical emphasis changes."],
 ["Are 1-2-4 and 1-3-4 swapped?","Derive the frets from the finger names: 1-2-4 = x,x+1,x+3; 1-3-4 = x,x+2,x+3."],
 ["Why is descending C-B-A called Aeolian?","Labels name the low-to-high shape. A-B-C is W-H / Aeolian, even when played backward."],
 ["Why do I forget the Ly-Lo shift?","Use: after three wides, the index steps forward. Lo, P, A and D rows have no shift on four strings."],
 ["What if WS-WS hurts?","Shift the whole hand below fret 7 or move higher. Five frets cannot be held safely by a four-fret hand."],
 ["Why do I lose my place?","You are tracking fret numbers. Return to KEY-DIRECTION-STRING-CHUNK."],
 ["Why is the tab overwhelming?","Cover every row except the active route card. Generate first, reveal only to check."],
 ["Why do crossings rush?","Loop only the last note of the old string and the first of the new one eight times at 40 BPM."],
 ["Do open strings break the shapes?","No: 0-1-3 is H-W, 0-2-3 is W-H and 0-2-4 is W-W. The intervals survive."],
 ["Why can I play it but not transpose it?","Tab was memorized. Return to the seven-step paper procedure every day for a week."]
];

export const FINAL_TESTS=[
 {n:1,name:"Fretboard recall",standard:"30 random coordinates; 28 correct; each under two seconds"},{n:2,name:"Shape recall",standard:"All three shapes from called fret/string; 20/20"},{n:3,name:"MILLPAD recall",standard:"Forward and backward from any starting label; no hesitation"},{n:4,name:"Row generation",standard:"Any label/key: labels, columns and shift under ten seconds"},{n:5,name:"Full traversal",standard:"C major open to fret 12 and back; unbroken at rung 6"},{n:6,name:"Transposition",standard:"Any learned key; first four sweeps; rung 4; no chart"},{n:7,name:"Free start",standard:"Drawn key/note; correct inside six seconds; 9/10"},{n:8,name:"State recovery",standard:"Five random halts; key, direction, string and chunk; 5/5"}
];

export const COLLECTIONS=[
 {name:"Major",intervals:[0,2,4,5,7,9,11],note:"Three shapes, six stationary crossings and one +1 shift. The cleanest learning system."},
 {name:"Harmonic minor",intervals:[0,2,3,5,7,8,11],note:"Five shapes. Shifts at degrees 4 (+1), 6 (+1) and 7 (-1); augmented-second chunks demand care."},
 {name:"Melodic minor",intervals:[0,2,3,5,7,9,11],note:"Three narrow shape families, but three shifting crossings: degrees 3 (+1), 4 (+1), 7 (-1). Best next seven-note project."},
 {name:"Harmonic major",intervals:[0,2,4,5,7,8,11],note:"Five shapes. Shifts at degrees 3 (-1), 4 (+1) and 6 (+1). Included to prove the rule generalizes."},
 {name:"Minor pentatonic",intervals:[0,3,5,7,10],note:"Five-chunk cycle. Three-per-string forms are wide and shift +2 or +3; useful, but a post-Day-30 project."}
];

export const MAINTENANCE=[
 {minutes:2,task:"Twenty random coordinates"},{minutes:2,task:"Three shapes, one clean pass each at top rung"},{minutes:4,task:"One full traversal in a drawn key"},{minutes:2,task:"One silent worksheet draw, then two sweeps"}
];
