export type Passage={id:string;title:string;category:string;days:string;purpose:string;how:string;hammer:string;tab:string;variants?:{name:string;tab:string;note:string}[]};

export const PASSAGES:Passage[]=[
 {id:"E1",title:"WS-WS ladder",category:"Shape isolation",days:"1-7",purpose:"Wire the wide shape and the hand travel it requires.",how:"Move 3-5-7, 4-6-8, 5-7-9 and onward. Below fret 7 shift the whole hand instead of pinning a five-fret span.",hammer:"Four ascents and descents at 40 BPM. Watch that the thumb releases and the wrist stays neutral.",tab:`G|--------------------------------------------------------|\nD|--------------------------------------------------------|\nA|--------------------------------------------------------|\nE|--3-5-7--4-6-8--5-7-9--6-8-10--7-9-11--8-10-12------|`},
 {id:"E2",title:"1-2-4 ladder",category:"Shape isolation",days:"1-7",purpose:"Wire the half-step-first shape that often feels cramped and gets skipped.",how:"Use fingers 1,2,4 at x,x+1,x+3. Say half-whole. Finger 3 must not replace finger 2.",hammer:"Play E2 and immediately switch to E3 without stopping; feel the interval order before naming it.",tab:`G|--------------------------------------------------------|\nD|--------------------------------------------------------|\nA|--------------------------------------------------------|\nE|--5-6-8--6-7-9--7-8-10--8-9-11--9-10-12--10-11-13--|`},
 {id:"E3",title:"1-3-4 ladder",category:"Shape isolation",days:"1-7",purpose:"Wire the half-step-last shape and separate it physically from 1-2-4.",how:"Use fingers 1,3,4 at x,x+2,x+3. Say whole-half on every repetition.",hammer:"Alternate E2 and E3 with eyes closed. A random shape call must become sound inside two seconds.",tab:`G|--------------------------------------------------------|\nD|--------------------------------------------------------|\nA|--------------------------------------------------------|\nE|--5-7-8--6-8-9--7-9-10--8-10-11--9-11-12--10-12-13-|`},
 {id:"E4",title:"One shape across four strings",category:"Shape isolation",days:"1-7",purpose:"Prove that a shape belongs to a fret column rather than a particular string.",how:"Carry one shape E-A-D-G and back while muting every string you leave.",hammer:"Repeat all three shapes at frets 5, 9 and 2: the same interval geometry in three neighborhoods.",tab:`G|-----------------------------5-7-8---------------------------|\nD|--------------------5-7-8---------8-7-5--------------------|\nA|-----------5-7-8-------------------------8-7-5-------------|\nE|--5-7-8-----------------------------------------8-7-5------|`},
 {id:"E5",title:"Plain sweep",category:"Beast deformation",days:"8-17",purpose:"The control sample: twelve uninterrupted C-major notes assigned three per string.",how:"Speak P-A-D-M, one label per string. The tab is a consequence of the scale rule.",hammer:"Play once before and after every deformation so the unchanged note collection remains obvious.",tab:`G|-----------------------------0-2-4-|\nD|--------------------0-2-3----------|\nA|-----------0-2-3-------------------|\nE|--0-1-3----------------------------|`},
 {id:"E6",title:"Pivot chunks (1-2-1-3)",category:"Beast deformation",days:"8-17",purpose:"Break linear finger memory while preserving the four chunk labels.",how:"Inside every group play low-middle-low-high. Speak the chunk label only on the first note.",hammer:"If the label disappears, the fingers have overtaken the state model. Slow down until thought leads again.",tab:`G|--------------------------------------0-2-0-4-|\nD|--------------------------0-2-0-3-------------|\nA|--------------0-2-0-3-------------------------|\nE|--0-1-0-3-------------------------------------|`},
 {id:"E7",title:"Broken chunks (1-3-2)",category:"Beast deformation",days:"8-17",purpose:"Separate the physical shape from its default low-to-high order.",how:"Play low-high-middle with the hand shape still. Descending becomes 3-1-2.",hammer:"Alternate 1-3-2 and 3-1-2 between strings without losing labels.",tab:`G|-----------------------------0-4-2-|\nD|--------------------0-3-2----------|\nA|-----------0-3-2-------------------|\nE|--0-3-1----------------------------|`},
 {id:"E8",title:"Retrograde chunk order",category:"Beast deformation",days:"8-17",purpose:"Track labels independently by reversing strings while each chunk itself still ascends.",how:"Play G-D-A-E; the labels are M-D-A-P, the backward cycle.",hammer:"Call the label before each group. A clean pass proves that label and finger tape are separated.",tab:`G|--0-2-4----------------------------|\nD|-----------0-2-3-------------------|\nA|--------------------0-2-3----------|\nE|-----------------------------0-1-3-|`},
 {id:"E9",title:"Sequence in threes",category:"Beast deformation",days:"8-17",purpose:"Turn the same collection into melodic vocabulary independent of the Beast route.",how:"Play scale notes 1-2-3, then 2-3-4, then 3-4-5. Position fingering is deliberately allowed.",hammer:"Compare Beast fingering and position fingering. Hear that the notes are identical while the physical route changes.",tab:`G|------------------------------------------------------------------4-|\nD|--------------------------------------------3--3-5--3-5-7--5-7------|\nA|----------------------3--3-5--3-5-7--5-7---------------------------|\nE|--0-1-3--1-3-5--3-5-7----------------------------------------------|`},
 {id:"E10",title:"Sequence in fours",category:"Beast deformation",days:"8-17",purpose:"Create a four-note grouping that rolls against the three-note-per-string layout.",how:"Move each four-note group up one scale degree. Keep counting four across irregular string-crossing locations.",hammer:"Accent group-of-four starts, then group-of-three starts. Same notes, different rhythmic identity.",tab:`G|--------------------------------------------------------------------|\nD|-----------------------------------------------3--3-5--3-5-7--------|\nA|----------------------3--3-5--3-5-7--3-5-7-------------------------|\nE|--0-1-3-5--1-3-5-7--3-5-7-----------------------------------------|`},
 {id:"E11",title:"Diatonic thirds",category:"Beast deformation",days:"8-17",purpose:"Turn scale degrees into interval and harmony awareness.",how:"Play a note, skip one, play the next; advance one scale degree and repeat.",hammer:"Name major or minor third for every pair. The quality pattern is the harmony map.",tab:`G|-----------------------------------------------------4-|\nD|-----------------------------------3--5-3--7-5----------|\nA|------------------3--5-3--7-5--7----------------------|\nE|--0-3--1-5--3-7--5------------------------------------|`},
 {id:"E12",title:"Diatonic triads",category:"Beast deformation",days:"8-17",purpose:"Expose the chord contained in every modal degree.",how:"Root-third-fifth from each scale degree. Major: I, IV, V; minor: ii, iii, vi; diminished: vii.",hammer:"Say C, Dm, Em, F, G, Am, Bdim instead of mode names.",tab:`G|---------------------------------------------------------------4-|\nD|--------------------------------------3--5--3-7--5---------------|\nA|----------------3--5--3-7--5--3-7--5----------------------------|\nE|--0-3-7--1-5--3-7--5--------------------------------------------|`},
 {id:"E13",title:"Octave-displaced chunks",category:"Beast deformation",days:"8-17",purpose:"Destroy one-position tunnel vision using the two-strings-up/two-frets-across octave.",how:"Play the E chunk, then its octave copy on D; play the A chunk, then its copy on G.",hammer:"Reverse high copy first, and say the repeated note names.",tab:`G|-----------------------------2-4-5-|\nD|-----------2-3-5-------------------|\nA|--------------------0-2-3----------|\nE|--0-1-3----------------------------|`},
 {id:"E14",title:"Root-pedal Beast",category:"Beast deformation",days:"8-17",purpose:"Force a perceived tonic onto the route and demonstrate relative modality.",how:"Alternate the low root with every scale note. Keep the pedal dynamically and rhythmically even.",hammer:"Move the pedal from C to A while leaving the upper notes unchanged; describe why the same collection becomes minor.",tab:`G|-------------------------------------------0---2---4-|\nD|-----------------------------0---2---3---------------|\nA|----------------0---2---3----------------------------|\nE|--8-0-8-1-8-3-8---8---8---8---8---8---8---8---8----|`},
 {id:"E15",title:"Six-note G-string bridge",category:"Turnarounds",days:"12-17",purpose:"Isolate the instant when both direction and label order reverse.",how:"Three notes up on G, the next higher in-key turn note, two notes back, then the first descending D-string group.",hammer:"Loop ten times at 40 BPM. Say TURN exactly on the hinge, then repeat with the cue internal.",tab:`G|--0-2-4-5-4-2----------|\nD|--------------5-3-2----|\nA|-----------------------|\nE|-----------------------|`},
 {id:"E16",title:"Two-string micro-Beast",category:"Turnarounds",days:"12-17",purpose:"Own a complete up-and-back route with only one crossing before adding complexity.",how:"Use E and A only. Take the next in-key note at the top before descending.",hammer:"Add D on the next pass and G on the next. One string per session makes the full system ordinary.",tab:`G|--------------------------------------|\nD|--------------------------------------|\nA|-----------0-2-3-3-2-0----------------|\nE|--0-1-3----------------3-1-0----------|`},
 {id:"E17",title:"Modal statements",category:"Modal conversion",days:"24-30",purpose:"Make a mode audible by establishing home, structural tones and the defining comparison tone.",how:"Loop the chosen root. Use only the parent collection, land on home every four bars, and lean on the characteristic degree.",hammer:"Twelve four-bar repetitions per mode; then A/B the nearest-neighbour modes with the same root.",tab:"Choose one of the six manual statements below.",variants:[
  {name:"D Dorian - major 6",tab:`G|----------------------|\nD|----------------------|\nA|----12---14---14-------|\nE|-10---10---13---10-----|`,note:"Compare D Aeolian; make B natural audible."},
  {name:"E Phrygian - flat 2",tab:`G|----------------------|\nD|----------------------|\nA|-----2----------------|\nE|--0----0-1-3-1-0------|`,note:"Compare E Aeolian; F is the exposed rub."},
  {name:"F Lydian - sharp 4",tab:`G|----------------------|\nD|----------------------|\nA|-----3----2----2-------|\nE|--1----1----5----1-----|`,note:"Compare F Ionian; B natural carries identity."},
  {name:"G Mixolydian - flat 7",tab:`G|----------------------|\nD|-----------3----3------|\nA|-----5----------------|\nE|--3----3----7----3-----|`,note:"Compare G Ionian; F natural removes leading-tone pull."},
  {name:"A Aeolian - flat 6",tab:`G|----------------------|\nD|----------------------|\nA|-----7----8----8-------|\nE|--5----5----8----5-----|`,note:"Compare A Dorian; F natural darkens the sixth."},
  {name:"B Locrian - flat 5",tab:`G|----------------------|\nD|----------------------|\nA|-----8----8----8-------|\nE|--7----7---10----7-----|`,note:"Compare B Phrygian; F removes the perfect fifth."}
 ]},
 {id:"E18",title:"Aeolian riff seed",category:"Riff seeds",days:"Any",purpose:"A root-heavy rock cell that foregrounds the flat sixth.",how:"Palm-mute the root and let upper pickups ring. Change the rhythm until it becomes yours.",hammer:"Move the same rhythmic idea to a Phrygian centre without changing the parent collection.",tab:`G|-------------------------------------------|\nD|-------------------------------------------|\nA|-------------------------------7-5---------|\nE|--5-5-7-5-5-8-5-7-5-5-------------8-7----|`},
 {id:"E19",title:"Phrygian riff seed",category:"Riff seeds",days:"Any",purpose:"Make the root-flat-2 half step into a usable heavy hook.",how:"Hit the flat 2 hard, then fall back to home; the semitone is the entire identity.",hammer:"Transpose the cell to D inside B-flat major and B inside G major.",tab:`G|-------------------------------------------|\nD|-------------------------------------------|\nA|-------------------------------2-0---------|\nE|--0-0-1-0-0-3-0-1-0-0-------------3-1----|`},
 {id:"E20",title:"Dorian riff seed",category:"Riff seeds",days:"Any",purpose:"Contrast Dorian's natural sixth with Aeolian's flat sixth in a groove context.",how:"Let the major sixth ring against the root. Keep the same rhythm used for E18.",hammer:"Alternate one bar E18 and one bar E20 until the sixth change is audible without labels.",tab:`G|-------------------------------------------|\nD|-------------------------------------------|\nA|------------------------------12-10--------|\nE|-10-10-12-10-10-13-10-12-10-10-----13-12-|`},
 {id:"E21",title:"Transposition checks",category:"Transposition",days:"18-23",purpose:"Generate a route in a new key before revealing any fret number.",how:"Say the four labels and four start columns, play, then uncover the route only to check.",hammer:"Generate three different keys in succession. If the letters contaminate each other, return to the paper procedure.",tab:"Choose a manual check below.",variants:[
  {name:"G major from degree 5",tab:`G|----------------------------11-12-14-|\nD|-------------------10-12-14----------|\nA|----------10-12-14-------------------|\nE|-10-12-14----------------------------|`,note:"M-I-Ly-Lo; columns 10,10,10,11."},
  {name:"F major from tonic",tab:`G|-----------------------------2-3-5-|\nD|--------------------2-3-5----------|\nA|-----------1-3-5-------------------|\nE|--1-3-5----------------------------|`,note:"I-Ly-Lo-P; columns 1,1,2,2."},
  {name:"D major from degree 2",tab:`G|----------------------------12-14-16-|\nD|-------------------12-14-16----------|\nA|----------12-14-16-------------------|\nE|-12-14-15----------------------------|`,note:"D-M-I-Ly; one column at fret 12."},
  {name:"B-flat major from degree 4",tab:`G|----------------------------12-14-15-|\nD|-------------------12-13-15----------|\nA|----------12-13-15-------------------|\nE|-11-13-15----------------------------|`,note:"Ly-Lo-P-A; columns 11,12,12,12."}
 ]}
];
