"use client";

import {useEffect,useRef,useSyncExternalStore} from "react";

const STORAGE_KEY="basslab-language";

const EXACT:Record<string,string>={
 "Course Home":"الرئيسية",
 "Current Lesson":"الدرس الحالي",
 "Course Map":"خريطة الكورس",
 "Harmony Fretboard":"فريت بورد الهارموني",
 "Practice Studio":"ستوديو التمرين",
 "Adaptive Coach":"المدرّب الذكي",
 "Slap Bass Academy":"أكاديمية السلاب باص",
 "Arabic Maqam Lab":"مختبر المقامات العربية",
 "My Progress":"تقدّمي",
 "Theory Reference":"مرجع النظريات",
 "BASS LAB":"مختبر الباص",
 "STRUCTURED MODES COURSE":"كورس المقامات الغربية المنظّم",
 "COURSE PROGRESS":"تقدّم الكورس",
 "LESSONS PASSED":"درس اتعدّى بنجاح",
 "BASS NOT CONNECTED":"الباص مش متوصل",
 "INPUT ACTIVE":"المدخل شغّال",
 "Optional for coached practice":"اختياري للتمرين مع المدرّب",
 "● CONNECT BASS":"● وصّل الباص",
 "■ STOP LISTENING":"■ وقّف الاستماع",
 "YOUR MODES & IMPROVISATION COURSE":"كورس المقامات الغربية والارتجال بتاعك",
 "Learn the sound.":"اسمع الصوت واتعلّمه.",
 "Then create with it.":"وبعدين اعمل بيه موسيقى.",
 "One ordered path from hearing home to modal improvisation and controlled outside playing. Every tool appears inside the lesson that teaches you how and why to use it.":"طريق واحد مترتّب، من سماع القرار لحد الارتجال والتحكّم في العزف برّه المقام. كل أداة هتظهر جوّه الدرس اللي بيشرح لك تستخدمها إزاي وليه.",
 "CURRENT LESSON":"الدرس الحالي",
 "LESSON PROGRESS":"تقدّم الدرس",
 "CONTINUE":"كمّل",
 "TODAY’S ORDER":"ترتيب تمرين النهارده",
 "One lesson. Four focused blocks.":"درس واحد. أربع فترات مركّزة.",
 "Finish these in order. Extra tools stay out of the way until the lesson asks for them.":"خلّصهم بالترتيب. الأدوات الزيادة مش هتظهر غير لما الدرس يحتاجها.",
 "LEARN":"اتعلّم",
 "HEAR":"اسمع",
 "PLAY":"اعزف",
 "PROVE":"اثبت",
 "THE COMPLETE PATH":"المسار الكامل",
 "Six units. No random wandering.":"ست وحدات. من غير لفّ عشوائي.",
 "PREVIOUS":"اللي فات",
 "NEXT":"اللي بعده",
 "COMPLETE & CONTINUE":"كمّل وروح للي بعده",
 "LOG JURY RESULT":"سجّل نتيجة الاختبار",
 "THE BIG IDEA":"الفكرة الأساسية",
 "BEFORE YOU TOUCH THE BASS":"قبل ما تمسك الباص",
 "Hear the function before learning the shape.":"اسمع وظيفة النغمة قبل ما تحفظ شكلها.",
 "LISTEN FOR":"ركّز في سماع",
 "HARMONIC MAP":"الخريطة الهارمونية",
 "See one octave as gravity, not permission.":"شوف الأوكتاف كدرجات جذب، مش كقائمة نغمات مسموحة.",
 "STRUCTURE":"الهيكل",
 "COLOUR":"اللون",
 "TENSION":"التوتّر",
 "WHY IT WORKS":"ليه ده بيشتغل",
 "CAUSE":"السبب",
 "CONTROL VARIABLE":"عامل التحكّم",
 "COMMON FAILURE":"غلطة شائعة",
 "GUIDED PLAY · DELIBERATE REPS":"عزف موجّه · تكرارات مقصودة",
 "SETUP":"التجهيز",
 "TASK":"المطلوب",
 "DOSE":"عدد التكرارات",
 "TEMPO POLICY":"قاعدة السرعة",
 "APPLY · MAKE MUSIC":"طبّق · اعمل موسيقى",
 "STATE":"ثبّت",
 "DEVELOP":"طوّر",
 "DESTABILIZE":"زوّد التوتّر",
 "RETURN":"ارجع",
 "ANALYZE · THE EAR AFTER THE TAKE":"حلّل · ودانك بعد التسجيل",
 "MINI JURY · PROVE IT":"اختبار صغير · اثبت إنك فاهم",
 "PASS 80/100":"النجاح من ٨٠/١٠٠",
 "BEGIN JURY TAKE":"ابدأ تسجيل الاختبار",
 "OPEN GUIDED BAND":"افتح الفرقة الموجّهة",
 "RECORD APPLICATION TAKE":"سجّل تطبيق موسيقي",
 "A map—not":"خريطة — مش",
 "a second course.":"كورس تاني.",
 "Use this only when a lesson asks you to check a formula or comparison.":"استخدم المرجع ده بس لما الدرس يطلب منك تراجع تركيبة أو مقارنة.",
 "THE SEVEN MODES · SAME ROOT":"السبع مقامات الغربية · نفس القرار",
 "THINK MODALLY WHEN":"فكّر بالمقام لما",
 "THINK FUNCTIONALLY WHEN":"فكّر بالهارموني الوظيفي لما",
 "THINK HYBRID WHEN":"اخلط الطريقتين لما",
 "One centre has time to develop.":"قرار واحد عنده وقت يتطوّر.",
 "Chords create directional gravity.":"الكوردات بتعمل اتجاه واضح للجذب.",
 "A home centre contains local chord motion.":"قرار أساسي جواه حركة كوردات مؤقتة.",
 "Start":"ابدأ",
 "Stop":"وقّف",
 "Continue":"كمّل",
 "Complete":"كمّل",
 "Correct":"صح",
 "Try again":"جرّب تاني",
 "PASS":"نجاح",
 "FAIL":"محتاج إعادة",
 "CORRECT":"صح",
 "WRONG":"غلط",
 "READY":"جاهز",
 "ACTIVE":"شغّال",
 "COMPLETE":"اكتمل",
 "FOUNDATION":"أساسيات",
 "LEARNED":"اتعلّمت",
 "UNDERSTOOD":"مفهوم",
 "PLAYABLE":"قابل للعزف",
 "MUSICAL":"موسيقي",
 "AUTOMATIC":"تلقائي",
 "UNASSESSED":"لسه ما اتقيّمش",
 "TODAY":"النهارده",
 "ASSESS":"تقييم",
 "EVIDENCE":"الدليل",
 "HISTORY":"السجل",
 "TODAY’S PRESCRIPTION":"روشتة تمرين النهارده",
 "GENERATE TODAY’S SESSION":"جهّز تمرين النهارده",
 "START HANDS-FREE SESSION":"ابدأ جلسة من غير لمس الشاشة",
 "EMERGENCY STOP":"إيقاف طوارئ",
 "The next cue, correction, tempo change, repair and block transition happen automatically. Only Emergency Stop interrupts the routine.":"التعليمات والتصحيح وتغيير السرعة وتمرين الإصلاح والانتقال بين الفترات بيحصلوا لوحدهم. زر إيقاف الطوارئ هو الحاجة الوحيدة اللي بتقطع الجلسة.",
 "Use headphones and a clean DI/audio-interface signal. Speaker audio can leak reference tones or speech into the mic. Monophonic playing and clean muting give the most reliable detection.":"استخدم سماعات وإشارة نظيفة من الـDI أو كارت الصوت. صوت السماعات الخارجية ممكن يدخل الميكروفون ويلخبط القياس. اعزف نغمة واحدة واعمل كتم نضيف عشان النتيجة تبقى أدق.",
 "WAITING FOR INPUT":"مستني الإشارة",
 "TIME REMAINING":"الوقت الباقي",
 "CURRENT CUE":"التعليمات الحالية",
 "AUTOMATIC CORRECTION":"التصحيح التلقائي",
 "SESSION COMPLETE":"الجلسة خلصت",
 "REPAIR LOOP":"دورة إصلاح",
 "PROOF PASS":"جولة إثبات",
 "ESTABLISH HOME":"ثبّت القرار",
 "Repeat slowly":"كرّر براحة",
 "Connect the material":"وصّل الأفكار ببعض",
 "Apply it musically":"طبّقها بشكل موسيقي",
 "Proof pass":"جولة إثبات",
 "BEGINNER → ADVANCED · ORIGINAL CURRICULUM":"من مبتدئ لمتقدّم · منهج أصلي",
 "SLAP IS A":"السلاب أساسه",
 "TIME FEEL.":"الإحساس بالوقت.",
 "START HANDS-FREE ROUTINE →":"ابدأ تمرين من غير ما تلمس الشاشة ←",
 "SEE ALL 7 LEVELS":"شوف المستويات السبعة",
 "THE MASTERY ORDER":"ترتيب الإتقان",
 "TIME":"الوقت",
 "POCKET":"الجروف",
 "TONE + DYNAMICS":"الصوت والديناميكس",
 "MUTING":"الكتم",
 "VOCABULARY":"المفردات",
 "SPEED":"السرعة",
 "PATH":"المسار",
 "EXERCISE":"التمرين",
 "AUTO ROUTINE":"روتين تلقائي",
 "GROOVE ENGINE":"محرّك الجروف",
 "PROOF":"الإثبات",
 "WHAT “WOOTEN LEVEL” MEANS HERE":"يعني إيه مستوى ووتن هنا",
 "Musical command, not copied tricks.":"تحكّم موسيقي، مش تقليد حركات.",
 "MICROPHONE CAN VERIFY":"الميكروفون يقدر يقيس",
 "YOU MUST SELF-CHECK":"لازم تراجع بنفسك",
 "EXACT MOVEMENT":"الحركة بالتفصيل",
 "AUDIO-VERIFIED":"اللي الصوت بيقيسه",
 "BODY + MUTING CHECK":"مراجعة الجسم والكتم",
 "MUSICAL TRANSFER":"التطبيق الموسيقي",
 "ONE TOUCH · VOICE CUES · AUTOMATIC TRANSITIONS":"لمسة واحدة · تعليمات صوتية · انتقال تلقائي",
 "Keep both hands on the bass.":"خلّي إيديك الاتنين على الباص.",
 "BUILD METHOD":"طريقة بناء التمرين",
 "SET EACH BLOCK":"حدّد وقت كل جزء",
 "MIN SELECTED":"دقيقة مختارة",
 "SKIPPED":"متشال",
 "Selected blocks are automatically rebalanced to fill exactly":"الأجزاء المختارة هيتوزّع وقتها تلقائياً عشان تكمّل بالظبط",
 "Your routine ends when the selected block minutes are complete.":"الروتين هيخلص لما وقت الأجزاء اللي اخترتها يخلص.",
 "START ONCE — COACH TAKES OVER":"ابدأ مرة واحدة — المدرّب هيكمّل",
 "PAUSE ROUTINE":"وقّف الروتين مؤقتاً",
 "ATTACKS":"الضربات",
 "AVG GRID":"متوسط التوقيت",
 "LEVEL":"المستوى",
 "MUTE EVERY 4TH BAR":"اسكت الكليك كل رابع مازورة",
 "START GROOVE ENGINE":"شغّل محرّك الجروف",
 "STOP ENGINE":"وقّف المحرّك",
 "THE THREE-DAY TEMPO GATE":"بوابة السرعة في ٣ أيام",
 "Fast is earned slowly.":"السرعة بتتكسب واحدة واحدة.",
 "LOG TODAY’S CLEAN PASS":"سجّل نجاح النهارده",
 "JURY RUBRIC · 100":"معايير الاختبار · ١٠٠",
 "MUSICAL CHOICE":"الاختيار الموسيقي",
 "STOP SIGNAL":"إشارة توقف",

 "ARABIC MUSIC LAB · مختبر المقامات":"مختبر الموسيقى العربية · المقامات",
 "Don’t memorize a scale.":"ما تحفظش سلّم.",
 "Learn how the maqam moves.":"اتعلّم المقام بيتحرّك إزاي.",
 "A bass-first laboratory for ajnas, sayr, quarter-tone intonation, hand routes, modulation and uninterrupted guided practice.":"مختبر معمول للباص عشان تتعلّم الأجناس والسير وضبط أرباع الصوت ومسارات الإيد والتحويل، مع تمرين موجّه من غير ما توقف.",
 "SELECTED MAQAM":"المقام المختار",
 "▶ HEAR ASCENT + RETURN":"▶ اسمع الصعود والرجوع",
 "EXPLORE":"افهم",
 "FRETBOARD":"لوحة الباص",
 "SWITCH":"التحويل",
 "PRACTICE":"التمرين",
 "BACKING":"المصاحبة",
 "MAQAM":"المقام",
 "PRACTICE ROOT":"قرار التمرين",
 "INSTRUMENT PATH":"طريقة الآلة",
 "FRETTED":"بفريتات",
 "FRETLESS / TRUE PITCH":"فريتلس / نغمة دقيقة",
 "THE ESSENTIAL DISTINCTION · الفكرة الأساسية":"الفرق الأساسي · الفكرة الأساسية",
 "A maqam is more than an octave scale.":"المقام أكبر من مجرد سلّم أوكتاف.",
 "Its identity comes from connected pitch cells called":"هويته بتيجي من خلايا نغمية متصلة اسمها",
 "characteristic melodic phrases, important resting points, modulation possibilities, ornamentation and a customary melodic course—the":"وجمل لحنية مميزة ودرجات ركوز مهمة وإمكانيات تحويل وزخارف ومسار لحني متعارف عليه اسمه",
 "A 3–5 note melodic unit with its own tonic and emphasis.":"وحدة لحنية من ٣ لـ٥ نغمات، ليها قرارها ودرجات تركيزها.",
 "A secondary station and frequent doorway to another jins.":"محطة ثانوية، وغالباً باب لجنس تاني.",
 "The typical path: what appears first, where it rises, and how it returns.":"المسار المعتاد: إيه يظهر الأول، اللحن يطلع لفين، ويرجع إزاي.",
 "START HERE":"ابدأ من هنا",
 "CORE":"أساسي",
 "BRIDGE":"جسر",
 "ADVANCED":"متقدّم",
 "MICROTONAL":"أرباع صوت",
 "12-TONE FRIENDLY":"مناسب للفريتات العادية",
 "▶ HEAR EXACT-CENT MAP":"▶ اسمع خريطة السنت الدقيقة",
 "LOWER IDENTITY":"هوية المنطقة الواطية",
 "GHAMMAZ / BRIDGE":"الغمّاز / الجسر",
 "UPPER POSSIBILITY":"احتمال الجنس العالي",
 "Possibility—not an automatic chord-scale rule. The melodic route decides when it appears.":"ده احتمال، مش قاعدة كورد/سلّم تلقائية. مسار الجملة هو اللي بيحدّد يظهر إمتى.",
 "SAYR · MELODIC COURSE":"السير · مسار اللحن",
 "FRETTED-BASS METHOD":"طريقة الباص بفريتات",
 "FRETLESS / MICROTONAL METHOD":"طريقة الفريتلس / أرباع الصوت",
 "DO NOT DO THIS":"خلي بالك من الغلطة دي",
 "LEFT-HAND MAP · خريطة اليد":"خريطة الإيد الشمال · مواضع العزف",
 "Anchor the fret. Then create the pitch.":"ثبّت مكان الفريت، وبعدين كوّن النغمة.",
 "Highlighted cells are the lower equal-tempered anchors. A":"الخانات المنوّرة هي نقطة البداية الأقل في الضبط المتساوي. علامة",
 "badge means bend or slide halfway toward the next fret—never squeeze harder with the thumb.":"معناها اعمل بند أو سلايد لنص المسافة ناحية الفريت اللي بعده. ما تعصرش الرقبة بإبهامك.",
 "SAFE HAND RULE":"قاعدة أمان الإيد",
 "Keep the thumb mobile and wrist neutral. If four frets feel forced, release pressure and shift the whole hand; do not stretch through pain.":"خلّي الإبهام بيتحرّك والرسغ مريح. لو أربع فريتات عاملين شد، ريّح الضغط وانقل الإيد كلها؛ ما تتمطّش مع وجع.",
 "LOW · 0–5":"واطي · ٠–٥",
 "MIDDLE · 5–10":"وسط · ٥–١٠",
 "UPPER · 9–15":"عالي · ٩–١٥",
 "FULL · 0–15":"كامل · ٠–١٥",
 "STRING":"وتر",
 "TONIC":"القرار",
 "GHAMMAZ":"الغمّاز",
 "MICROTONAL ANCHOR + BEND":"بداية ربع الصوت + بند",
 "Click any highlighted note to make it the live intonation target.":"دوس على أي نغمة منوّرة عشان تبقى هدف الضبط المباشر.",
 "ONE PLAYABLE ROUTE":"مسار عزف مقترح",
 "This is a movement suggestion, not a fixed fingering law. Keep one finger over the pivot while the thumb travels with the hand.":"ده اقتراح لحركة الإيد، مش قانون صوابع ثابت. خلّي صباع مرشد فوق نقطة التحويل، والإبهام يتحرّك مع الإيد.",
 "SHIFT HAND":"انقل الإيد",
 "SHIFT SEQUENCE":"خطوات نقل الإيد",
 "Finish the old note.":"كمّل النغمة القديمة.",
 "Release finger pressure but keep skin contact.":"ريّح ضغط الصباع مع استمرار اللمس الخفيف.",
 "Move thumb and hand as one unit.":"حرّك الإبهام والإيد كوحدة واحدة.",
 "Land near the ghammaz; listen before pressing harder.":"انزل قريب من الغمّاز؛ اسمع قبل ما تزود الضغط.",
 "JINS-TO-JINS MOVEMENT · التحويل":"التحويل من جنس لجنس",
 "Keep the shared station.":"ثبّت المحطة المشتركة.",
 "Change the melodic evidence.":"وغيّر الدليل اللحني.",
 "Real modulation is not merely replacing one same-root scale with another. It changes emphasis, introduces a new jins at a pivot, and proves the new destination by phrase behavior.":"التحويل الحقيقي مش مجرد تبديل سلّمين على نفس القرار. هو بيغيّر مركز التركيز، ويدخل جنس جديد عند نقطة مشتركة، ويثبت الوجهة الجديدة بطريقة الجملة.",
 "COMMON PRACTICE ROUTES":"مسارات تحويل شائعة للتمرين",
 "ON DEGREE 4":"على الدرجة الرابعة",
 "ON DEGREE 5":"على الدرجة الخامسة",
 "SAME TONIC STUDY":"تمرين على نفس القرار",
 "FROM":"من",
 "TO":"إلى",
 "PIVOT LOCATION":"مكان التحويل",
 "Same tonic":"نفس القرار",
 "Source degree 4":"الدرجة الرابعة من المصدر",
 "Source degree 5":"الدرجة الخامسة من المصدر",
 "HOLD THIS STATION":"ثبّت المحطة دي",
 "▶ HEAR DESTINATION MAP":"▶ اسمع خريطة المقام الجديد",
 "SHARED / NEAR-SHARED PITCHES":"النغمات المشتركة أو القريبة",
 "DESTINATION EVIDENCE TO INTRODUCE":"النغمات اللي هتثبت المقام الجديد",
 "No exact common pitch at this simplified route. Use the chosen station as a melodic hand-off.":"مفيش نغمة مشتركة دقيقة في المسار المبسّط ده. استخدم المحطة المختارة كتسليم لحني.",
 "EXACT 8-BAR ROUTE":"مسار ٨ موازير بالتفصيل",
 "One switch. No guesswork.":"تحويل واحد. من غير تخمين.",
 "ESTABLISH":"ثبّت",
 "APPROACH":"اقرّب",
 "HOLD":"اثبت",
 "REVEAL":"اظهر اللون",
 "CONFIRM":"أكّد",
 "CADENCE":"اقفل الجملة",
 "HAND MOVE":"حركة الإيد",
 "HANDS-FREE PRACTICE · تدريب بدون لمس الشاشة":"تمرين من غير لمس الشاشة",
 "Press start once.":"دوس ابدأ مرة واحدة.",
 "The coach speaks every phase, advances the clock, listens to pitch, and gives low / high / wrong-note corrections. The only control left on screen is stop.":"المدرّب هيقول كل مرحلة، ويحرّك الوقت، ويسمع النغمة، ويصحّح واطي / عالي / نغمة غلط. الزر الوحيد اللي هتحتاجه هو الإيقاف.",
 "BEST SIGNAL":"أفضل إشارة",
 "Bass → audio interface → browser input. Use headphones when the backing track is active so the microphone hears the bass, not the speakers.":"الباص ← كارت الصوت ← مدخل المتصفح. استخدم سماعات لما المصاحبة شغّالة عشان الميكروفون يسمع الباص مش السماعات الخارجية.",
 "Root + jins lock":"تثبيت القرار والجنس",
 "Quarter-tone intonation":"ضبط أرباع الأصوات",
 "Sayr ladder":"سُلّم السير اللحني",
 "Ghammaz bridge":"جسر الغمّاز",
 "Maqam switch":"تحويل المقام",
 "Taqsim proof":"إثبات التقسيم",
 "Press start once. Keep both hands on the bass.":"دوس ابدأ مرة واحدة، وخلي إيديك الاتنين على الباص.",
 "LIVE ROUTINE":"الروتين شغّال",
 "SELECTED ROUTINE":"الروتين المختار",
 "LISTENING TARGET":"النغمة المطلوبة",
 "INPUT OFF":"المدخل مقفول",
 "PLAY TARGET":"اعزف النغمة المطلوبة",
 "CENTERED":"مظبوطة",
 "LOW":"واطية",
 "HIGH":"عالية",
 "WRONG NOTE":"نغمة غلط",
 "Waiting for a stable bass note":"مستني نغمة باص ثابتة",
 "COMPLETE ROUTINE SCRIPT":"تفاصيل الروتين كاملة",
 "Know exactly what will happen.":"اعرف بالظبط إيه اللي هيحصل.",
 "PASS CONDITION":"شرط النجاح",
 "GENERATIVE ACCOMPANIMENT · مصاحبة آلية":"مصاحبة موسيقية آلية",
 "Drone first.":"الدرون هو الأساس.",
 "Rhythm without harmonic clutter.":"إيقاع من غير زحمة هارمونية.",
 "Maqam is primarily melodic, so these tracks use a tonic/fifth drone, a soft ghammaz cue and programmable iqa‘—not a Western chord loop that dictates the phrase.":"المقام أساسه لحني، عشان كده المسارات دي فيها درون للقرار والخامسة، وإشارة خفيفة للغمّاز، وإيقاع قابل للتعديل—مش لوب كوردات غربي يفرض شكل الجملة.",
 "NO AUDIO FILES":"من غير ملفات صوت جاهزة",
 "Every track is generated in real time. Change maqam, root, rhythm, tempo and form to create a new practice bed.":"كل مصاحبة بتتولّد وقتها. غيّر المقام والقرار والإيقاع والسرعة والفورمة عشان تعمل أرضية تمرين جديدة.",
 "NOW CONFIGURED":"الإعداد الحالي",
 "▶ START BACKING":"▶ شغّل المصاحبة",
 "■ STOP BACKING":"■ وقّف المصاحبة",
 "TEMPO":"السرعة",
 "DRONE":"الدرون",
 "PERCUSSION":"الإيقاع",
 "FORM":"الفورمة",
 "BAR":"مازورة",
 "GUIDED PROMPT":"توجيه العزف",
 "ESTABLISH THE LOWER JINS":"ثبّت الجنس السفلي",
 "LEAN ON THE GHAMMAZ":"ركّز على الغمّاز",
 "REVEAL THE UPPER JINS":"اظهر الجنس العلوي",
 "DESCEND AND PROVE HOME":"انزل وثبّت القرار",
 "WHEN LISTENING COACH IS ON:":"لما المدرّب المستمع يكون شغّال:",
 "wear headphones and send the bass directly to the selected input. Speaker bleed can be mistaken for your note.":"البس سماعات وابعت إشارة الباص مباشرة للمدخل المختار. تسريب صوت السماعات ممكن يتحسب نغمتك.",
 "4-BAR LOOP":"لوب ٤ موازير",
 "8-BAR LOOP":"لوب ٨ موازير",
 "16-BAR LOOP":"لوب ١٦ مازورة",
 "Intonation":"ضبط النغمة",
 "INTONATION NOTE":"ملاحظة عن الضبط",
 "AJNAS → SAYR → INTONATION → MODULATION → MUSIC":"أجناس ← سير ← ضبط ← تحويل ← موسيقى",
 "Ajam family":"عيلة العجم",
 "Bayati family":"عيلة البياتي",
 "Hijaz family":"عيلة الحجاز",
 "Kurd family":"عيلة الكرد",
 "Nahawand family":"عيلة النهاوند",
 "Rast family":"عيلة الراست",
 "Sikah family":"عيلة السيكاه",
 "Independent":"مستقل",
 "Jins Bayati":"جنس بياتي",
 "Jins Rast":"جنس راست",
 "Jins Hijaz":"جنس حجاز",
 "Jins Kurd":"جنس كرد",
 "Jins Nahawand":"جنس نهاوند",
 "Jins Ajam":"جنس عجم",
 "Jins Saba":"جنس صبا",
 "Jins Sikah":"جنس سيكاه",
 "POSITION":"موضع",
 "OPEN STRING":"وتر مفتوح",
 "CENTRE":"مظبوط",
 "BEND":"بند",
 "FINGER":"صباع",
 "MIN":"دقيقة",
 "MINUTES":"دقايق",
 "START":"ابدأ",
 "HANDS-FREE ROUTINE":"روتين من غير لمس الشاشة",
 "Fret anchor":"بداية الفريت",
 "Listener target":"هدف الاستماع",
 "of":"من",
 "ajnas":"الأجناس",
 "sayr":"السير",
 ", characteristic melodic phrases, important resting points, modulation possibilities, ornamentation and a customary melodic course—the":"، وجمل لحنية مميزة، ودرجات ركوز مهمة، وإمكانيات تحويل، وزخارف، ومسار لحني متعارف عليه اسمه",
 "Pause here before changing register or introducing another jins.":"قف هنا قبل ما تغيّر المنطقة أو تدخل جنس تاني.",
 "Root at":"القرار عند",
 "first station at degree":"أول محطة عند الدرجة",
 "Make the lower jins recognizable before the full maqam appears.":"خلّي الجنس السفلي مسموع وواضح قبل ما تظهر المقام كامل.",
 "Reproduce the selected half-flat pitch without looking at the screen.":"كرّر نغمة النصف بيمول المختارة من غير ما تبص للشاشة.",
 "Turn the pitch collection into an audible melodic course.":"حوّل مجموعة النغمات لمسار لحني مسموع.",
 "Make the ghammaz a real station and a doorway to a second jins.":"خلّي الغمّاز محطة حقيقية وباب لجنس تاني.",
 "Change the active jins at a shared pivot without losing pulse or hand orientation.":"غيّر الجنس عند نقطة مشتركة من غير ما تضيّع النبض أو مكان إيدك.",
 "Create a complete solo arc with silence, development, modulation and return.":"اعمل قوس ارتجال كامل فيه سكتات وتطوير وتحويل ورجوع.",
 "Drone at practice root · 56 BPM · one octave below middle C · clean tone":"درون على قرار التمرين · ٥٦ BPM · أوكتاف تحت دو الوسطى · صوت نضيف",
 "Headphones strongly recommended · drone only · no percussion · very light fretting-hand pressure":"السماعات مفضّلة جداً · درون بس · من غير إيقاع · ضغط خفيف جداً بإيد الفريتات",
 "Drone + light Maqsum · 64 BPM · four two-bar phrases":"درون + مقسوم خفيف · ٦٤ BPM · أربع جمل، كل جملة مازورتين",
 "Drone + Wahda · 58 BPM · two-register hand route":"درون + وحدة · ٥٨ BPM · مسار إيد في منطقتين",
 "Drone + Maqsum · 68 BPM · selected FROM → TO route":"درون + مقسوم · ٦٨ BPM · مسار التحويل المختار",
 "Drone + optional Sama‘i Thaqil · start 52 BPM · record the full take":"درون + سماعي ثقيل اختياري · ابدأ ٥٢ BPM · سجّل المحاولة كاملة",
 "Hands off. Hear the drone, sing the tonic, then sing the lower jins.":"شيل إيدك. اسمع الدرون، غنّي القرار، وبعده غنّي الجنس السفلي.",
 "Play four long tonics. Let every note settle before the next attack.":"اعزف أربع قرارات طويلة. سيب كل نغمة تثبت قبل الضربة اللي بعدها.",
 "Play degrees one, two, three, four, then descend. Repeat without speeding up.":"اعزف الدرجات الأولى والتانية والتالتة والرابعة، وبعدين انزل. كرّر من غير ما تسرّع.",
 "Two beats ascending, two beats descending. End every answer on the tonic.":"نبضتين طالع ونبضتين نازل. اقفل كل إجابة على القرار.",
 "One unbroken lower-jins phrase, then hold the tonic for four seconds.":"جملة واحدة متصلة من الجنس السفلي، وبعدها ثبّت القرار أربع ثواني.",
 "Hear tonic, target, tonic. Sing the target before touching the bass.":"اسمع القرار، الهدف، القرار. غنّي الهدف قبل ما تلمس الباص.",
 "Start at the lower fret anchor and bend slowly until the coach says centred.":"ابدأ من الفريت الأقل واعمل بند ببطء لحد ما المدرّب يقول مظبوط.",
 "Mute, reset, then land directly on the target. Leave two seconds of silence between attempts.":"اكتم، جهّز من جديد، وانزل على الهدف مباشرة. سيب ثانيتين سكتة بين المحاولات.",
 "Alternate tonic, microtone, next structural degree, microtone, tonic.":"بدّل بين القرار، ربع الصوت، الدرجة الأساسية اللي بعدها، ربع الصوت، والقرار.",
 "Do not look down. Ten measured attacks; the coach corrects low, high or wrong note.":"ما تبصّش لتحت. عشر ضربات مقاسة؛ المدرّب هيقول واطي أو عالي أو نغمة غلط.",
 "Improvise using only the first four degrees. Repeat one cell until the maqam is clear.":"ارتجل بأول أربع درجات بس. كرّر خلية واحدة لحد ما المقام يبقى واضح.",
 "Climb to the ghammaz and hold it. Do not reveal the octave yet.":"اطلع للغمّاز وثبّته. ما تظهرش الأوكتاف لسه.",
 "Add degrees five through seven as an answer to the original cell.":"ضيف الدرجات من الخامسة للسابعة كإجابة للخلية الأصلية.",
 "Reach the highest note once; descend immediately to the ghammaz.":"وصل لأعلى نغمة مرة واحدة، وانزل فوراً للغمّاز.",
 "Remove upper notes one by one and end with a two-second tonic.":"شيل النغمات العالية واحدة واحدة، واقفل بقرار مدته ثانيتين.",
 "Lower jins to ghammaz, hold, then descend. Repeat four times.":"من الجنس السفلي للغمّاز، ثبّت، وبعدين انزل. كرّر أربع مرات.",
 "Keep the pivot finger as a guide. Release pressure, move the thumb, then place the new position.":"خلّي صباع التحويل كمرشد. ريّح الضغط، حرّك الإبهام، وبعدين حط الإيد في الموضع الجديد.",
 "Begin every upper phrase on the ghammaz and return there after three notes.":"ابدأ كل جملة عالية من الغمّاز وارجع له بعد ثلاث نغمات.",
 "One phrase rises through the bridge; the next descends through it. No isolated scale runs.":"جملة تطلع من خلال الجسر واللي بعدها تنزل من خلاله. من غير جري سلّم منفصل.",
 "Two bars lower, two bars bridge, two bars upper, two bars full return.":"مازورتين تحت، مازورتين جسر، مازورتين فوق، ومازورتين رجوع كامل.",
 "Establish only the source maqam. Make its characteristic degree obvious.":"ثبّت المقام الأصلي بس، وخلّي درجته المميزة واضحة.",
 "Approach the shared station from below and above. Hold it for two beats.":"قرّب للمحطة المشتركة من تحت ومن فوق. ثبّتها نبضتين.",
 "After the pivot, introduce the first pitch that belongs to the destination route.":"بعد نقطة التحويل، دخل أول نغمة بتثبت مسار المقام الجديد.",
 "Answer with the destination lower jins, then cadence to its tonic or back to home.":"جاوب بالجنس السفلي للمقام الجديد، وبعدين اقفل على قراره أو ارجع للقرار الأصلي.",
 "Five uninterrupted eight-bar rounds. The coach counts; you keep both hands on the bass.":"خمس جولات متصلة، كل واحدة ٨ موازير. المدرّب هيعد، وإنت خلّي إيديك على الباص.",
 "Lower register only. State tonic and lower jins with space between phrases.":"المنطقة الواطية بس. وضّح القرار والجنس السفلي، وسيب مساحة بين الجمل.",
 "Choose one three-note motif. Repeat, vary its ending, then leave silence.":"اختار موتيف من ثلاث نغمات. كرّره، غيّر نهايته، وبعدها اسكت.",
 "Move toward the ghammaz. Shift once, slowly, without breaking the pulse.":"اتحرّك ناحية الغمّاز. اعمل نقلة واحدة ببطء من غير ما تكسر النبض.",
 "Reveal the upper jins and one register peak. Do not stay at maximum intensity.":"اظهر الجنس العلوي وقمة واحدة في المنطقة العالية. ما تفضلش على أعلى شدة.",
 "Use the planned pivot. Introduce the destination colour after the held common tone.":"استخدم نقطة التحويل المخططة. دخل لون المقام الجديد بعد ما تثبّت النغمة المشتركة.",
 "Reduce density, descend through the lower jins, and let the final tonic ring.":"قلّل كثافة النغمات، وانزل من خلال الجنس السفلي، وسيب القرار الأخير يرن.",
 "3 rounds: tonic returns within ±15¢; lower jins stays continuous; no pause before the cadence.":"٣ جولات: الرجوع للقرار جوه ±١٥ سنت؛ الجنس السفلي متصل؛ من غير توقف قبل القفلة.",
 "8 of the final 10 attacks centre within ±15¢; no bend overshoot; release returns cleanly to the anchor fret.":"٨ من آخر ١٠ ضربات جوه ±١٥ سنت؛ من غير ما البند يعدّي الهدف؛ والرجوع للفريت الأساسي نضيف.",
 "Lower jins arrives first; ghammaz is emphasized before the upper register; final descent clearly restores home.":"الجنس السفلي يظهر الأول؛ الغمّاز يتأكد قبل المنطقة العالية؛ والنزول الأخير يرجّع القرار بوضوح.",
 "Pivot remains audible through the shift; new jins appears after the pivot; hand movement is silent and rhythm remains intact.":"نقطة التحويل تفضل مسموعة أثناء النقلة؛ الجنس الجديد يظهر بعدها؛ حركة الإيد هادية والإيقاع ثابت.",
 "4 of 5 switches introduce only the planned changed tones; pivot is held; destination maqam resolves intentionally.":"٤ من ٥ تحويلات تدخل النغمات المتغيرة المخططة بس؛ نقطة التحويل ثابتة؛ والمقام الجديد بيقفل بقصد.",
 "Home is clear in minute 1; one motif develops; one planned switch succeeds; final minute unmistakably returns; at least 25% silence.":"القرار واضح في أول دقيقة؛ موتيف واحد بيتطوّر؛ تحويل مخطط ينجح؛ آخر دقيقة ترجع بوضوح؛ وسكوت ٢٥٪ على الأقل.",
 "Keep the pivot finger lightly touching its string. Release pressure, move the thumb with the hand, and place only the destination’s changed degrees. The common tones do not need to be relearned.":"خلّي صباع التحويل لامس الوتر بخفة. ريّح الضغط، وحرّك الإبهام مع الإيد، وحط بس الدرجات اللي اتغيّرت في المقام الجديد. النغمات المشتركة مش محتاجة تتعلّم من الأول.",
 "Warm, vocal and grounded. The half-flat second is the first identity test.":"دافئ وغنائي وثابت. الدرجة التانية نصف بيمول هي أول اختبار حقيقي لهوية البياتي.",
 "Establish the lower Bayati jins, lean on the fourth, reveal the upper jins, then descend through the half-flat second into home.":"ثبّت جنس البياتي السفلي، اركن على الرابعة، اظهر الجنس العلوي، وبعدين انزل من خلال التانية نصف بيمول للقرار.",
 "Do not treat the 150-cent second as an out-of-tune major second. It is a controlled destination whose exact height follows style and teacher.":"ما تعتبرش الدرجة التانية عند ١٥٠ سنت نغمة كبيرة مش مظبوطة. هي هدف متحكّم فيه، ومكانها الدقيق بيتغيّر حسب المدرسة والأستاذ.",
 "Anchor the second one fret above the tonic, then bend it about +50¢. Release the bend before returning to the tonic.":"ابدأ التانية من الفريت اللي فوق القرار بنص تون، وبعدها اعمل بند حوالي +٥٠ سنت. فك البند قبل ما ترجع للقرار.",
 "On fretless bass, hear the second between the minor and major second; arrive from below and check it against the drone.":"على الفريتلس، اسمع التانية بين التانية الصغيرة والكبيرة؛ وصل لها من تحت وراجعها قدّام الدرون.",
 "Stable, open and authoritative. Its half-flat third and seventh keep it distinct from a Western major scale.":"ثابت ومفتوح وواثق. التالتة والسابعة نصف بيمول بيفرّقوه عن السلم الكبير الغربي.",
 "State tonic–second–half-flat third clearly, expand to the fifth, explore the upper jins, then let the half-flat seventh guide the descent.":"وضّح القرار والتانية والتالتة نصف بيمول، وسّع للخامسة، استكشف الجنس العلوي، وبعدها خلّي السابعة نصف بيمول تقود النزول.",
 "A plain major third erases the core Rast colour; a minor third makes the lower jins sound too dark.":"التالتة الكبيرة العادية بتمسح لون الراست؛ والتالتة الصغيرة بتخلّي الجنس السفلي أغمق من اللازم.",
 "Play the lower chromatic anchor for degrees 3 and 7, then bend each roughly +50¢ while the tonic drone continues.":"اعزف الفريت الأقل للدرجتين التالتة والسابعة، واعمل لكل واحدة بند حوالي +٥٠ سنت والدرون مستمر.",
 "Use the drone to place the third and seventh as expressive centres, not fixed equal-tempered compromises.":"استخدم الدرون عشان تحط التالتة والسابعة كمراكز تعبير، مش كحلول ثابتة من الضبط المتساوي.",
 "Focused and high-contrast. The semitone followed by the wide leap must still sing as one connected jins.":"مركّز وتباينه قوي. نص التون وبعده القفزة الواسعة لازم يفضلوا جملة جنس واحدة متصلة.",
 "Circle the first four notes, emphasize the fourth, open the upper register only after Hijaz is unmistakable, then resolve by ♭2–1.":"لف حوالين أول أربع نغمات، ركّز على الرابعة، وما تفتحش المنطقة العالية غير لما الحجاز يبقى واضح، وبعدها اقفل ♭٢–١.",
 "Do not exaggerate the wide step by clipping the ♭2 or attacking the third too hard; sing the whole lower jins as one phrase.":"ما تبالغش في المسافة الواسعة بتقصير ♭٢ أو ضرب التالتة بعنف؛ غنّي الجنس السفلي كله كجملة واحدة.",
 "This is fully available on a standard fretted bass. Keep fingers 1–2 ready for the tight semitone and shift cleanly into the major third.":"الحجاز متاح كامل على باص بفريتات. جهّز الصباعين ١–٢ لنص التون الضيق، وانقل بنضافة للتالتة الكبيرة.",
 "Use small slides and vocal ornaments, but keep the four structural pitches centred.":"استخدم سلايدات صغيرة وزخارف غنائية، بس خلّي الأربع نغمات الأساسية مظبوطة.",
 "Minor-coloured and highly useful for connecting Western ears to maqam phrasing.":"لونه ماينور، ومفيد جداً عشان يوصل الودن الغربية لطريقة جملة المقام.",
 "Build the lower minor jins, rest on the fifth, expose the upper tension, then descend with a clear melodic answer.":"ابنِ الجنس الماينور السفلي، اركن على الخامسة، اظهر التوتر العالي، وبعدين انزل بإجابة لحنية واضحة.",
 "Running harmonic minor evenly does not establish maqam behavior. Give the lower jins time, repetition and cadential weight.":"جري الهارمونيك ماينور بالتساوي مش بيثبّت سلوك المقام. ادّي الجنس السفلي وقت وتكرار ووزن في القفلة.",
 "No microtonal adjustment is required for this teaching form; concentrate on shifts, phrase shape and the raised seventh’s pull.":"الشكل التعليمي ده مش محتاج أرباع صوت؛ ركّز على النقلات وشكل الجملة وجذب السابعة المرفوعة.",
 "Fretless players can shade ornaments around stable pitches without moving the structural targets.":"عازف الفريتلس يقدر يلوّن الزخارف حوالين النغمات الثابتة من غير ما يحرّك الأهداف الأساسية.",
 "Dark and direct. Its first four notes resemble Phrygian, but its melodic treatment and cadences remain the lesson.":"داكن ومباشر. أول أربع نغمات شبه الفريجيان، لكن طريقة الجملة والقفلات هي الدرس الحقيقي.",
 "Make the tonic–♭2 tension audible, answer through ♭3–4, develop near the fourth or fifth, then descend without rushing the cadence.":"خلّي شد القرار مع ♭٢ مسموع، جاوب من خلال ♭٣–٤، طوّر حوالين الرابعة أو الخامسة، وانزل من غير استعجال القفلة.",
 "Do not lean so long on ♭2 that it becomes a new tonic. The root must remain acoustically and rhythmically stronger.":"ما تركنش على ♭٢ لوقت طويل يخليها قرار جديد. القرار الأصلي لازم يفضل أقوى في الصوت والإيقاع.",
 "Fully playable on frets. Use a compact four-fret cell and shift rather than forcing a wide left-hand stretch.":"قابل للعزف بالكامل على الفريتات. استخدم خلية صغيرة في أربع فريتات، وانقل الإيد بدل ما تجبرها على مطّة واسعة.",
 "Use ornaments as phrasing choices, not as substitutes for a stable tonal centre.":"استخدم الزخارف كاختيارات في الجملة، مش كبديل عن قرار ثابت.",
 "Bright and declarative. Familiar pitch material makes it ideal for learning maqam grammar without intonation pressure.":"مشرق وواضح. نغماته المألوفة بتخليه مناسب لتعلّم قواعد المقام من غير ضغط أرباع الصوت.",
 "State the lower Ajam jins as a phrase, pause on the fifth, shape the upper answer, and return with a deliberate cadence.":"قول جنس العجم السفلي كجملة، قف على الخامسة، شكّل الإجابة العالية، وارجع بقفلة مقصودة.",
 "Major-scale fingering alone is not a maqam performance; articulation, repeated cells and destinations must reveal a melodic route.":"صوابع السلم الكبير لوحدها مش أداء مقام؛ النطق والخلايا المتكررة والأهداف لازم يوضحوا مسار لحني.",
 "Fully playable. Use it to perfect hand economy and phrase architecture before adding quarter-tone bends.":"قابل للعزف بالكامل. استخدمه لتحسين اقتصاد حركة الإيد وبناء الجملة قبل ما تضيف بندات أرباع الصوت.",
 "Keep stable centres, then add tasteful slides into the third and tonic.":"ثبّت المراكز الأول، وبعدها ضيف سلايدات بذوق للتالتة والقرار.",
 "Tense, intimate and non-octave-equivalent in important practice. Learn the lower jins before asking for a universal scale formula.":"حساس ومشدود، ومش لازم يبقى متماثل في الأوكتاف. اتعلّم الجنس السفلي قبل ما تدور على تركيبة سلم عامة.",
 "Dwell in the compressed lower tetrachord, emphasize its expressive third, touch the overlapping Hijaz colour, then return without forcing an octave symmetry.":"اتمهّل في التتراكورد السفلي المضغوط، ركّز على تالتته التعبيرية، المس لون الحجاز المتداخل، وارجع من غير ما تفرض تماثل الأوكتاف.",
 "The upper starred notes are only a practice route, not a universal Saba scale. Repertoire, regional style and teacher determine the full path.":"النغمات العالية عليها نجمة مجرد مسار تمرين، مش سلّم صبا عام. الريبرتوار والمدرسة والأستاذ هم اللي بيحددوا الطريق الكامل.",
 "Use the lower chromatic fret as the anchor for the half-flat second and bend +50¢. Keep the next two notes only one semitone apart.":"استخدم الفريت الأقل كنقطة بداية للتانية نصف بيمول واعمل بند +٥٠ سنت. خلّي النغمتين اللي بعدها بينهم نص تون بس.",
 "Map the lower four notes first: 0, 150, 300 and 400 cents. Let the ear lead before extending the route.":"ارسم أول أربع نغمات الأول: ٠ و١٥٠ و٣٠٠ و٤٠٠ سنت. خلّي الودن تقود قبل ما توسّع المسار.",
 "A microtonal tonic changes the entire hand map: the home note itself often sits between equal-tempered frets.":"القرار الميكروتوني بيغيّر خريطة الإيد كلها: نغمة البيت نفسها غالباً بتقع بين فريتين من الضبط المتساوي.",
 "Establish the microtonal tonic repeatedly, make the third or fourth a contrasting station, and prove the tonic again after every expansion.":"ثبّت القرار الميكروتوني أكتر من مرة، خلّي التالتة أو الرابعة محطة مختلفة، واثبت القرار تاني بعد كل توسّع.",
 "Never tune the tonic by eye alone. Its exact intonation varies; use a reference performance, teacher and drone.":"ما تضبطش القرار بعينك لوحدها. مكانه الدقيق بيتغيّر؛ استخدم تسجيل مرجعي وأستاذ ودرون.",
 "Choose the lower adjacent fret and bend the tonic about +50¢, or tune a dedicated string reference. Every return must reproduce the same height.":"اختار الفريت الأقل المجاور واعمل للقرار بند حوالي +٥٠ سنت، أو اضبط وتر كمرجع. كل رجوع لازم يجيب نفس الارتفاع.",
 "On fretless, mark the tonic by ear against a drone and test it after silence. This lab uses E half-flat as the recommended starting centre.":"على الفريتلس، علّم القرار بودنك قدّام الدرون واختبره بعد سكتة. المختبر بيقترح مي نصف بيمول كبداية.",
 "Nahawand or Rast on degree 4":"نهاوند أو راست على الدرجة الرابعة",
 "Rast or Nahawand around degree 5":"راست أو نهاوند حوالين الدرجة الخامسة",
 "Nahawand or Rast above the ghammaz":"نهاوند أو راست فوق الغمّاز",
 "Hijaz or Kurd on degree 5":"حجاز أو كرد على الدرجة الخامسة",
 "Nahawand on degree 4 or 5":"نهاوند على الدرجة الرابعة أو الخامسة",
 "Ajam or Rast above degree 5":"عجم أو راست فوق الدرجة الخامسة",
 "Overlapping Hijaz from degree 3; later routes vary":"حجاز متداخل من الدرجة التالتة؛ المسارات الأعلى بتتغيّر",
 "Rast or Hijaz according to route":"راست أو حجاز حسب المسار",
 "Hold tonic, microtonal colour, ghammaz, tonic. No improvising until every target centres.":"ثبّت القرار، لون ربع الصوت، الغمّاز، والقرار. ما ترتجلش قبل ما كل هدف يبقى مظبوط.",
 "2 bars lower jins · 2 bars bridge · 2 bars upper answer · 2 bars return.":"مازورتين جنس سفلي · مازورتين جسر · مازورتين إجابة عالية · مازورتين رجوع.",
 "Build slowly, leave silence, reach one peak, then make the final return unmistakable.":"ابنِ الجملة براحة، وسيب سكتات، ووصل لقمة واحدة، وبعدها خلّي الرجوع الأخير واضح جداً.",
 "Sayr":"السير",
 "Taqsim arc":"قوس التقسيم",
 "Root drone + fifth · ghammaz cue:":"درون القرار + الخامسة · إشارة الغمّاز:",
 "MICROPHONE REQUIRED · Select your bass/audio-interface input, then start again.":"الميكروفون مطلوب · اختار مدخل الباص أو كارت الصوت، وبعدها ابدأ تاني.",
 "The Inside Foundation":"أساس العزف جوّه الهارموني",
 "Hear and establish home before studying modes.":"اسمع القرار وثبّته قبل ما تدرس المقامات الغربية.",
 "How Modes Work":"المقامات الغربية بتشتغل إزاي",
 "Replace scale-shape thinking with interval environments.":"بدّل تفكير أشكال السلالم بفهم بيئة المسافات.",
 "The Seven Modal Sounds":"أصوات المقامات الغربية السبعة",
 "Build every mode from one root and make its identity audible.":"ابنِ كل مقام من قرار واحد وخلّي هويته مسموعة.",
 "Modal Improvisation":"الارتجال المقامي",
 "Turn mode knowledge into grooves, motifs, fills and phrases.":"حوّل معرفة المقامات لجروفات وموتيفات وفيلز وجمل.",
 "Harmony in Motion":"الهارموني وهو بيتحرّك",
 "Know when to think modally and when to follow chord gravity.":"اعرف إمتى تفكّر بالمقام وإمتى تتبع جذب الكورد.",
 "Controlled Outside Playing":"العزف برّه بتحكّم",
 "Leave the harmony deliberately and return with authority.":"اخرج برّه الهارموني بقصد، وارجع بثقة.",
 "Tonal Centre: What ‘Home’ Means":"القرار: يعني إيه نغمة البيت",
 "Establish a tonal centre so clearly that the listener can hear departure and return.":"ثبّت القرار بوضوح لدرجة إن المستمع يسمع الخروج والرجوع.",
 "Intervals as Musical Functions":"المسافات كوظايف موسيقية",
 "Hear and name every note by its distance and emotional function from the root.":"اسمع وسمّي كل نغمة حسب بعدها ووظيفتها التعبيرية من القرار.",
 "Chord-Tone Hierarchy":"ترتيب أهمية نغمات الكورد",
 "Build lines that state harmony before adding modal colour.":"ابنِ جمل توضّح الهارموني قبل ما تضيف لون المقام.",
 "Rhythmic Weight, Duration & Articulation":"الوزن الإيقاعي والمدة وطريقة النطق",
 "Control how tense a note sounds without changing the pitch itself.":"اتحكّم في توتّر النغمة من غير ما تغيّر النغمة نفسها.",
 "What Modes Actually Are":"المقامات الغربية هي إيه فعلاً",
 "Understand modes as distinct interval environments, not seven positions of one major scale.":"افهم المقامات كبيئات مسافات مختلفة، مش سبع وضعيات لسلم كبير واحد.",
 "Relative Modes vs Same-Root Modes":"المقامات النسبية قدّام نفس القرار",
 "Switch fluently between parent-scale analysis and audible parallel colour.":"بدّل بسلاسة بين تحليل السلم الأم وسماع الألوان على نفس القرار.",
 "Mode Families & the Brightness Spectrum":"عائلات المقامات ودرجة السطوع",
 "Organize modes by chord quality and altered degrees instead of memorizing seven unrelated formulas.":"رتّب المقامات حسب نوع الكورد والدرجات المتغيّرة بدل حفظ سبع تركيبات منفصلة.",
 "Characteristic Tones & Modal Identity":"نغمات اللون وهوية المقام",
 "Make a mode recognizable without ascending or descending the scale.":"خلّي المقام معروف من غير ما تجري السلم طالع ونازل.",
 "Ionian: Major Stability":"أيونيان: ثبات الماجور",
 "Use Ionian as the major reference and control the 4–3 semitone rub.":"استخدم الأيونيان كمرجع للماجور واتحكّم في احتكاك ٤–٣.",
 "Dorian: Minor with a Natural 6":"دوريان: ماينور بسادسة طبيعية",
 "Make Dorian audible through the relationship between ♭3 and natural 6.":"خلّي الدوريان مسموع من العلاقة بين ♭٣ والسادسة الطبيعية.",
 "Phrygian: Minor with a ♭2":"فريجيان: ماينور بتانية بيمول",
 "Control the extreme root–♭2 tension without losing the minor tonal centre.":"اتحكّم في شد القرار مع ♭٢ من غير ما تضيّع مركز الماينور.",
 "Lydian: Major with a ♯4":"ليديان: ماجور برابعة دييز",
 "Use ♯4 to create Lydian lift while keeping major harmony stable.":"استخدم ♯٤ عشان تعمل رفعة الليديان مع ثبات هارموني الماجور.",
 "Mixolydian: Major with a ♭7":"ميكسوليديان: ماجور بسابعة بيمول",
 "Hear dominant colour as stable modal identity and as potential functional tension.":"اسمع لون الدومينانت كهوية مقام ثابتة وكمان كتوتر وظيفي محتمل.",
 "Aeolian: Natural Minor":"إيوليان: الماينور الطبيعي",
 "Use ♭6 as Aeolian identity while separating it from Dorian and Phrygian.":"استخدم ♭٦ كهوية للإيوليان وفرّقه عن الدوريان والفريجيان.",
 "Locrian: Minor with a ♭5":"لوكريان: ماينور بخامسة بيمول",
 "Hear Locrian as m7♭5 harmony rather than an unstable scale exercise.":"اسمع اللوكريان كهارموني m7♭5 مش كتمرين سلم غير ثابت.",
 "Constructing a Modal Bass Groove":"بناء جروف باص مقامي",
 "Build a groove in layers so rhythm and harmonic identity develop together.":"ابنِ الجروف طبقات عشان الإيقاع وهوية الهارموني يتطوّروا سوا.",
 "Scarcity: Four-Note Improvisation":"الاقتصاد: ارتجال بأربع نغمات",
 "Create compelling modal phrases without hiding behind the full scale.":"اعمل جمل مقامية قوية من غير ما تستخبّى ورا السلم كامل.",
 "Motif Development":"تطوير الموتيف",
 "Build a solo from one recognizable idea rather than unrelated licks.":"ابنِ السولو من فكرة واحدة معروفة بدل جمل ملهاش علاقة ببعض.",
 "Modal Fills & Target Landings":"الفيلز المقامية والوصول للأهداف",
 "Leave the groove briefly and return on time to a harmonically meaningful target.":"سيب الجروف لحظة وارجع في الوقت على هدف له معنى هارموني.",
 "Ear-to-Fretboard Integration":"ربط الودن بلوحة الباص",
 "Convert heard modal function into immediate movement anywhere on the bass.":"حوّل الوظيفة اللي سمعتها لحركة فورية في أي مكان على الباص.",
 "Static Modal Harmony":"هارموني مقامي ثابت",
 "Develop musical material over one chord without treating the mode as a scale exercise.":"طوّر مادة موسيقية فوق كورد واحد من غير ما تحوّل المقام لتمرين سلم.",
 "Chords Inside a Mode":"الكوردات جوّه المقام",
 "Navigate modes as triads and seventh chords instead of continuous scales.":"اتحرّك في المقام كترايادات وكوردات سابعة بدل سلالم مستمرة.",
 "Modal, Functional or Hybrid?":"مقامي ولا وظيفي ولا خليط؟",
 "Choose the correct improvisational mental model before playing.":"اختار طريقة التفكير الصح للارتجال قبل ما تعزف.",
 "Voice Leading Through Changes":"حركة الأصوات مع تغيّر الكوردات",
 "Connect chords through the nearest meaningful destination rather than random scale travel.":"وصّل الكوردات لأقرب هدف له معنى بدل الحركة العشوائية في السلم.",
 "Chromatic Approaches":"الاقترابات الكروماتيك",
 "Use outside notes as directed motion into chord tones.":"استخدم النغمات البرّه كحركة موجهة لنغمات الكورد.",
 "Enclosures & Chromatic Connectors":"الإحاطات والوصلات الكروماتيك",
 "Surround structural tones and connect stable notes through deliberate chromatic pathways.":"حاوط النغمات الأساسية ووصل الثابتة بمسارات كروماتيك مقصودة.",
 "Side-Slipping & Outside Motifs":"السايد-سليب والموتيفات البرّه",
 "Move an entire recognizable idea outside the key and return without losing the listener.":"حرّك فكرة كاملة معروفة برّه المفتاح وارجع من غير ما تضيّع المستمع.",
 "Tension Architecture Capstone":"مشروع بناء التوتّر النهائي",
 "Improvise with an intentional long-form arc from home through tension and back.":"ارتجل بقوس طويل مقصود من القرار للتوتّر وللرجوع.",
};

const DETAIL_EXACT:Record<string,string>={
 "MOVE ON WHEN":"كمّل لما",
 "WHY THIS DRILL":"ليه التمرين ده",
 "BEFORE START":"قبل ما تبدأ",
 "COUNT ALOUD":"عُدّ بصوت عالي",
 "FRETTING-HAND JOB":"مهمة إيد الفريتات",
 "REPAIR WITHOUT RESTARTING":"صلّح من غير ما تبدأ من الأول",
 "PASS EVIDENCE":"دليل النجاح",
 "COUNT THE FORM":"عُدّ الفورمة",
 "THEN CONTINUE":"وبعدين كمّل",
 "CURRENT STEP":"الخطوة الحالية",
 "NEXT":"اللي بعده",
 "CONTINUE TO":"كمّل لحد",
 "RETURN TO PATH":"ارجع للمسار",
 "RETURN TO EXPLORE":"ارجع للفهم",
 "NEXT ·":"اللي بعده ·",
 "CURRENT STEP ·":"الخطوة الحالية ·",
 "MINUTE LESSON":"درس بالدقايق",
 "01 · PREPARE":"٠١ · جهّز",
 "02 · ATTEMPT":"٠٢ · جرّب",
 "03 · CHECK":"٠٣ · راجع",
 "04 · IF IT FAILS":"٠٤ · لو ما نجحش",
 "05 · REPAIR HERE":"٠٥ · صلّح من هنا",
 "06 · PASS EVIDENCE":"٠٦ · دليل النجاح",
 "The timing now matches this":"الوقت دلوقتي مطابق لمدة الدرس:",
 "Finish each exit condition before moving on; if it fails, repair only that block.":"خلّص شرط الخروج من كل جزء قبل ما تنقل؛ لو ما نجحش، صلّح الجزء ده بس.",
 "Read the core idea, name every term and explain the essential contrast in your own words.":"اقرا الفكرة الأساسية، وسمّي كل مصطلح، واشرح الفرق المهم بكلامك.",
 "You can teach the idea aloud without reading and give one correct example plus one common failure.":"تقدر تشرح الفكرة بصوت عالي من غير قراية، وتدي مثال صح وغلطة شائعة.",
 "Hear, imagine and sing the defining function before you find it on the bass.":"اسمع وتخيّل وغنّي الوظيفة المميّزة قبل ما تدور عليها على الباص.",
 "You can predict the colour, identify it in an A/B contrast and sing its return to home.":"تقدر تتوقّع اللون، وتميّزه في مقارنة A/B، وتغنّي رجوعه للقرار.",
 "Map two neck regions, then complete the written setup, task, dose and tempo ladder.":"ارسم منطقتين على الرقبة، وبعدها نفّذ التجهيز والمطلوب والجرعة وسلّم السرعة المكتوبين.",
 "You earn three consecutive clean passes in two distant keys with time, touch and target intact.":"تجيب ٣ نجاحات نضيفة ورا بعض في مفتاحين بعيدين، والوقت واللمسة والهدف ثابتين.",
 "Record the application mission as one uninterrupted take and score the stated evidence.":"سجّل مهمة التطبيق في تيك واحد من غير قطع، وقيّم الدليل المطلوب.",
 "The take reaches 80/100, no category is below 70, and you can name the intended target and resolution.":"التيك يجيب ٨٠/١٠٠، ومفيش بند أقل من ٧٠، وتقدر تسمّي الهدف والقفلة المقصودين.",
 "Choose the first level whose outcome you cannot yet prove cleanly.":"اختار أول مستوى لسه مش قادر تثبت نتيجته بنضافة.",
 "One current level and drill are selected; start at its printed tempo.":"مستوى وتمرين واحد متحددين؛ ابدأ من السرعة المكتوبة.",
 "Learn the movement, counting and muting jobs before chasing speed.":"اتعلّم الحركة والعدّ ومهام الكتم قبل ما تجري ورا السرعة.",
 "Three consecutive rounds meet the drill’s sound, time and body standard.":"٣ جولات ورا بعض يحققوا معيار الصوت والوقت والجسم بتاع التمرين.",
 "Repeat the drill hands-free while the coach manages time and transitions.":"كرّر التمرين من غير لمس الشاشة والمدرّب يدير الوقت والانتقالات.",
 "The full selected routine finishes without an uncorrected timing or tension problem.":"الروتين المختار يخلص كله من غير مشكلة توقيت أو شدّ متسابِة من غير تصحيح.",
 "Keep the subdivision alive when the click disappears and the phrase has space.":"خلّي التقسيم الداخلي شغّال لما الكليك يختفي والجملة فيها سكتات.",
 "The returning click lands with you for three silent-bar cycles.":"الكليك يرجع راكب معاك في ٣ دورات مازورة ساكتة.",
 "Save one unedited musical take and judge the evidence, not the difficulty.":"احفظ تيك موسيقي واحد من غير مونتاج، واحكم على الدليل مش على صعوبة الحركة.",
 "Score at least 80/100 with no weak category and log the clean day.":"جيب على الأقل ٨٠/١٠٠ من غير بند ضعيف، وسجّل اليوم النضيف.",
 "Proof completes the loop. Return to Path, select the earliest weak outcome and repeat from there.":"الإثبات بيكمّل الدايرة. ارجع للمسار، اختار أول نتيجة ضعيفة، وكرّر من هناك.",
 "Hear the identity and understand its ajnas, stations and sayr.":"اسمع الهوية وافهم الأجناس والمحطات والسير.",
 "Sing the tonic and lower jins, then name the ghammaz and the main mistake to avoid.":"غنّي القرار والجنس السفلي، وبعدها سمّي الغمّاز وأهم غلطة لازم تتجنبها.",
 "Turn the sound into one safe hand route and one deliberate shift.":"حوّل الصوت لمسار إيد آمن ونقلة واحدة مقصودة.",
 "Play the route up and down twice with centred targets, silent shifts and a relaxed thumb.":"اعزف المسار طالع ونازل مرتين بأهداف مظبوطة ونقلات هادية وإبهام مرتاح.",
 "Use a timed routine to make intonation and melodic order repeatable.":"استخدم روتين بوقت عشان ضبط النغم وترتيب الجملة يبقوا قابلين للتكرار.",
 "Complete the chosen routine’s printed pass condition without touching the screen.":"كمّل شرط نجاح الروتين المختار من غير ما تلمس الشاشة.",
 "Hold a shared station and introduce only the destination evidence.":"ثبّت محطة مشتركة، ودخّل دليل المقام الجديد بس.",
 "Four of five switches preserve pulse, pivot and a convincing destination cadence.":"٤ من ٥ تحويلات يحافظوا على النبض ونقطة التحويل وقفلة مقنعة للمقام الجديد.",
 "Place the learned route inside iqa‘, form, space and a full musical return.":"حط المسار اللي اتعلّمته جوّه الإيقاع والفورمة والسكتة ورجوع موسيقي كامل.",
 "The returning tonic is unmistakable after a complete 4-, 8- or 16-bar form.":"القرار الراجع يبقى واضح من غير لخبطة بعد فورمة كاملة ٤ أو ٨ أو ١٦ مازورة.",
 "The route is complete. Return to Explore with a new maqam or root and repeat the same evidence chain.":"المسار خلص. ارجع للفهم بمقام أو قرار جديد وكرّر نفس سلسلة الإثبات.",
 "AJNAS + SAYR → HAND ROUTE → PRACTICE → MODULATION → MUSIC":"أجناس + سير ← مسار الإيد ← تمرين ← تحويل ← موسيقى",
 "Build one relaxed thumb stroke that produces a clear note and immediately returns to a ready position. Everything later depends on this rebound and the silence around it.":"ابني ضربة إبهام مرتاحة تطلع نغمة واضحة وترجع فوراً لوضع الاستعداد. كل اللي بعد كده معتمد على الارتداد ده وعلى السكتة حواليه.",
 "Tune E and A. Use a clean amplified tone at comfortable volume, sit or stand with the bass stable, set the click to 48 BPM and make every string silent before the first count-in.":"اضبط وتري E وA. استخدم صوت نضيف ومكبّر على مستوى مريح، ثبّت الباص وإنت قاعد أو واقف، حط الكليك على ٤٨ BPM، واكتم كل الأوتار قبل العدّ الأول.",
 "Say ‘1, 2, 3, 4’ aloud. Strike one quarter note on each number for eight bars; use E for two bars, A for two bars, and repeat without adding fills.":"قول ١، ٢، ٣، ٤ بصوت عالي. اضرب نوار على كل رقم لمدة ٨ موازير؛ وتر E مازورتين وA مازورتين، وكرّر من غير فيلات.",
 "Lay relaxed fretting fingers across the unused strings without pressing a fret. After each thumb hit, release enough pressure to stop the note while preserving contact.":"حط صوابع إيد الفريتات مرتاحة على الأوتار اللي مش بتعزفها من غير ما تدوس فريت. بعد كل ضربة إبهام ريّح الضغط كفاية توقف النغمة مع استمرار اللمس.",
 "A compact E or A attack, nearly equal loudness on both strings, a centred beat and true silence between hits. The next click should never be covered by ringing.":"ضربة قصيرة ومركّزة على E أو A، مستوى الصوت شبه متساوي على الوترين، النبضة في مكانها، وسكوت حقيقي بين الضربات. رنين النغمة ما يغطيش الكليك اللي بعده.",
 "The thumb stays buried, the shoulder rises, D/G ring sympathetically, or a louder attack arrives early. Loudness is not a pass if rebound or silence disappears.":"الإبهام يفضل مدفون، الكتف يطلع، وتري D/G يرنّوا، أو الضربة الأعلى تيجي بدري. الصوت العالي مش نجاح لو الارتداد أو السكتة اختفوا.",
 "Pause only the failed four-beat cell. Shake out the arm, perform eight silent key-turn rotations against a muted string, drop 6 BPM, then resume at the beginning of that cell—not the whole exercise.":"وقّف خلية الأربع نبضات اللي فشلت بس. ريّح الدراع، اعمل ٨ لفّات صامتة كأنك بتلف مفتاح على وتر مكتوم، انزل ٦ BPM، وارجع من أول الخلية دي مش من أول التمرين.",
 "Three consecutive 16-bar rounds: every attack on the quarter-note grid, peak spread under 6 dB, unused strings silent and the thumb loose immediately after every hit.":"٣ جولات من ١٦ مازورة ورا بعض: كل ضربة على شبكة النوار، فرق القمم أقل من ٦ dB، الأوتار غير المستخدمة ساكتة، والإبهام مرتاح فوراً بعد كل ضربة.",
 "Load this drill into the auto routine. After clean passes on three separate days, begin Root–octave handshake at its printed start tempo.":"حمّل التمرين في الروتين التلقائي. بعد نجاح نضيف في ٣ أيام مختلفة، ابدأ حوار القرار والأوكتاف على سرعة البداية المكتوبة.",
 "Coordinate thumb and pop as one conversation while keeping their timing and volume matched. The octave must answer the root, not overpower it.":"نسّق الإبهام والشدّة كأنهم حوار واحد، وخلي توقيتهم ومستوى صوتهم متساويين. الأوكتاف يجاوب القرار مش يغطي عليه.",
 "Tune, warm up eight rebound notes, select A at E-string fret 5 and its octave at G-string fret 7, then verify both pitches with ordinary fingerstyle before slapping.":"اضبط الباص، سخّن بـ٨ نغمات ارتداد، اختار A على وتر E فريت ٥ وأوكتافه على وتر G فريت ٧، وراجع النغمتين بفينجرستايل عادي قبل السلاب.",
 "Count ‘1 & 2 & 3 & 4 &’. Place T on 1, P on 2, T on 3, P on 4 for eight bars; only then add the second written bar T T · P.":"عُدّ ١ و٢ و٣ و٤ و. حط T على ١ وP على ٢ وT على ٣ وP على ٤ لمدة ٨ موازير؛ بعدها بس ضيف المازورة التانية المكتوبة T T · P.",
 "Index holds the root and releases pressure after its attack; little finger reaches the octave without collapsing the wrist. Both fingers remain in light contact to stop the previous note.":"السبابة تمسك القرار وتريّح الضغط بعد ضربته؛ الخنصر يوصل للأوكتاف من غير ما الرسغ يقع. الصباعين يفضلوا بلمسة خفيفة عشان يوقفوا النغمة اللي فاتت.",
 "The pop sits on the same eighth-note grid as the thumb and no more than 4 dB louder. Root and octave should read as one pitch identity in two registers.":"الشدّة تقعد على نفس شبكة الثُمن زي الإبهام، وما تبقاش أعلى منه بأكتر من ٤ dB. القرار والأوكتاف لازم يتسمعوا كهوية نغمة واحدة في منطقتين.",
 "The G string is pulled too far, the octave arrives early, the root rings under the pop, or the little-finger reach twists the wrist.":"وتر G بيتشد بعيد، الأوكتاف ييجي بدري، القرار يرن تحت الشدّة، أو مطّة الخنصر تلف الرسغ.",
 "Return to one bar of alternating muted thumb/pop motions, then four bars of root–rest–octave–rest at 6 BPM below the miss. Rejoin at the start of the current two-bar cell.":"ارجع لمازورة واحدة إبهام/شدّة بالتبادل على أوتار مكتومة، وبعدها ٤ موازير قرار–سكتة–أوكتاف–سكتة بسرعة أقل ٦ BPM من الغلطة. ارجع من أول خلية المازورتين الحالية.",
 "Three consecutive 16-bar rounds with correct A targets, even eighths, matched dynamics, clean note endings and a neutral wrist.":"٣ جولات ١٦ مازورة ورا بعض بأهداف A صح، أثمان متساوية، ديناميكس متطابقة، نهايات نغمات نضيفة ورسغ محايد.",
 "Use the auto routine to alternate mechanic and pocket blocks; then test the same octave relationship in E and D before entering the ghost grid.":"استخدم الروتين التلقائي عشان تبدّل بين الحركة والجروف؛ وبعدها اختبر نفس علاقة الأوكتاف في E وD قبل شبكة النغمات المكتومة.",
 "Own the sixteenth-note grid without turning every subdivision into a pitched note. Ghosts should support pocket and make the sounding root feel intentional.":"اتحكّم في شبكة الستاشر من غير ما تحوّل كل تقسيمة لنغمة. النغمات المكتومة تسند الجروف وتخلي القرار المسموع مقصود.",
 "Mute all four strings with the fretting hand, set 58 BPM and produce eight short unpitched clicks. Add the A root only after every click is dry and equal.":"اكتم الأربع أوتار بإيد الفريتات، حط ٥٨ BPM واطلع ٨ كليكات قصيرة من غير نغمة. ضيف قرار A بس بعد ما كل كليك يبقى ناشف ومتساوي.",
 "Say ‘1-e-&-a, 2-e-&-a, 3-e-&-a, 4-e-&-a’ continuously. Speak louder on the written T locations but do not change hand speed.":"قول ١-إي-و-آ، ٢-إي-و-آ، ٣-إي-و-آ، ٤-إي-و-آ باستمرار. علّي صوتك عند أماكن T المكتوبة من غير ما تغيّر سرعة الإيد.",
 "For x, distribute two or three fingers lightly across the strings so no harmonic speaks. For T, press only the A root, then immediately return to the full mute.":"عند x وزّع صباعين أو تلاتة بخفة على الأوتار عشان مفيش هارمونيك ينطق. عند T دوس قرار A بس، وارجع فوراً للكتم الكامل.",
 "One continuous subdivision with short, low-energy ghosts and a clearly pitched A only on T. Space must sound designed, not like missing notes.":"تقسيم مستمر واحد بنغمات مكتومة قصيرة وهادية، وA واضحة بس عند T. السكتة لازم تبان متصممة مش نغمات ناقصة.",
 "A ghost produces a pitch or harmonic, the sounding note gets much louder, the hand stops during rests, or the pattern rushes after beat 1.":"النغمة المكتومة تطلع نغمة أو هارمونيك، النغمة المسموعة تعلى زيادة، الإيد تقف وقت السكتات، أو الباترن يجري بعد النبضة ١.",
 "Loop only one beat: speak it, tap it on the body, play it fully muted, then restore the single sounding T. Earn three clean one-beat loops before rejoining the bar.":"لف نبضة واحدة بس: قولها، خبطها على جسم الباص، اعزفها كلها مكتومة، وبعدها رجّع T المسموعة الوحيدة. اعمل ٣ لوبات نبضة واحدة نضاف قبل ما ترجع للمازورة.",
 "Three consecutive 24-bar rounds with stable onset spacing, every x unpitched, every T detected as A and normal breathing throughout.":"٣ جولات ٢٤ مازورة ورا بعض بمسافات ضربات ثابتة، كل x من غير نغمة، كل T متسجلة A، والنَفَس طبيعي طول الوقت.",
 "Run the mute-every-fourth-bar test. When the click returns with you three times, use the same ghost placement inside One-groove construction.":"اعمل اختبار كتم كل رابع مازورة. لما الكليك يرجع راكب معاك ٣ مرات، استخدم نفس أماكن النغمات المكتومة جوّه تمرين بناء جروف واحد.",
 "Learn to add vocabulary without allowing the newest device to damage the original groove. The skeleton remains the reference at every layer.":"اتعلّم تضيف مفردات من غير ما أحدث حركة تبوّظ الجروف الأصلي. الهيكل يفضل المرجع في كل طبقة.",
 "Record or memorize the plain two-bar A-root skeleton. Clap it once, play it fingerstyle once, then slap it for four bars before adding any ghost, hammer or octave.":"سجّل أو احفظ هيكل قرار A البسيط من مازورتين. سقّف له مرة، اعزفه فينجرستايل مرة، وبعدها سلاب ٤ موازير قبل أي مكتوم أو هامر أو أوكتاف.",
 "Count all sixteenths. Use four passes: skeleton only; add one x; add the 5→7 hammer; add the octave answer. Stay on each pass for eight bars.":"عُدّ كل الستاشر. اعمل ٤ مراحل: الهيكل بس؛ ضيف x واحدة؛ ضيف هامر ٥←٧؛ ضيف إجابة الأوكتاف. اقعد ٨ موازير على كل مرحلة.",
 "Keep the root finger ready, hammer close behind fret 7 without a new thumb attack, release pressure during the position change and mute every unused string before the octave pop.":"خلّي صباع القرار جاهز، اعمل الهامر قريب ورا فريت ٧ من غير ضربة إبهام جديدة، ريّح الضغط وقت نقل الموضع، واكتم كل وتر مش مستخدم قبل شدّة الأوكتاف.",
 "Bar 1 remains unmistakable after every layer. The hammer speaks clearly, the ghost is shorter than pitched notes and the downbeat never shifts.":"المازورة ١ تفضل واضحة بعد كل طبقة. الهامر ينطق بوضوح، المكتوم أقصر من النغمات، وأول نبضة ما تتحركش.",
 "The groove changes when a layer enters, the hammer requires a hidden re-attack, the shift squeaks, or added notes make the phrase continuously busy.":"الجروف يتغيّر لما طبقة تدخل، الهامر يحتاج ضربة مخفية، النقلة تزيّق، أو النغمات الزيادة تخلي الجملة زحمة طول الوقت.",
 "Remove only the newest layer. Play the previous version for three clean loops, isolate the new motion for four slow reps, then restore it at 8 BPM below the miss.":"شيل أحدث طبقة بس. اعزف النسخة اللي قبلها ٣ لوبات نضاف، اعزل الحركة الجديدة ٤ تكرارات بطيئة، وبعدها رجّعها بسرعة أقل ٨ BPM من الغلطة.",
 "Three consecutive 32-bar builds with a stable downbeat, accurate targets, silent shifts and no timing or dynamic degradation at any layer.":"٣ بناءات من ٣٢ مازورة ورا بعض بأول نبضة ثابتة، أهداف دقيقة، نقلات هادية، ومن غير تدهور في الوقت أو الديناميكس في أي طبقة.",
 "Transfer the unchanged rhythm through the four printed articulations. If the cell stays recognizable, continue to Double-thumb pendulum.":"انقل نفس الإيقاع من غير تغيير خلال الأربع طرق نطق المكتوبة. لو الخلية فضلت معروفة، كمّل لبندول الإبهام المزدوج.",
 "Turn thumb down and up into one economical pendulum so speed comes from continuous motion rather than extra force.":"حوّل ضربة الإبهام لتحت ولفوق لبندول اقتصادي واحد، عشان السرعة تيجي من حركة مستمرة مش قوة زيادة.",
 "Trim or protect any catching nail edge, warm up relaxed rebounds, mute the A string and rehearse 16 silent down/up rotations before sounding it at 44 BPM.":"سوّي أو احمي أي طرف ضافر بيعلق، سخّن بارتدادات مرتاحة، اكتم وتر A ودرّب ١٦ لفة لتحت/لفوق صامتة قبل ما تطلع صوته على ٤٤ BPM.",
 "Count ‘1 & 2 & 3 & 4 &’. Downstrokes land on numbers and upstrokes on &. Do not begin the fretted 5–7–8–7 route until open A is even for three bars.":"عُدّ ١ و٢ و٣ و٤ و. الضربات لتحت على الأرقام واللي لفوق على و. ما تبدأش مسار الفريتات ٥–٧–٨–٧ قبل ما A المفتوحة تبقى متساوية ٣ موازير.",
 "On the open-string stage, mute all other strings and stop A after each pair. On the fretted route, keep fingers close, release between notes and never let the left hand pull the tempo.":"في مرحلة الوتر المفتوح، اكتم باقي الأوتار ووقّف A بعد كل زوج. في مسار الفريتات، خلّي الصوابع قريبة وريّح بين النغمات وما تخلّيش الإيد الشمال تشد السرعة.",
 "Down and up sound like one player: equal spacing, same A target, peak difference under 3 dB and no scraped or accidental middle onset.":"الضربة لتحت ولفوق يتسمعوا كعازف واحد: مسافات متساوية، نفس هدف A، فرق القمم أقل من ٣ dB، ومن غير حكّة أو ضربة زيادة في النص.",
 "Two separate wrist actions appear, the upstroke snags, the downstroke is louder, the forearm hardens, or the fretting pattern causes a rush.":"تظهر حركتين منفصلتين للرسغ، الضربة لفوق تعلق، اللي لتحت تعلى، الساعد يشد، أو باترن الفريتات يسبب جري.",
 "Stop at the failed stroke pair. Rehearse eight silent pendulums, play four pairs on a muted string, then four open-A pairs at 8 BPM less before returning to that pair.":"قف عند زوج الضربات اللي فشل. درّب ٨ بندولات صامتة، اعزف ٤ أزواج على وتر مكتوم، وبعدها ٤ أزواج A مفتوحة بسرعة أقل ٨ BPM قبل ما ترجع للزوج ده.",
 "Three consecutive 24-bar rounds of even eighths with matched stroke volume, no extra onset, comfortable nail contact and a loose forearm.":"٣ جولات ٢٤ مازورة ورا بعض بأثمان متساوية، صوت الضربتين متطابق، من غير ضربة زيادة، ملامسة ضافر مريحة وساعد سايب.",
 "Replace only beat 4 of a familiar groove with one down/up pair. Preserve the groove before beginning the four-stroke cell.":"بدّل النبضة ٤ بس في جروف معروف بزوج لتحت/لفوق واحد. حافظ على الجروف قبل ما تبدأ خلية الأربع ضربات.",
 "Coordinate thumb down, thumb up, index pop and middle pop as one evenly spaced circular cell while accents move independently of speed.":"نسّق إبهام لتحت وإبهام لفوق وشدّة سبابة وشدّة وسطى كخلية دائرية واحدة متساوية، والنبرات تتحرك مستقلة عن السرعة.",
 "At 40 BPM, mute the strings and perform the four motions silently. Check that both popping fingers hook from the same shallow depth and the thumb remains close to the A string.":"على ٤٠ BPM اكتم الأوتار واعمل الأربع حركات بصمت. راجع إن صباعين الشدّة بيمسكوا من نفس العمق الصغير، والإبهام يفضل قريب من وتر A.",
 "Say ‘1-e-&-a’. Assign T↓ to 1, T↑ to e, P1 to &, P2 to a. Rotate the accent to the second, third and fourth syllable on later bars without changing spacing.":"قول ١-إي-و-آ. حط T↓ على ١ وT↑ على إي وP1 على و وP2 على آ. لف النبرة للمقطع التاني والتالت والرابع في الموازير اللي بعدها من غير تغيير المسافات.",
 "Hold the A root only for the two thumb attacks, prepare the octave A and C on G string, then release each pitch immediately so the four events never overlap.":"امسك قرار A وقت ضربتي الإبهام بس، جهّز أوكتاف A وC على وتر G، وبعدها ريّح كل نغمة فوراً عشان الأربع أحداث ما يركبوش على بعض.",
 "Four equal subdivisions with the A–A–A–C contour intact. The chosen accent is audible once per bar without dragging the following attack forward.":"أربع تقسيمات متساوية ومسار A–A–A–C سليم. النبرة المختارة تتسمع مرة في كل مازورة من غير ما تسحب الضربة اللي بعدها لقدام.",
 "The two pops bunch together, the accent becomes extra speed, the thumb freezes while fingers pop, or wide string pulls create volume spikes.":"الشدّتين يزحموا بعض، النبرة تتحول لسرعة زيادة، الإبهام يتجمّد وقت الشدّ، أو سحب الوتر بعيد يعمل قفزات في الصوت.",
 "Freeze pitch. Clap and speak the rotating accent for one bar, play the entire cell muted for three clean cycles, then restore A–A–A–C at 8 BPM below the miss.":"جمّد النغمات. سقّف وقول النبرة المتحركة مازورة، اعزف الخلية كلها مكتومة ٣ دورات نضيفة، وبعدها رجّع A–A–A–C بسرعة أقل ٨ BPM من الغلطة.",
 "Three consecutive 32-bar rounds with equal onset spacing, correct contour, four successful accent locations, no hand collision and matched pop depth.":"٣ جولات ٣٢ مازورة ورا بعض بمسافات ضربات متساوية، مسار صح، أربع أماكن نبرة ناجحة، من غير خبط إيدين وعمق شدّة متطابق.",
 "Use the cell once in a two-bar groove and answer with two beats of silence. Only then add it to the automatic routine.":"استخدم الخلية مرة في جروف مازورتين، وجاوب بنبضتين سكوت. بعدها بس ضيفها للروتين التلقائي.",
 "Make one plucking-hand attack generate a clear open–hammer phrase, then answer with a controlled pop. This develops economy and conversation rather than note density.":"خلّي ضربة واحدة من إيد العزف تطلع جملة مفتوح–هامر واضحة، وبعدها جاوب بشدّة متحكّم فيها. ده بيطوّر الاقتصاد والحوار مش زحمة النغمات.",
 "Verify open A, C at A-string fret 3 and C at G-string fret 5 with separate attacks. Set 50 BPM, mute after every note, then practise the hammer alone until it speaks.":"راجع A المفتوحة وC على وتر A فريت ٣ وC على وتر G فريت ٥ بضربات منفصلة. حط ٥٠ BPM، اكتم بعد كل نغمة، وبعدها درّب الهامر لوحده لحد ما ينطق.",
 "Count ‘1-e-&-a’. Open lands on 1, hammer on e, pop on &, rest on a. For the second bar, keep the printed O · H P placement and count through the empty subdivision.":"عُدّ ١-إي-و-آ. المفتوح على ١، الهامر على إي، الشدّة على و، والسكتة على آ. في المازورة التانية حافظ على مكان O · H P المكتوب وعُدّ خلال التقسيمة الفاضية.",
 "Hammer close behind fret 3 with a curved finger and no thumb re-attack. Keep a spare finger touching unused strings; release the open string before the next phrase.":"اعمل الهامر قريب ورا فريت ٣ بصباع مقوّس ومن غير ضربة إبهام تانية. خلّي صباع فاضي لامس الأوتار غير المستخدمة، ووقّف الوتر المفتوح قبل الجملة اللي بعدها.",
 "Three intended pitches, a hammer clearly above the noise floor, stable subdivisions and a final pop that answers rather than shouts.":"تلات نغمات مقصودة، هامر واضح فوق مستوى الدوشة، تقسيمات ثابتة، وشدّة أخيرة بتجاوب مش بتزعق.",
 "The hammer is inaudible, a hidden thumb attack replaces it, the open string overlaps the phrase, or the pop arrives early after the fretting effort.":"الهامر مش مسموع، ضربة إبهام مخفية تاخد مكانه، الوتر المفتوح يركب على الجملة، أو الشدّة تيجي بدري بعد مجهود إيد الفريتات.",
 "Isolate the failed link only: open→hammer or hammer→pop. Play it four times at half-note speed, reconnect one subdivision at a time, then resume from the current two-bar phrase.":"اعزل الوصلة اللي فشلت بس: مفتوح←هامر أو هامر←شدّة. اعزفها ٤ مرات بسرعة نص النغمة، وصّل تقسيمة واحدة كل مرة، وبعدها ارجع من جملة المازورتين الحالية.",
 "Three consecutive 32-bar rounds with all three pitches detected, no secret re-attack, clean open-string stopping and unchanged pulse across transpositions.":"٣ جولات ٣٢ مازورة ورا بعض والتلات نغمات متسجلين، من غير ضربة سرية، إيقاف نضيف للوتر المفتوح، والنبض ثابت مع النقل.",
 "Create the 16-bar call–answer–return using this device only twice. When the original pocket returns clearly, attempt the five-minute proof.":"اعمل فورمة نداء–جواب–رجوع من ١٦ مازورة، واستخدم الحركة دي مرتين بس. لما الجروف الأصلي يرجع بوضوح، جرّب إثبات الخمس دقايق.",
 "Prove that the complete slap vocabulary can shape a musical story while time, dynamics, space and a recognizable home groove remain in control.":"اثبت إن مفردات السلاب الكاملة تقدر تشكّل حكاية موسيقية مع تحكّم في الوقت والديناميكس والسكتة وجروف قرار معروف.",
 "Choose one key, five pitches, three devices and one two-bar home groove. Record 20 seconds of the plain groove first; this is the reference you must restore at the end.":"اختار مفتاح واحد وخمس نغمات وتلات حركات وجروف قرار من مازورتين. سجّل ٢٠ ثانية من الجروف البسيط الأول؛ ده المرجع اللي لازم ترجّعه في الآخر.",
 "Count the form, not every note: 16 bars establish, 16 converse, 16 develop, 16 reach one peak, 16 return. Announce each section before the take and never restart.":"عُدّ الفورمة مش كل نغمة: ١٦ مازورة تثبيت، ١٦ حوار، ١٦ تطوير، ١٦ لقمة واحدة، ١٦ رجوع. قول اسم كل جزء قبل التيك وما تبدأش من الأول.",
 "Use the same muting, release and relaxed-shift standards from earlier levels. Technique is disqualified if the body tightens or open strings obscure the form.":"استخدم نفس معايير الكتم والراحة والنقلة المريحة من المستويات اللي فاتت. التكنيك يسقط لو الجسم شد أو الأوتار المفتوحة غطّت الفورمة.",
 "A repeatable motif, at least 25% silence, one clear dynamic peak, stable downbeats and a final home groove that matches the opening feel.":"موتيف قابل للتكرار، على الأقل ٢٥٪ سكتة، قمة ديناميكية واحدة واضحة، أول نبضات ثابتة، وجروف قرار أخير مطابق لإحساس البداية.",
 "The take becomes a catalogue of tricks, intensity stays high, fills erase beat 1, the home motif disappears, or a miss causes an immediate restart.":"التيك يتحول لكتالوج حركات، الشدة تفضل عالية، الفيلات تمسح النبضة ١، موتيف القرار يختفي، أو غلطة تخليك تبدأ فوراً من الأول.",
 "Finish the take. Mark the bar where identity first weakened, isolate the nearest two-bar checkpoint, repair it for three clean reps, then record one new complete take.":"كمّل التيك. علّم المازورة اللي الهوية ضعفت فيها أول مرة، اعزل أقرب نقطة مراجعة من مازورتين، صلّحها ٣ تكرارات نضيفة، وبعدها سجّل تيك كامل جديد.",
 "One unedited five-minute take scoring at least 80/100 with no jury category below 70, original groove singable afterward, one climax and a relaxed body.":"تيك خمس دقايق واحد من غير مونتاج يجيب على الأقل ٨٠/١٠٠ ومفيش بند أقل من ٧٠، تقدر تغنّي الجروف الأصلي بعده، فيه قمة واحدة والجسم مرتاح.",
 "Log the proof day. Repeat the same form in a new key or return to the earliest weak level; mastery is maintaining musical control, not collecting harder tricks.":"سجّل يوم الإثبات. كرّر نفس الفورمة في مفتاح جديد أو ارجع لأول مستوى ضعيف؛ الإتقان هو الحفاظ على التحكّم الموسيقي مش جمع حركات أصعب.",
 "Tune the bass, choose the maqam and root, start with a drone only, and sing tonic–lower jins–tonic before the clock begins.":"اضبط الباص، اختار المقام والقرار، ابدأ بدرون بس، وغنّي قرار–جنس سفلي–قرار قبل ما الساعة تبدأ.",
 "Treat each phrase as four slow beats: ascend for beats 1–2, descend for beats 3–4, then leave one full breath before the next phrase.":"اعتبر كل جملة أربع نبضات بطيئة: اطلع في ١–٢، انزل في ٣–٤، وبعدها سيب نَفَس كامل قبل الجملة اللي بعدها.",
 "The tonic must feel final and the lower jins must already identify the maqam. Every return should settle within ±15¢ without a last-second correction.":"القرار لازم يحسّسك بالنهاية، والجنس السفلي يعرّف المقام لوحده. كل رجوع يستقر جوّه ±١٥ سنت من غير تعديل في آخر لحظة.",
 "You run the entire octave, reveal the upper jins too early, pause before the cadence, or treat the target microtone as a passing accident.":"تجري الأوكتاف كله، تظهر الجنس العلوي بدري، تقف قبل القفلة، أو تعامل ربع الصوت المطلوب كأنه نغمة عابرة بالغلط.",
 "Return only to tonic plus the first four degrees. Reduce 10 BPM, sing the failed direction, earn three clean lower-jins cadences, then resume at the failed timed step.":"ارجع للقرار وأول أربع درجات بس. انزل ١٠ BPM، غنّي الاتجاه اللي فشل، اعمل ٣ قفلات جنس سفلي نضيفة، وبعدها كمّل من الخطوة الزمنية اللي فشلت.",
 "Repeat once in a second comfortable root. Then choose Quarter-tone intonation for pitch control or Sayr ladder for melodic expansion.":"كرّر مرة على قرار تاني مريح. بعدها اختار ضبط أرباع الصوت للتحكّم في النغمة أو سلّم السير لتوسيع الجملة.",
 "Use headphones, a clean direct bass input and drone only. Locate the lower fret anchor, relax the thumb and hear tonic–target–tonic three times before touching the string.":"استخدم سماعات ومدخل باص مباشر نضيف ودرون بس. حدّد فريت البداية الأقل، ريّح الإبهام، واسمع قرار–هدف–قرار ٣ مرات قبل ما تلمس الوتر.",
 "One attempt lasts four beats: arrive on beat 1, hold through beat 2, release on beat 3, stay silent on beat 4. The blind test contains ten separate attempts.":"كل محاولة أربع نبضات: وصل على ١، ثبّت خلال ٢، ريّح على ٣، واسكت على ٤. الاختبار من غير نظر فيه ١٠ محاولات منفصلة.",
 "A direct, repeatable centre within ±15¢, no overshoot and the same target height after silence. The bend should sound intentional, not searched for.":"مركز مباشر وقابل للتكرار جوّه ±١٥ سنت، من غير ما تعدّي الهدف، ونفس ارتفاع النغمة بعد السكوت. البند يتسمع مقصود مش تدوير.",
 "You stare at the meter, squeeze with the thumb, overshoot and fall back, or allow the reference tone from speakers to enter the microphone.":"تفضل باصص للميتر، تعصر بالإبهام، تعدّي الهدف وترجع، أو تسيب صوت المرجع من السماعات يدخل الميكروفون.",
 "Stop at the nearest attempt. Hear and sing the target, slide slowly from the anchor twice, then make three direct attacks with eyes closed before the timed routine continues.":"قف عند أقرب محاولة. اسمع وغنّي الهدف، اعمل سلايد ببطء من نقطة البداية مرتين، وبعدها ٣ ضربات مباشرة وعينك مغمضة قبل ما الروتين بوقته يكمّل.",
 "Apply the centred pitch inside tonic–microtone–next degree–tonic, then use Root + jins lock or Sayr ladder so intonation serves a phrase.":"طبّق النغمة المظبوطة جوّه قرار–ربع صوت–الدرجة اللي بعدها–قرار، وبعدها استخدم تثبيت القرار والجنس أو سلّم السير عشان الضبط يخدم جملة.",
 "Complete one clean lower-jins cadence first. Select a light Maqsum, mark the ghammaz note and its hand position, and decide which three-note cell will be repeated.":"كمّل قفلة جنس سفلي نضيفة الأول. اختار مقسوم خفيف، علّم نغمة الغمّاز ومكان الإيد، وحدد خلية التلات نغمات اللي هتكررها.",
 "Think in five one-minute destinations: lower world, ghammaz, upper answer, one peak, home. Count two-bar questions and two-bar answers inside each destination.":"فكّر في خمس وجهات كل واحدة دقيقة: المنطقة الواطية، الغمّاز، الإجابة العالية، قمة واحدة، القرار. عُدّ سؤال مازورتين وجواب مازورتين جوّه كل وجهة.",
 "The lower identity arrives before the upper register, the ghammaz sounds like a station, one peak is enough and the final descent reduces tension progressively.":"الهوية الواطية تظهر قبل المنطقة العالية، الغمّاز يتسمع كمحطة، قمة واحدة كفاية، والنزول الأخير يقلل التوتّر واحدة واحدة.",
 "The exercise becomes an even scale, the octave appears before the ghammaz is established, every phrase climbs, or the ending simply stops instead of cadencing.":"التمرين يتحول لسلم متساوي، الأوكتاف يظهر قبل تثبيت الغمّاز، كل الجمل تطلع، أو النهاية تقف وخلاص بدل ما تقفل.",
 "Go back to the last clear station, not minute zero. Restrict yourself to the previous four degrees, repeat the motif three times, then reopen one new degree.":"ارجع لآخر محطة واضحة مش للدقيقة صفر. اقفل على الأربع درجات اللي فاتوا، كرّر الموتيف ٣ مرات، وبعدها افتح درجة جديدة واحدة.",
 "Run the same sayr with a different three-note motif. Then practise Ghammaz bridge if the hand shift is weak, or Maqam switch if the stations are secure.":"اعمل نفس السير بموتيف تلات نغمات مختلف. بعدها درّب جسر الغمّاز لو نقلة الإيد ضعيفة، أو تحويل المقام لو المحطات ثابتة.",
 "Map the lower route and upper route separately. Circle the ghammaz as the shared note, rehearse the shift without sound and use Wahda at 58 BPM.":"ارسم المسار الواطي والعالي كل واحد لوحده. علّم الغمّاز كنغمة مشتركة، درّب النقلة من غير صوت، واستخدم وحدة على ٥٨ BPM.",
 "Use the eight-bar form throughout: 2 bars lower, 2 approach/hold, 2 upper, 2 return. Say the section name on the first beat of each pair.":"استخدم فورمة ٨ موازير طول الوقت: ٢ واطي، ٢ اقتراب/ثبات، ٢ عالي، ٢ رجوع. قول اسم الجزء على أول نبضة من كل زوج.",
 "The pivot remains audible during the move, the thumb and hand travel together, the first upper note arrives after the station and no slide or squeak interrupts time.":"نقطة التحويل تفضل مسموعة وقت الحركة، الإبهام والإيد يتحركوا سوا، أول نغمة عالية تيجي بعد المحطة، ومفيش سلايد أو تزييق يقطع الوقت.",
 "You jump directly into the upper shape, lose the pivot during the shift, stretch instead of moving the hand, or arrive rhythmically late after looking down.":"تنطّ للشكل العالي مباشرة، تضيّع نقطة التحويل في النقلة، تتمط بدل ما تنقل الإيد، أو توصل متأخر إيقاعياً بعد ما تبص تحت.",
 "Freeze on the ghammaz. Release pressure, move the silent hand three times, play pivot→first upper note for three clean pairs, then rejoin at bars 3–4.":"اثبت على الغمّاز. ريّح الضغط، حرّك الإيد بصمت ٣ مرات، اعزف نقطة التحويل←أول نغمة عالية ٣ أزواج نضاف، وبعدها ارجع عند المازورتين ٣–٤.",
 "Transpose the same bridge to one nearby root. When the shift remains silent, use the Maqam switch routine to change melodic identity at that station.":"انقل نفس الجسر لقرار قريب. لما النقلة تفضل هادية، استخدم روتين تحويل المقام عشان تغيّر الهوية اللحنية عند المحطة دي.",
 "Choose one printed FROM→TO route, hear both maqamat separately, name the pivot and the first two changed tones, then rehearse the eight-bar route verbally.":"اختار مسار من←إلى مكتوب، اسمع المقامين كل واحد لوحده، سمّي نقطة التحويل وأول نغمتين متغيرين، وبعدها قول مسار الـ٨ موازير بالكلام.",
 "Bars 1–2 establish, 3–4 approach, bar 5 holds for two beats, bar 6 reveals one changed tone, bar 7 confirms and bar 8 cadences. Keep counting through the hold.":"الموازير ١–٢ تثبيت، ٣–٤ اقتراب، ٥ ثبات نبضتين، ٦ تظهر نغمة متغيرة، ٧ تأكيد، و٨ قفلة. كمّل العد وقت الثبات.",
 "Source identity is undeniable before departure; the pivot remains common; only planned changed tones reveal the destination; the final cadence states whether you stayed or returned.":"هوية المصدر تبقى واضحة قبل الرحيل؛ نقطة التحويل تفضل مشتركة؛ النغمات المتغيرة المخططة بس تظهر المقام الجديد؛ والقفلة الأخيرة تقول كملت ولا رجعت.",
 "You swap full scale shapes at once, introduce the destination before the pivot, stop the pulse during the hand move, or end without confirming a tonal centre.":"تبدّل أشكال سلالم كاملة مرة واحدة، تدخل المقام الجديد قبل نقطة التحويل، توقف النبض وقت حركة الإيد، أو تنهي من غير ما تثبّت قرار.",
 "Return to bar 5. Hold the pivot, sing the first changed tone, play only pivot→changed tone→destination tonic three times, then restart at bar 3 rather than bar 1.":"ارجع للمازورة ٥. ثبّت نقطة التحويل، غنّي أول نغمة متغيرة، واعزف نقطة التحويل←النغمة المتغيرة←قرار المقام الجديد ٣ مرات، وبعدها ابدأ من المازورة ٣ مش ١.",
 "Complete five uninterrupted switches. Then use the backing section’s 8- or 16-bar form and make the same destination audible without visual labels.":"كمّل ٥ تحويلات من غير قطع. بعدها استخدم فورمة ٨ أو ١٦ مازورة في قسم المصاحبة، وخلّي نفس المقام الجديد مسموع من غير علامات بصرية.",
 "Record one continuous take. Choose a home maqam, one three-note motif, one planned pivot and a single destination; set a comfortable drone and decide whether percussion will enter.":"سجّل تيك واحد مستمر. اختار مقام قرار وموتيف تلات نغمات ونقطة تحويل مخططة ومقام جديد واحد؛ حط درون مريح وحدد الإيقاع هيدخل ولا لأ.",
 "Follow six two-minute chapters: home, develop, climb, open, switch, return. Count phrases in four-bar spans and leave at least one full bar of silence in every chapter.":"امشِ في ست فصول كل واحد دقيقتين: قرار، تطوير، طلوع، فتح، تحويل، رجوع. عُدّ الجمل في مجموعات ٤ موازير وسيب على الأقل مازورة سكوت كاملة في كل فصل.",
 "Home is clear in minute 1, the motif remains recognizable through variation, intensity reaches one peak, the switch has evidence and the final minute restores the opening centre.":"القرار واضح في الدقيقة ١، الموتيف يفضل معروف وسط التغيير، الشدة توصل لقمة واحدة، التحويل له دليل، والدقيقة الأخيرة ترجع مركز البداية.",
 "Density stays constant, new ideas replace development, the modulation is an unexplained scale change, silence disappears, or a miss causes you to restart the take.":"الكثافة تفضل ثابتة، أفكار جديدة تاخد مكان التطوير، التحويل يبقى تغيير سلم من غير تفسير، السكتة تختفي، أو غلطة تخليك تبدأ التيك من الأول.",
 "Finish the take. Mark the chapter and nearest four-bar checkpoint where identity failed, repair only that phrase for three clean repetitions, then record one new full proof.":"كمّل التيك. علّم الفصل وأقرب نقطة مراجعة ٤ موازير اللي الهوية فشلت عندها، صلّح الجملة دي بس ٣ تكرارات نضيفة، وبعدها سجّل إثبات كامل جديد.",
 "Score the unedited take against the pass statement. Repeat only the weakest chapter before attempting another full 12-minute proof in a new root.":"قيّم التيك من غير مونتاج قدام شرط النجاح. كرّر أضعف فصل بس قبل ما تحاول إثبات ١٢ دقيقة كامل تاني على قرار جديد.",
 "Put both feet under you, balance the bass without gripping, drop the shoulders and make six slow air-finger movements before sounding a note.":"حط رجليك الاتنين تحتك، وازن الباص من غير قبضة، نزّل كتافك، واعمل ٦ حركات صوابع بطيئة في الهوا قبل ما تطلع نغمة.",
 "Breath stays free, wrist stays neutral, thumb travels with the hand and every note can stop without extra force.":"النَفَس يفضل حر، الرسغ محايد، الإبهام يتحرك مع الإيد، وكل نغمة تقدر تقف من غير قوة زيادة.",
 "A correct route still fails if the jaw, shoulder, wrist or fretting thumb tightens—or if pain, tingling or numbness appears.":"المسار الصح يفضل فاشل لو الفك أو الكتف أو الرسغ أو إبهام الفريتات شدّ—أو لو ظهر وجع أو تنميل أو وخز.",
 "Stop the current movement, release the instrument for one breath, reduce range and tempo, then earn three relaxed repetitions from the nearest position checkpoint.":"وقّف الحركة الحالية، سيب الآلة لمدة نَفَس، قلّل المدى والسرعة، وبعدها اعمل ٣ تكرارات مرتاحة من أقرب نقطة مراجعة للموضع.",
 "Cover the answer, state key and string aloud, find the fret visually and give yourself six seconds to name the note before touching it.":"غطّي الإجابة، قول المفتاح والوتر بصوت عالي، لاقي الفريت بعينك، وادي نفسك ٦ ثواني تسمّي النغمة قبل ما تلمسها.",
 "The spoken note arrives first; after playing, confirm its degree and MILLPAD label in the selected parent key.":"اسم النغمة يتقال الأول؛ بعد العزف راجع درجتها وعلامة MILLPAD في المفتاح الأم المختار.",
 "A lucky finger landing, silent guessing, or naming only after hearing the pitch does not train recall.":"نزلة صباع بالحظ، تخمين صامت، أو تسمية بعد ما تسمع النغمة بس ما بيدرّبوش الاستدعاء.",
 "Return to the same string and a neighbouring natural-note anchor. Name anchor, count semitones to the target, then retest the original fret twice without playing first.":"ارجع لنفس الوتر ولنغمة طبيعية قريبة كمرجع. سمّي المرجع، عُدّ أنصاف التون للهدف، وبعدها اختبر الفريت الأصلي مرتين من غير ما تعزف الأول.",
 "Say the chunk label, interval order and fingering; air-finger the three offsets with the thumb released before putting pressure on the string.":"قول علامة الخلية وترتيب المسافات والصوابع؛ حرّك الصوابع في الهوا على التلات إزاحات والإبهام مرتاح قبل ما تدوس الوتر.",
 "All three notes speak evenly, the half step appears in the correct place and the chosen fingering does not force a stretch.":"التلات نغمات ينطقوا بالتساوي، نص التون يظهر في مكانه الصح، والصوابع المختارة ما تجبرش الإيد على مطّة.",
 "Memorizing fret numbers without the interval pattern, collapsing fingers, or changing tempo at the half step hides the actual shape.":"حفظ أرقام الفريتات من غير شكل المسافات، وقوع الصوابع، أو تغيير السرعة عند نص التون بيخبّي الشكل الحقيقي.",
 "Play only the two-note interval that failed, say H or W, repeat it three times, then rebuild the complete three-note chunk from that checkpoint.":"اعزف مسافة النغمتين اللي فشلت بس، قول H أو W، كرّرها ٣ مرات، وبعدها ابنِ خلية التلات نغمات كاملة من نقطة المراجعة دي.",
 "Recite the local cycle around the starting label, predict the next label and say whether the crossing stays in column or shifts before revealing anything.":"قول الدورة المحلية حوالين علامة البداية، توقّع العلامة اللي بعدها، وقول عبور الوتر هيفضل في العمود ولا هينقل قبل ما تكشف أي حاجة.",
 "Label, mode, shape and exception agree; the Ly↔Lo tritone shift is announced before the hand moves.":"العلامة والمود والشكل والاستثناء متفقين؛ نقلة الترايتون Ly↔Lo تتقال قبل ما الإيد تتحرك.",
 "Reciting all seven labels mechanically while losing the current state, direction or shift location is not usable knowledge.":"تسميع السبع علامات آلياً مع ضياع الحالة أو الاتجاه أو مكان النقلة مش معرفة قابلة للاستخدام.",
 "Keep only current label → next label. Verify that pair, add its shape, then restore one preceding and one following label before returning to the prompt.":"خلّي العلامة الحالية ← العلامة اللي بعدها بس. راجع الزوج، ضيف شكله، وبعدها رجّع علامة قبله وعلامة بعده قبل ما ترجع للسؤال.",
 "State four pieces of state: key, direction, starting string and starting chunk. Generate labels and fret columns on paper or aloud before uncovering the route.":"قول أربع معلومات للحالة: المفتاح والاتجاه ووتر البداية وخلية البداية. ولّد العلامات وأعمدة الفريتات على ورق أو بصوت عالي قبل ما تكشف المسار.",
 "Three parent-scale notes occur per string, the turn uses the next in-key note and every column change is explained by the tritone exception.":"تلات نغمات من السلم الأم على كل وتر، اللفة تستخدم النغمة اللي بعدها جوّه المفتاح، وكل تغيير عمود يفسّره استثناء الترايتون.",
 "Following tab by sight, restarting after a crossing miss, or changing more than the current string chunk prevents true route generation.":"متابعة التاب بالعين، البداية من الأول بعد غلطة عبور، أو تغيير أكتر من خلية الوتر الحالية يمنع توليد المسار الحقيقي.",
 "Restart at checkpoint A–E nearest the failed crossing. Say old label, new label and column change; air-finger that crossing three times, then continue the remaining row.":"ارجع لنقطة المراجعة A–E الأقرب لعبور الوتر اللي فشل. قول العلامة القديمة والجديدة وتغيير العمود؛ حرّك صوابع العبور في الهوا ٣ مرات، وبعدها كمّل باقي الصف.",
 "Read purpose and variation before the tab. Sing or clap its rhythm, identify its entry checkpoint and set a tempo that leaves spare attention.":"اقرا الهدف والتغيير قبل التاب. غنّي أو سقّف الإيقاع، حدّد نقطة مراجعة الدخول، وحط سرعة تسيب لك تركيز زيادة.",
 "The intended deformation is audible while the parent route, alternation, muting and time remain intact.":"التغيير المقصود مسموع، ومسار الأصل والتبادل والكتم والوقت لسه سليمين.",
 "Treating the passage as a speed lick, adding the variation before the base is stable, or restarting the whole passage after one miss conceals the weak link.":"معاملة المقطع كليك سرعة، إضافة التغيير قبل ثبات الأساس، أو بداية المقطع كله من الأول بعد غلطة واحدة بيخبّوا الوصلة الضعيفة.",
 "Mark the smallest two- to four-note cell around the miss, drop two rungs, pass that cell three times, then enter one note before it and continue forward.":"علّم أصغر خلية من نغمتين لأربع حوالين الغلطة، انزل درجتين سرعة، نجّح الخلية ٣ مرات، وبعدها ادخل من نغمة قبلها وكمّل لقدام.",
 "Choose the parent key, set a comfortable root drone and sing root plus the target degree before mapping it on the instrument.":"اختار المفتاح الأم، حط درون قرار مريح، وغنّي القرار والدرجة المطلوبة قبل ما ترسمها على الآلة.",
 "Every played note is named by function, the root remains internally audible and intonation settles without hunting.":"كل نغمة متعزوفة تتسمّى بوظيفتها، القرار يفضل مسموع جواك، وضبط النغمة يستقر من غير تدوير.",
 "Letting the drone become background noise, running shapes without singing, or correcting pitch only by looking removes the ear from the task.":"تحويل الدرون لدوشة في الخلفية، جري الأشكال من غير غنا، أو تصحيح النغمة بالعين بس بيشيل الودن من المهمة.",
 "Mute the bass, sing root→target→root twice, play only those two notes for three centred repetitions, then restore the current chunk.":"اكتم الباص، غنّي قرار←هدف←قرار مرتين، اعزف النغمتين دول بس ٣ تكرارات مظبوطة، وبعدها رجّع الخلية الحالية.",
 "Cover all routes, choose a random key and state, start recording and accept the first prompt without a rehearsal attempt.":"غطّي كل المسارات، اختار مفتاح وحالة عشوائيين، ابدأ التسجيل، واقبل أول سؤال من غير محاولة بروفة.",
 "The answer is generated within the time limit, execution remains even and the explanation names both the rule and any exception.":"الإجابة تتولّد جوّه الوقت، التنفيذ يفضل متساوي، والشرح يسمّي القاعدة وأي استثناء.",
 "Pausing the clock, changing the prompt, revealing before answering or editing out misses invalidates the evidence.":"توقيف الساعة، تغيير السؤال، الكشف قبل الإجابة، أو حذف الغلطات بالمونتاج يبطل الدليل.",
 "Finish and score the attempt. Isolate only the lowest category for three clean repairs, then take one completely new assessment prompt.":"كمّل وقيّم المحاولة. اعزل أضعف بند بس لـ٣ إصلاحات نضيفة، وبعدها خد سؤال تقييم جديد تماماً.",
 "Keep the just-finished take available. Write what actually happened before deciding what tomorrow should contain.":"خلّي التيك اللي خلص حالاً متاح. اكتب اللي حصل فعلاً قبل ما تقرر تمرين بكرة فيه إيه.",
 "Tempo rung, clean count, error code, body state and nearest repair point are specific enough to reproduce the session.":"درجة السرعة وعدد النضيف وكود الغلطة وحالة الجسم وأقرب نقطة إصلاح محددين كفاية إنك تعيد الجلسة.",
 "Writing ‘good’ or ‘bad’, logging only the fastest tempo, or hiding tension creates no usable practice evidence.":"كتابة كويس أو وحش، تسجيل أسرع سرعة بس، أو إخفاء الشدّ ما بيعملش دليل تمرين مفيد.",
 "Replay the hardest moment, name one audible or physical cause, and rewrite tomorrow’s instruction as one observable action plus one pass condition.":"اسمع أصعب لحظة تاني، سمّي سبب مسموع أو جسدي واحد، واكتب تعليمات بكرة كفعل واحد قابل للملاحظة ومعاه شرط نجاح واحد.",
};

const SNIPPETS:Array<[string,string]>=[
 ["Warm, vocal and grounded.","دافئ وغنائي وثابت."],
 ["Stable, open and authoritative.","ثابت ومفتوح وواثق."],
 ["Focused and high-contrast.","مركّز وتباينه قوي."],
 ["Minor-coloured and highly useful","لونه ماينور ومفيد جداً"],
 ["Dark and direct.","داكن ومباشر."],
 ["Bright and declarative.","مشرق وواضح."],
 ["Tense, intimate and non-octave-equivalent","حساس ومشدود ومش لازم يتكرر بنفس الشكل في الأوكتاف"],
 ["A microtonal tonic changes the entire hand map","القرار الميكروتوني بيغيّر خريطة الإيد كلها"],
 ["Establish the lower","ثبّت الجزء الواطي من"],
 ["then descend","وبعدين انزل"],
 ["return to the tonic","ارجع للقرار"],
 ["Do not treat","ما تتعاملش مع"],
 ["Do not exaggerate","ما تبالغش في"],
 ["Do not lean","ما تركّزش زيادة على"],
 ["Do not run the scale","ما تجريش السلم طالع نازل"],
 ["Use the drone","استخدم الدرون"],
 ["against the drone","قدّام الدرون"],
 ["lower jins","الجنس السفلي"],
 ["upper jins","الجنس العلوي"],
 ["the ghammaz","الغمّاز"],
 ["the tonic","القرار"],
 ["quarter-tone","ربع الصوت"],
 ["microtonal","ميكروتوني"],
 ["fretless bass","باص فريتلس"],
 ["fretted bass","باص بفريتات"],
 ["equal-tempered","بالضبط المتساوي"],
 ["Practice","تمرّن"],
 ["practice","تمرين"],
 ["Exercise","تمرين"],
 ["exercise","التمرين"],
 ["Listen","اسمع"],
 ["listen","اسمع"],
 ["Play","اعزف"],
 ["play","اعزف"],
 ["Repeat","كرّر"],
 ["repeat","كرّر"],
 ["Hold","ثبّت"],
 ["hold","ثبّت"],
 ["Shift","انقل الإيد"],
 ["shift","نقلة"],
 ["Return","ارجع"],
 ["return","رجوع"],
 ["Target","هدف"],
 ["target","الهدف"],
 ["Listener target:","هدف الاستماع:"],
 ["Fret anchor","بداية الفريت"],
 ["-MIN HANDS-FREE ROUTINE"," دقيقة · روتين من غير لمس الشاشة"],
 ["● START","● ابدأ"],
 ["first station at","أول محطة عند"],
 ["bend","بند"],
 ["Root","قرار"],
 ["root","القرار"],
 ["Degree","درجة"],
 ["degree","درجة"],
 ["String","وتر"],
 ["string","وتر"],
 ["Fret","فريت"],
 ["fret","فريت"],
 ["Finger","صباع"],
 ["finger","صباع"],
 ["Minutes","دقايق"],
 ["minutes","دقايق"],
 ["Minute","دقيقة"],
 ["minute","دقيقة"],
 ["Seconds","ثواني"],
 ["seconds","ثواني"],
 ["Bars","موازير"],
 ["bars","موازير"],
 ["Bar","مازورة"],
 ["bar","مازورة"],
 ["Lesson","درس"],
 ["lesson","الدرس"],
 ["Course","كورس"],
 ["course","الكورس"],
 ["Score","النتيجة"],
 ["score","النتيجة"],
 ["Pass","نجاح"],
 ["pass","ينجح"],
 ["Wrong note","نغمة غلط"],
 ["wrong note","نغمة غلط"],
 ["with no pause","من غير توقف"],
 ["without stopping","من غير ما توقف"],
 ["hands-free","من غير لمس الشاشة"],
 ["audio interface","كارت الصوت"],
 ["headphones","سماعات"],
 ["backing track","المصاحبة"],
 ["melodic course","المسار اللحني"],
 ["melodic phrase","جملة لحنية"],
 ["characteristic tone","نغمة اللون المميّزة"],
 ["tonal centre","القرار الأساسي"],
 ["chord tones","نغمات الكورد"],
 ["outside note","نغمة برّه"],
 ["inside the mode","جوه المقام"],
 ["strong beat","نبضة قوية"],
 ["clean repetitions","تكرارات نضيفة"],
 ["exact destination","هدف محدد"],
 ["rhythmic placement","مكانها في الإيقاع"],
 ["one octave","أوكتاف واحد"],
 ["one continuous take","تسجيل واحد من غير قطع"],
 ["No visual help","من غير مساعدة بصرية"],
 ["No diagram","من غير رسومات"],
 ["No stopping","من غير توقف"],
];

function translateTemplates(text:string){
 let value=text;
 value=value.replace(/UNIT\s+(\d+)\s*·\s*LESSON\s+(\d+)/gi,(_,a,b)=>`الوحدة ${a} · الدرس ${b}`);
 value=value.replace(/LESSON\s+(\d+)\s+OF\s+(\d+)/gi,(_,a,b)=>`الدرس ${a} من ${b}`);
 value=value.replace(/UNIT\s+(\d+)\s+OF\s+(\d+)/gi,(_,a,b)=>`الوحدة ${a} من ${b}`);
 value=value.replace(/STAGE\s+(\d+)\s+OF\s+(\d+)/gi,(_,a,b)=>`المرحلة ${a} من ${b}`);
 value=value.replace(/DAY\s+(\d+)/gi,(_,a)=>`اليوم ${a}`);
 value=value.replace(/(\d+)\s*MIN(?:UTE)?S?/gi,(_,a)=>`${a} دقيقة`);
 value=value.replace(/(\d+)\s*SEC(?:OND)?S?/gi,(_,a)=>`${a} ثانية`);
 value=value.replace(/FRET\s+(\d+)/gi,(_,a)=>`فريت ${a}`);
 value=value.replace(/BAR\s+(\d+)/gi,(_,a)=>`مازورة ${a}`);
 value=value.replace(/STRING\s+([EADGBC])/gi,(_,a)=>`وتر ${a}`);
 value=value.replace(/([EADGBC])\s+STRING/gi,(_,a)=>`وتر ${a}`);
 value=value.replace(/^([A-G](?:♯|♭)?)\s+([A-Za-z]+): repeat the lower (.+)\.$/,(_,note,mode,jins)=>`${note} ${mode}: كرّر ${jins} في المنطقة الواطية.`);
 value=value.replace(/^Climb toward ([A-G](?:♯|♭)?); make the source identity clear before leaving\.$/,(_,note)=>`اطلع ناحية ${note}، وخلّي هوية المقام الأصلي واضحة قبل ما تسيبه.`);
 value=value.replace(/^Hold ([A-G](?:♯|♭)?) for two beats\. Keep that finger as the visual and aural guide\.$/,(_,note)=>`ثبّت ${note} نبضتين. خلّي الصباع ده مرشد للعين والودن.`);
 value=value.replace(/^Introduce ([A-G](?:♯|♭)?) then ([A-G](?:♯|♭)?); do not run the whole scale\.$/,(_,a,b)=>`دخل ${a} وبعدها ${b}؛ ما تجريش المقام كله طالع نازل.`);
 value=value.replace(/^Answer with (.+) around ([A-G](?:♯|♭)?)\.$/,(_,jins,note)=>`جاوب بـ${jins} حوالين ${note}.`);
 value=value.replace(/^Resolve to ([A-G](?:♯|♭)?) to stay, or retrace the pivot to ([A-G](?:♯|♭)?) to return\.$/,(_,a,b)=>`اقفل على ${a} لو هتكمّل في المقام الجديد، أو ارجع من نقطة التحويل لـ${b}.`);
 const labels:Record<string,string>={"LISTEN":"اسمع","REFERENCE":"مرجع","ROOT":"القرار","LOWER JINS":"الجنس السفلي","QUESTION / ANSWER":"سؤال / جواب","PROOF":"إثبات","SLOW ARRIVAL":"وصول بطيء","DIRECT ATTACK":"ضربة مباشرة","IN CONTEXT":"جوه الجملة","BLIND TEST":"اختبار من غير نظر","LOWER WORLD":"المنطقة الواطية","UPPER ANSWER":"الإجابة العالية","CONTROLLED PEAK":"قمة متحكّم فيها","HOME CADENCE":"قفلة للقرار","STATION":"محطة","SHIFT WITHOUT SOUND":"نقلة هادية","UPPER JINS":"الجنس العلوي","TWO DIRECTIONS":"اتجاهين","EIGHT-BAR FORM":"فورمة ٨ موازير","FROM":"من المصدر","PIVOT":"نقطة التحويل","CHANGE ONE TONE":"غيّر نغمة واحدة","COMPLETE DESTINATION":"ثبّت المقام الجديد","FIVE SWITCHES":"خمس تحويلات","DECLARE HOME":"أعلن القرار","DEVELOP":"طوّر","CLIMB":"اطلع","OPEN":"افتح","SWITCH":"حوّل","RETURN":"ارجع"};
 for(const [english,arabic] of Object.entries(labels))value=value.replace(new RegExp(`\\b${english.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")}\\b`,"g"),arabic);
 return value;
}

function preserveWhitespace(original:string,translated:string){
 const lead=original.match(/^\s*/)?.[0]??"",trail=original.match(/\s*$/)?.[0]??"";
 return `${lead}${translated}${trail}`;
}

export function toEgyptianArabic(input:string){
 const body=input.trim();
 if(!body||/[\u0600-\u06ff]/.test(body)&&!/[A-Za-z]{3}/.test(body))return input;
 const exact=DETAIL_EXACT[body]??EXACT[body];if(exact)return preserveWhitespace(input,exact);
 if(/^(?:[A-G](?:♯|♭)?\d?|[1-8](?:↓|\*)?|[+−-]?\d+¢|[HWSPALoy-]+)(?:\s*[·/→|,+-]\s*(?:[A-G](?:♯|♭)?\d?|[1-8](?:↓|\*)?|[+−-]?\d+¢|[HWSPALoy-]+))*$/i.test(body))return input;
 let translated=translateTemplates(body);
 for(const [english,arabic] of SNIPPETS.sort((a,b)=>b[0].length-a[0].length))translated=translated.replaceAll(english,arabic);
 translated=translated.replace(/\bAND\b/g,"و").replace(/\bWITH\b/g,"مع").replace(/\bWITHOUT\b/g,"من غير").replace(/\bTHE\b/g,"").replace(/\bOF\b/g,"من").replace(/\bTO\b/g,"إلى");
 return preserveWhitespace(input,translated);
}

function translateAttribute(element:HTMLElement,name:"aria-label"|"title"|"placeholder",arabic:boolean){
 const dataName=`data-egyptian-${name}`;
 const current=element.getAttribute(name);
 if(arabic){
  if(current&&!element.hasAttribute(dataName))element.setAttribute(dataName,current);
  const original=element.getAttribute(dataName);if(original)element.setAttribute(name,toEgyptianArabic(original));
 }else{const original=element.getAttribute(dataName);if(original)element.setAttribute(name,original)}
}

const subscribeLanguage=(callback:()=>void)=>{window.addEventListener("storage",callback);window.addEventListener("basslab-language",callback);return()=>{window.removeEventListener("storage",callback);window.removeEventListener("basslab-language",callback)}};
const languageSnapshot=()=>window.localStorage.getItem(STORAGE_KEY)==="ar-EG";
const serverLanguageSnapshot=()=>false;

export function useEgyptianArabic(){
 return useSyncExternalStore(subscribeLanguage,languageSnapshot,serverLanguageSnapshot);
}

export default function EgyptianArabicToggle(){
 const arabic=useEgyptianArabic();
 const originalsRef=useRef(new Map<Text,string>()),expectedRef=useRef(new Map<Text,string>());
 useEffect(()=>{
  const root=document.querySelector<HTMLElement>(".courseOs");if(!root)return;
  const originals=originalsRef.current,expected=expectedRef.current;
  const isExcluded=(node:Text)=>node.parentElement?.closest("[data-no-translate],script,style,code")!==null;
  const applyText=(node:Text)=>{
   if(isExcluded(node))return;
   const current=node.nodeValue??"";
   if(arabic){
    const previousExpected=expected.get(node),previousOriginal=originals.get(node);
    if(previousOriginal===undefined||current!==previousExpected&&current!==previousOriginal)originals.set(node,current);
    const translated=toEgyptianArabic(originals.get(node)??current);expected.set(node,translated);if(current!==translated)node.nodeValue=translated;
   }else if(originals.has(node)){const original=originals.get(node)!;expected.delete(node);if(current!==original)node.nodeValue=original}
  };
  const applyTree=(node:Node)=>{
   if(node.nodeType===Node.TEXT_NODE){applyText(node as Text);return}
   if(node.nodeType!==Node.ELEMENT_NODE)return;
   const element=node as HTMLElement;if(element.closest("[data-no-translate]"))return;
   const walker=document.createTreeWalker(element,NodeFilter.SHOW_TEXT);let text=walker.nextNode();while(text){applyText(text as Text);text=walker.nextNode()}
   element.querySelectorAll<HTMLElement>("[aria-label],[title],[placeholder]").forEach(x=>{translateAttribute(x,"aria-label",arabic);translateAttribute(x,"title",arabic);translateAttribute(x,"placeholder",arabic)});
  };
  root.classList.toggle("egyptian-arabic",arabic);document.documentElement.lang=arabic?"ar-EG":"en";document.documentElement.dir=arabic?"rtl":"ltr";
  applyTree(root);
  const observer=new MutationObserver(records=>records.forEach(record=>{if(record.type==="characterData")applyText(record.target as Text);record.addedNodes.forEach(applyTree)}));
  observer.observe(root,{subtree:true,childList:true,characterData:true});
  window.dispatchEvent(new CustomEvent("basslab-language",{detail:{language:arabic?"ar-EG":"en"}}));
  return()=>observer.disconnect();
 },[arabic]);
 const toggle=()=>{const next=!arabic;window.localStorage.setItem(STORAGE_KEY,next?"ar-EG":"en");window.dispatchEvent(new CustomEvent("basslab-language",{detail:{language:next?"ar-EG":"en"}}))};
 return <button data-no-translate className="egyptianToggle" aria-pressed={arabic} onClick={toggle} title={arabic?"Switch the whole site to English":"حوّل الموقع كله للمصري"}><span>{arabic?"EN":"مصري"}</span><small>{arabic?"English":"Egyptian Arabic"}</small></button>;
}
